// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genApplicationsReadInfoCmd() *cobra.Command {
	var dataJSON string
	var fApplicationID string
	cmd := &cobra.Command{
		Use:   "application-info",
		Short: "Get application detail",
		Long: `Get application detail.

Retrieve full details of a single RUM application by 'application_id'.

API: POST /rum/application/info (rum-application-read-info)

Request fields:
  --application-id string (required) — RUM application ID.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) — Account ID.
  - alerting (object) — Alert settings for the application.
    - channel_ids (array<integer>) — Channel IDs to send alerts to.
    - enabled (boolean) — Whether alerting is enabled.
    - integration_id (integer) — Associated on-call integration ID (read-only, auto-assigned).
  - application_id (string) — Unique application ID.
  - application_name (string) — Application display name.
  - client_token (string) — Token used to initialize the RUM SDK.
  - created_at (integer) — Creation timestamp, Unix epoch seconds.
  - created_by (integer) — Creator member ID.
  - is_private (boolean) — If 'true', the application is only accessible to team members.
  - no_geo (boolean) — If 'true', geographic location is not inferred from IP.
  - no_ip (boolean) — If 'true', IP addresses are not collected.
  - status (string) — Application status. [enabled, disabled, deleted]
  - team_id (integer) — Owning team ID.
  - tracing (object) — APM tracing integration settings.
    - enabled (boolean) — Whether tracing integration is enabled.
    - endpoint (string) — Trace endpoint URL (http or https).
    - open_type (string) — How to open the trace link. [popup, tab]
  - type (string) — Application type. [browser, ios, android, react-native, flutter, kotlin-multiplatform, roku, unity]
  - updated_at (integer) — Last update timestamp, Unix epoch seconds.
  - updated_by (integer) — Last updater member ID.
`,
		Example: `  flashduty rum application-info --data '{"application_id":"WoyQQ3BohkdtPivubEvE8o"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("application-id") {
						body["application_id"] = fApplicationID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.RUMApplicationIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Applications.ReadInfo(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fApplicationID, "application-id", "", "RUM application ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genApplicationsReadInfosCmd() *cobra.Command {
	var dataJSON string
	var fApplicationIDs []string
	cmd := &cobra.Command{
		Use:   "application-infos",
		Short: "Batch get applications",
		Long: `Batch get applications.

Retrieve details for multiple RUM applications by their IDs in one request.

API: POST /rum/application/infos (rum-application-read-infos)

Request fields:
  --application-ids []string (required) — Up to 200 application IDs.

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>)
    - account_id (integer) — Account ID.
    - alerting (object) — Alert settings for the application.
      - channel_ids (array<integer>) — Channel IDs to send alerts to.
      - enabled (boolean) — Whether alerting is enabled.
      - integration_id (integer) — Associated on-call integration ID (read-only, auto-assigned).
    - application_id (string) — Unique application ID.
    - application_name (string) — Application display name.
    - client_token (string) — Token used to initialize the RUM SDK.
    - created_at (integer) — Creation timestamp, Unix epoch seconds.
    - created_by (integer) — Creator member ID.
    - is_private (boolean) — If 'true', the application is only accessible to team members.
    - no_geo (boolean) — If 'true', geographic location is not inferred from IP.
    - no_ip (boolean) — If 'true', IP addresses are not collected.
    - status (string) — Application status. [enabled, disabled, deleted]
    - team_id (integer) — Owning team ID.
    - tracing (object) — APM tracing integration settings.
      - enabled (boolean) — Whether tracing integration is enabled.
      - endpoint (string) — Trace endpoint URL (http or https).
      - open_type (string) — How to open the trace link. [popup, tab]
    - type (string) — Application type. [browser, ios, android, react-native, flutter, kotlin-multiplatform, roku, unity]
    - updated_at (integer) — Last update timestamp, Unix epoch seconds.
    - updated_by (integer) — Last updater member ID.
`,
		Example: `  flashduty rum application-infos --data '{"application_ids":["eWbr4xk3ZRnLabRa6unqwD","WoyQQ3BohkdtPivubEvE8o"]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("application-ids") {
						body["application_ids"] = fApplicationIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.RUMApplicationInfosRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Applications.ReadInfos(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringSliceVar(&fApplicationIDs, "application-ids", nil, "Up to 200 application IDs. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genApplicationsReadListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fAsc bool
	var fIsMyTeam bool
	var fOrderby string
	var fQuery string
	var fTeamID int64
	cmd := &cobra.Command{
		Use:   "application-list",
		Short: "List applications",
		Long: `List applications.

Return a paginated list of RUM applications accessible to the current user.

API: POST /rum/application/list (rum-application-read-list)

Request fields:
  --page int — Page number (1-based). Default: 1.
  --limit int — Page size. Range: 1–100. Default: 20.
  --search-after-ctx string
  --asc bool — Sort ascending if 'true'.
  --is-my-team bool — If 'true', return only applications belonging to the current user's teams.
  --orderby string — Sort field. [created_at, updated_at]
  --query string — Search query to filter by application name.
  --team-id int — Filter by team ID.

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - has_next_page (boolean)
  - items (array<object>)
    - account_id (integer) — Account ID.
    - alerting (object) — Alert settings for the application.
      - channel_ids (array<integer>) — Channel IDs to send alerts to.
      - enabled (boolean) — Whether alerting is enabled.
      - integration_id (integer) — Associated on-call integration ID (read-only, auto-assigned).
    - application_id (string) — Unique application ID.
    - application_name (string) — Application display name.
    - client_token (string) — Token used to initialize the RUM SDK.
    - created_at (integer) — Creation timestamp, Unix epoch seconds.
    - created_by (integer) — Creator member ID.
    - is_private (boolean) — If 'true', the application is only accessible to team members.
    - no_geo (boolean) — If 'true', geographic location is not inferred from IP.
    - no_ip (boolean) — If 'true', IP addresses are not collected.
    - status (string) — Application status. [enabled, disabled, deleted]
    - team_id (integer) — Owning team ID.
    - tracing (object) — APM tracing integration settings.
      - enabled (boolean) — Whether tracing integration is enabled.
      - endpoint (string) — Trace endpoint URL (http or https).
      - open_type (string) — How to open the trace link. [popup, tab]
    - type (string) — Application type. [browser, ios, android, react-native, flutter, kotlin-multiplatform, roku, unity]
    - updated_at (integer) — Last update timestamp, Unix epoch seconds.
    - updated_by (integer) — Last updater member ID.
  - total (integer)
`,
		Example: `  flashduty rum application-list --data '{"is_my_team":false,"limit":20,"p":1,"query":""}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("page") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("asc") {
						body["asc"] = fAsc
					}
					if cmd.Flags().Changed("is-my-team") {
						body["is_my_team"] = fIsMyTeam
					}
					if cmd.Flags().Changed("orderby") {
						body["orderby"] = fOrderby
					}
					if cmd.Flags().Changed("query") {
						body["query"] = fQuery
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.RUMApplicationListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Applications.ReadList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "page", 0, "Page number (1-based). Default: 1.")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size. Range: 1–100. Default: 20.")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().BoolVar(&fAsc, "asc", false, "Sort ascending if 'true'.")
	cmd.Flags().BoolVar(&fIsMyTeam, "is-my-team", false, "If 'true', return only applications belonging to the current user's teams.")
	cmd.Flags().StringVar(&fOrderby, "orderby", "", "Sort field. [created_at, updated_at]")
	cmd.Flags().StringVar(&fQuery, "query", "", "Search query to filter by application name.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Filter by team ID.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genApplicationsWriteCreateCmd() *cobra.Command {
	var dataJSON string
	var fApplicationName string
	var fIsPrivate bool
	var fNoGeo bool
	var fNoIP bool
	var fTeamID int64
	var fType string
	cmd := &cobra.Command{
		Use:   "application-create",
		Short: "Create application",
		Long: `Create application.

Create a new RUM application. Returns the generated 'application_id' and 'client_token'.

API: POST /rum/application/create (rum-application-write-create)

Request fields:
  --application-name string (required) — Application name. 1–40 characters.
  --is-private bool — Restrict access to team members only.
  --no-geo bool — Do not infer geographic location.
  --no-ip bool — Do not collect IP addresses.
  --team-id int (required) — Owning team ID.
  --type string (required) — Application type. [browser, ios, android, react-native, flutter, kotlin-multiplatform, roku, unity]
  alerting (object, via --data) — Alert settings for the application.
    - channel_ids (array<integer>) — Channel IDs to send alerts to.
    - enabled (boolean) — Whether alerting is enabled.
    - integration_id (integer) — Associated on-call integration ID (read-only, auto-assigned).
  tracing (object, via --data) — APM tracing integration settings.
    - enabled (boolean) — Whether tracing integration is enabled.
    - endpoint (string) — Trace endpoint URL (http or https).
    - open_type (string) — How to open the trace link. [popup, tab]

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - application_id (string) — Auto-generated unique application ID.
  - application_name (string) — Application display name.
  - client_token (string) — Token for RUM SDK initialization.
`,
		Example: `  flashduty rum application-create --data '{"application_name":"My Web App","is_private":false,"team_id":2477033058131,"type":"browser"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("application-name") {
						body["application_name"] = fApplicationName
					}
					if cmd.Flags().Changed("is-private") {
						body["is_private"] = fIsPrivate
					}
					if cmd.Flags().Changed("no-geo") {
						body["no_geo"] = fNoGeo
					}
					if cmd.Flags().Changed("no-ip") {
						body["no_ip"] = fNoIP
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("type") {
						body["type"] = fType
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.RUMApplicationCreateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Applications.WriteCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fApplicationName, "application-name", "", "Application name. 1–40 characters. (required)")
	cmd.Flags().BoolVar(&fIsPrivate, "is-private", false, "Restrict access to team members only.")
	cmd.Flags().BoolVar(&fNoGeo, "no-geo", false, "Do not infer geographic location.")
	cmd.Flags().BoolVar(&fNoIP, "no-ip", false, "Do not collect IP addresses.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Owning team ID. (required)")
	cmd.Flags().StringVar(&fType, "type", "", "Application type. (required) [browser, ios, android, react-native, flutter, kotlin-multiplatform, roku, unity]")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genApplicationsWriteDeleteCmd() *cobra.Command {
	var dataJSON string
	var fApplicationID string
	cmd := &cobra.Command{
		Use:   "application-delete",
		Short: "Delete application",
		Long: `Delete application.

Delete a RUM application by 'application_id'.

API: POST /rum/application/delete (rum-application-write-delete)

Request fields:
  --application-id string (required) — RUM application ID.
`,
		Example: `  flashduty rum application-delete --data '{"application_id":"qLpu24Dz4CAzWsESPbJYWA"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("application-id") {
						body["application_id"] = fApplicationID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.RUMApplicationIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Applications.WriteDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /rum/application/delete")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fApplicationID, "application-id", "", "RUM application ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genApplicationsWriteUpdateCmd() *cobra.Command {
	var dataJSON string
	var fApplicationID string
	var fApplicationName string
	var fIsPrivate bool
	var fNoGeo bool
	var fNoIP bool
	var fTeamID int64
	var fType string
	cmd := &cobra.Command{
		Use:   "application-update",
		Short: "Update application",
		Long: `Update application.

Update an existing RUM application. All fields except 'application_id' are optional — only provided fields are updated.

API: POST /rum/application/update (rum-application-write-update)

Request fields:
  --application-id string (required) — Application ID to update.
  --application-name string — New application name.
  --is-private bool
  --no-geo bool
  --no-ip bool
  --team-id int
  --type string [browser, ios, android, react-native, flutter, kotlin-multiplatform, roku, unity]
  alerting (object, via --data) — Alert settings for the application.
    - channel_ids (array<integer>) — Channel IDs to send alerts to.
    - enabled (boolean) — Whether alerting is enabled.
    - integration_id (integer) — Associated on-call integration ID (read-only, auto-assigned).
  tracing (object, via --data) — APM tracing integration settings.
    - enabled (boolean) — Whether tracing integration is enabled.
    - endpoint (string) — Trace endpoint URL (http or https).
    - open_type (string) — How to open the trace link. [popup, tab]
`,
		Example: `  flashduty rum application-update --data '{"alerting":{"channel_ids":[2490121812131],"enabled":true},"application_id":"WoyQQ3BohkdtPivubEvE8o","application_name":"My Web App v2"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("application-id") {
						body["application_id"] = fApplicationID
					}
					if cmd.Flags().Changed("application-name") {
						body["application_name"] = fApplicationName
					}
					if cmd.Flags().Changed("is-private") {
						body["is_private"] = fIsPrivate
					}
					if cmd.Flags().Changed("no-geo") {
						body["no_geo"] = fNoGeo
					}
					if cmd.Flags().Changed("no-ip") {
						body["no_ip"] = fNoIP
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("type") {
						body["type"] = fType
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.RUMApplicationUpdateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Applications.WriteUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /rum/application/update")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fApplicationID, "application-id", "", "Application ID to update. (required)")
	cmd.Flags().StringVar(&fApplicationName, "application-name", "", "New application name.")
	cmd.Flags().BoolVar(&fIsPrivate, "is-private", false, "Request field is_private")
	cmd.Flags().BoolVar(&fNoGeo, "no-geo", false, "Request field no_geo")
	cmd.Flags().BoolVar(&fNoIP, "no-ip", false, "Request field no_ip")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Request field team_id")
	cmd.Flags().StringVar(&fType, "type", "", "Request field type [browser, ios, android, react-native, flutter, kotlin-multiplatform, roku, unity]")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedApplications(root *cobra.Command) {
	gRUM := genGroup(root, "rum", "RUM API")
	genAddLeaf(gRUM, genApplicationsReadInfoCmd())
	genAddLeaf(gRUM, genApplicationsReadInfosCmd())
	genAddLeaf(gRUM, genApplicationsReadListCmd())
	genAddLeaf(gRUM, genApplicationsWriteCreateCmd())
	genAddLeaf(gRUM, genApplicationsWriteDeleteCmd())
	genAddLeaf(gRUM, genApplicationsWriteUpdateCmd())
}
