// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import "github.com/spf13/cobra"

func genImIntegrationsListCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "im-war-room-enabled-list",
		Short: "List war-room-enabled IM integrations",
		Long: `List war-room-enabled IM integrations.

List IM integrations that have the war-room feature enabled for the account.

API: POST /datasource/im/war-room-enabled/list (im-war-room-enabled-list)

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>) — IM integrations with the war-room feature enabled.
    - account_id (integer) — Account this integration belongs to.
    - category (string) — Category of the integration plugin.
    - created_at (integer) — Unix timestamp in seconds when the integration was created.
    - creator_id (integer) — Person who created the integration.
    - data_source_id (integer) — Integration ID.
    - description (string) — Integration description.
    - exclusive_data_source_id (integer) — Exclusive integration ID associated with this integration.
    - integration_id (integer) — Integration ID, alias of data_source_id.
    - integration_key (string) — Push key used by alert sources to send to this integration.
    - last_time (integer) — Unix timestamp in seconds of the most recent activity on the integration.
    - name (string) — Integration name.
    - no_editable (boolean) — Whether the integration is read-only.
    - plugin_id (integer) — Plugin ID backing this integration.
    - plugin_type (string) — Type identifier of the integration plugin.
    - plugin_type_name (string) — Localized display name of the integration plugin type.
    - ref_id (string) — External reference ID of the integration.
    - settings (object) — Plugin-specific configuration of the integration.
    - status (string) — Current status of the integration.
    - team_id (integer) — Team that owns this integration.
    - updated_at (integer) — Unix timestamp in seconds when the integration was last updated.
    - updated_by (integer) — Person who last updated the integration.
`,
		Example: `  flashduty datasource im-war-room-enabled-list --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					return nil
				})
				if err != nil {
					return err
				}
				_ = body
				out, _, err := ctx.Client.ImIntegrations.List(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedImIntegrations(root *cobra.Command) {
	gDatasource := genGroup(root, "datasource", "On-call API")
	genAddLeaf(gDatasource, genImIntegrationsListCmd())
}
