// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genDiagnosticsQueryDataCmd() *cobra.Command {
	var dataJSON string
	var fAccountID int64
	var fDelaySeconds int64
	var fDsName string
	var fDsType string
	var fExpr string
	cmd := &cobra.Command{
		Use:   "query-data",
		Short: "Query structured data",
		Long: `Query structured data.

Run a synchronous ad-hoc query against a configured data source and return a stable 'query_result.v1' result whose natural shape is frames, records, or samples. This public API requires monit-edge v0.65.0 or later.

API: POST /monit/query/data (monit-read-query-data)

Request fields:
  --account-id int — Optional consistency check. Must equal the authenticated account when supplied; mismatched values are rejected. Business execution always uses the authenticated account.
  --delay-seconds int — Look-back offset in seconds applied to point-in-time queries (Prometheus, Loki stats, VictoriaLogs stats). Ignored for raw / detail queries.
  --ds-name string (required) — Data source name; must match a configured data source under the tenant.
  --ds-type string (required) — Data source type; must match a configured data source under the tenant. Examples: 'prometheus', 'loki', 'victorialogs', 'sls', 'elasticsearch', 'mysql', 'postgres', 'oracle', 'clickhouse'.
  --expr string (required) — Query expression. Syntax depends on 'ds_type' and is interpreted by the corresponding monit-edge client (PromQL for Prometheus, LogQL for Loki, SQL for SQL sources, etc.).
  args (object, via --data) — Polymorphic key/value extension parameters forwarded verbatim to monit-edge. All values must be strings, and keys are always namespaced by source (e.g. 'sls.project', 'loki.type'). Validation depends on 'ds_type': SLS requires 'sls.project' + 'sls.logstore'. Elasticsearch accepts 'es.type' of 'sql', or omitted — any other value is rejected. Loki and VictoriaLogs accept '<source>.type' of 'stats', 'raw', or omitted; 'raw' additionally requires a time range, either '<source>.start' + '<source>.end' or '<source>.timespan.value' + '<source>.timespan.unit' (unit one of 's', 'm', 'h', 'd'). Prometheus and the remaining SQL sources ignore 'args' entirely.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - format (string) (required) — Public result-contract version. It is independent of the internal monit-edge query protocol version. Fixed at 'query_result.v1', which defines the structure of the 'result' field. [query_result.v1]
  - result (object) (required) — Exactly one natural result shape, selected by 'kind'.
    - frames (array<object>) — Typed table or time-series frames. A response can contain more than one frame.
      - fields (array<object>) (required) — Columns of the frame; all fields share the same 'values' length and row i is composed of each field's 'values[i]'.
        - labels (object) — Series labels. Present on the float field of a time-series frame.
        - name (string) (required) — Column name; on a time-series float field, series are distinguished by 'labels' and 'name' is usually the metric name.
        - type (string) (required) — Value type governing 'values' encoding: 'string' = strings or null, 'float' = numbers or 'NaN'/'±Inf' strings or null, 'time' = RFC 3339 Nano strings or null. [string, float, time]
        - values (array<any>) (required) — All values of this column in row order; length matches the other fields in the frame.
      - kind (string) (required) — Frame type: 'table' for a generic table, 'time_series' for a series (exactly one time field and one float field). [table, time_series]
    - kind (string) (required) — Result-kind discriminator, always 'frames', indicating the 'frames' payload of typed table/time-series frames. [frames, records, samples]
    - records (array<any>) — Schema-flexible records. Records may have different fields, contain nested JSON, or be null. Integers outside JavaScript's safe range are encoded as decimal strings.
    - samples (array<object>) — Instant samples with their complete label sets.
      - labels (object) (required) — The sample's full label set; may be an empty object but is always present.
      - value (any) (required) — Finite numeric value or a JSON-safe representation of a non-finite float.
`,
		Example: `  flashduty monit query-data --data '{"args":{},"delay_seconds":0,"ds_name":"prod-prom","ds_type":"prometheus","expr":"sum by (job) (rate(http_requests_total[5m]))"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("account-id") {
						body["account_id"] = fAccountID
					}
					if cmd.Flags().Changed("delay-seconds") {
						body["delay_seconds"] = fDelaySeconds
					}
					if cmd.Flags().Changed("ds-name") {
						body["ds_name"] = fDsName
					}
					if cmd.Flags().Changed("ds-type") {
						body["ds_type"] = fDsType
					}
					if cmd.Flags().Changed("expr") {
						body["expr"] = fExpr
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.QueryDataRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Diagnostics.QueryData(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fAccountID, "account-id", 0, "Optional consistency check. Must equal the authenticated account when supplied; mismatched values are rejected. Business execution always uses the authenticated account.")
	cmd.Flags().Int64Var(&fDelaySeconds, "delay-seconds", 0, "Look-back offset in seconds applied to point-in-time queries (Prometheus, Loki stats, VictoriaLogs stats). Ignored for raw / detail queries.")
	cmd.Flags().StringVar(&fDsName, "ds-name", "", "Data source name; must match a configured data source under the tenant. (required)")
	cmd.Flags().StringVar(&fDsType, "ds-type", "", "Data source type; must match a configured data source under the tenant. Examples: 'prometheus', 'loki', 'victorialogs', 'sls', 'elasticsearch', 'mysql', 'postgres', 'oracle', 'clickhouse'. (required)")
	cmd.Flags().StringVar(&fExpr, "expr", "", "Query expression. Syntax depends on 'ds_type' and is interpreted by the corresponding monit-edge client (PromQL for Prometheus, LogQL for Loki, SQL for SQL sources, etc.). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedDiagnostics(root *cobra.Command) {
	gMonit := genGroup(root, "monit", "Monitors API")
	genAddLeaf(gMonit, genDiagnosticsQueryDataCmd())
}
