// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genMembersMemberDeleteCmd() *cobra.Command {
	var dataJSON string
	var fCountryCode string
	var fEmail string
	var fIsForce bool
	var fMemberID int64
	var fMemberName string
	var fPhone string
	var fRefID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete member",
		Long: `Delete member.

Remove a member from the organization by ID, email, phone, or name.

API: POST /member/delete (memberDelete)

Request fields:
  --country-code string — Phone country code, used with phone
  --email string — Email address
  --is-force bool — Force delete. Defaults to false, which checks for references from escalation rules, schedules, etc. Set to true to skip the reference check and delete immediately
  --member-id int — Member ID
  --member-name string — Member name
  --phone string — Phone number
  --ref-id string — External reference ID
`,
		Example: `  flashduty member delete --data '{"member_id":5068740052131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("country-code") {
						body["country_code"] = fCountryCode
					}
					if cmd.Flags().Changed("email") {
						body["email"] = fEmail
					}
					if cmd.Flags().Changed("is-force") {
						body["is_force"] = fIsForce
					}
					if cmd.Flags().Changed("member-id") {
						body["member_id"] = fMemberID
					}
					if cmd.Flags().Changed("member-name") {
						body["member_name"] = fMemberName
					}
					if cmd.Flags().Changed("phone") {
						body["phone"] = fPhone
					}
					if cmd.Flags().Changed("ref-id") {
						body["ref_id"] = fRefID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MemberDeleteRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Members.MemberDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /member/delete")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fCountryCode, "country-code", "", "Phone country code, used with phone")
	cmd.Flags().StringVar(&fEmail, "email", "", "Email address")
	cmd.Flags().BoolVar(&fIsForce, "is-force", false, "Force delete. Defaults to false, which checks for references from escalation rules, schedules, etc. Set to true to skip the reference check and delete immediately")
	cmd.Flags().Int64Var(&fMemberID, "member-id", 0, "Member ID")
	cmd.Flags().StringVar(&fMemberName, "member-name", "", "Member name")
	cmd.Flags().StringVar(&fPhone, "phone", "", "Phone number")
	cmd.Flags().StringVar(&fRefID, "ref-id", "", "External reference ID")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMembersMemberGrantRoleCmd() *cobra.Command {
	var dataJSON string
	var fMemberID int64
	var fRoleIDs []int
	cmd := &cobra.Command{
		Use:   "role-grant",
		Short: "Grant role to member",
		Long: `Grant role to member.

Add a role assignment to a member.

API: POST /member/role/grant (memberGrantRole)

Request fields:
  --member-id int (required) — Member ID
  --role-ids []int (required) — Role IDs to grant; appended to the member's current roles (duplicates are deduplicated).
`,
		Example: `  flashduty member role-grant --data '{"member_id":5068740052131,"role_ids":[6]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("member-id") {
						body["member_id"] = fMemberID
					}
					if cmd.Flags().Changed("role-ids") {
						body["role_ids"] = fRoleIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MemberRoleGrantRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Members.MemberGrantRole(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /member/role/grant")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fMemberID, "member-id", 0, "Member ID (required)")
	cmd.Flags().IntSliceVar(&fRoleIDs, "role-ids", nil, "Role IDs to grant; appended to the member's current roles (duplicates are deduplicated). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMembersMemberInfoCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "info",
		Short: "Get current member info",
		Long: `Get current member info.

Return the current session member's full profile.

API: POST /member/info (memberInfo)

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_avatar (string) — Account avatar URL
  - account_email (string) — Account email
  - account_id (integer) — Account ID
  - account_locale (string) — Account-level locale preference (e.g. zh-CN or en-US)
  - account_name (string) — Account name
  - account_role_ids (array<integer>) — Assigned role IDs
  - account_time_zone (string) — Account-level time zone (e.g. Asia/Shanghai)
  - avatar (string) — Member avatar URL
  - country_code (string) — Phone country code
  - domain (string) — Account domain
  - email (string) — Email address
  - email_verified (boolean) — Whether email is verified
  - is_external (boolean) — Whether provisioned via SSO
  - locale (string) — Locale preference
  - member_id (integer) — Member ID
  - member_name (string) — Member display name
  - phone (string) — Masked phone number
  - phone_verified (boolean) — Whether phone is verified
  - status (string) — Member status. 'enabled' — active member; 'pending' — invited but not yet accepted; 'deleted' — removed from the organization. [enabled, pending, deleted]
  - time_zone (string) — Time zone
`,
		Example: `  flashduty member info --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				out, _, err := ctx.Client.Members.MemberInfo(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMembersMemberInviteCmd() *cobra.Command {
	var dataJSON string
	var fFrom string
	cmd := &cobra.Command{
		Use:   "invite",
		Short: "Invite members",
		Long: `Invite members.

Batch invite new members to the organization by email or phone.

API: POST /member/invite (memberInvite)

Request fields:
  --from string — Invite source context
  members (array<object>, via --data) (required) — Members to invite (max 20)
    - country_code (string) — Country code
    - email (string) — Email address
    - locale (string) — Locale [zh-CN, en-US]
    - member_name (string) — Display name (2-39 chars)
    - phone (string) — Phone number
    - ref_id (string) — External reference ID
    - role_ids (array<integer>) — Role IDs to assign
    - time_zone (string) — Time zone

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>) — Newly created members
    - member_id (integer) — Member ID
    - member_name (string) — Member display name
`,
		Example: `  flashduty member invite --data '{"members":[{"email":"charlie@example.com","locale":"en-US","member_name":"Charlie","role_ids":[6],"time_zone":"Asia/Shanghai"}]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("from") {
						body["from"] = fFrom
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MemberInviteRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Members.MemberInvite(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fFrom, "from", "", "Invite source context")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMembersMemberListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fAsc bool
	var fOrderby string
	var fQuery string
	var fRoleID int64
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List members",
		Long: `List members.

Return a paginated list of organization members.

API: POST /member/list (memberList)

Request fields:
  --page int — Page number (min 1)
  --limit int — Page size (1-100)
  --search-after-ctx string
  --asc bool — Ascending order
  --orderby string — Sort field [created_at, updated_at]
  --query string — Search keyword
  --role-id int — Filter by role ID

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>) — Member items
    - account_id (integer) (required) — Account ID
    - account_role_ids (array<integer>) (required) — Role IDs
    - avatar (string) (required) — Avatar URL
    - country_code (string) (required) — Phone country code
    - created_at (integer) (required) — Creation timestamp (Unix seconds)
    - email (string) (required) — Email address
    - email_verified (boolean) (required) — Email verified
    - is_external (boolean) (required) — Provisioned via SSO
    - locale (string) — Locale
    - member_id (integer) (required) — Member ID
    - member_name (string) (required) — Display name
    - phone (string) (required) — Masked phone number
    - phone_verified (boolean) (required) — Phone verified
    - ref_id (string) (required) — External reference ID
    - status (string) (required) — Member status. 'enabled' — active member; 'pending' — invited but not yet accepted; 'deleted' — removed from the organization. [enabled, pending, deleted]
    - time_zone (string) — Time zone
    - updated_at (integer) (required) — Update timestamp (Unix seconds)
  - limit (integer) — Page size
  - p (integer) — Current page
  - total (integer) — Total count
`,
		Example: `  flashduty member list --data '{"limit":5,"p":1}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("page") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("asc") {
						body["asc"] = fAsc
					}
					if cmd.Flags().Changed("orderby") {
						body["orderby"] = fOrderby
					}
					if cmd.Flags().Changed("query") {
						body["query"] = fQuery
					}
					if cmd.Flags().Changed("role-id") {
						body["role_id"] = fRoleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MemberListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Members.MemberList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "page", 0, "Page number (min 1)")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size (1-100)")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().BoolVar(&fAsc, "asc", false, "Ascending order")
	cmd.Flags().StringVar(&fOrderby, "orderby", "", "Sort field [created_at, updated_at]")
	cmd.Flags().StringVar(&fQuery, "query", "", "Search keyword")
	cmd.Flags().Int64Var(&fRoleID, "role-id", 0, "Filter by role ID")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMembersMemberResetInfoCmd() *cobra.Command {
	var dataJSON string
	var fAvatar string
	var fCountryCode string
	var fEmail string
	var fLocale string
	var fMemberID int64
	var fMemberName string
	var fPhone string
	var fTimeZone string
	cmd := &cobra.Command{
		Use:   "info-reset",
		Short: "Reset member info",
		Long: `Reset member info.

Batch-update multiple profile fields of the current member.

API: POST /member/info/reset (memberResetInfo)

Request fields:
  --avatar string — Avatar URL
  --country-code string — Country code
  --email string — Email address
  --locale string — Locale [zh-CN, en-US]
  --member-id int (required) — Member ID of the member to update
  --member-name string — Display name (2-39 chars)
  --phone string — Phone number
  --time-zone string — Time zone
`,
		Example: `  flashduty member info-reset --data '{"locale":"zh-CN","member_id":2476444212131,"member_name":"Alice","time_zone":"Asia/Shanghai"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("avatar") {
						body["avatar"] = fAvatar
					}
					if cmd.Flags().Changed("country-code") {
						body["country_code"] = fCountryCode
					}
					if cmd.Flags().Changed("email") {
						body["email"] = fEmail
					}
					if cmd.Flags().Changed("locale") {
						body["locale"] = fLocale
					}
					if cmd.Flags().Changed("member-id") {
						body["member_id"] = fMemberID
					}
					if cmd.Flags().Changed("member-name") {
						body["member_name"] = fMemberName
					}
					if cmd.Flags().Changed("phone") {
						body["phone"] = fPhone
					}
					if cmd.Flags().Changed("time-zone") {
						body["time_zone"] = fTimeZone
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MemberResetInfoRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Members.MemberResetInfo(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /member/info/reset")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fAvatar, "avatar", "", "Avatar URL")
	cmd.Flags().StringVar(&fCountryCode, "country-code", "", "Country code")
	cmd.Flags().StringVar(&fEmail, "email", "", "Email address")
	cmd.Flags().StringVar(&fLocale, "locale", "", "Locale [zh-CN, en-US]")
	cmd.Flags().Int64Var(&fMemberID, "member-id", 0, "Member ID of the member to update (required)")
	cmd.Flags().StringVar(&fMemberName, "member-name", "", "Display name (2-39 chars)")
	cmd.Flags().StringVar(&fPhone, "phone", "", "Phone number")
	cmd.Flags().StringVar(&fTimeZone, "time-zone", "", "Time zone")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMembersMemberRevokeRoleCmd() *cobra.Command {
	var dataJSON string
	var fMemberID int64
	var fRoleIDs []int
	cmd := &cobra.Command{
		Use:   "role-revoke",
		Short: "Revoke role from member",
		Long: `Revoke role from member.

Remove a role assignment from a member.

API: POST /member/role/revoke (memberRevokeRole)

Request fields:
  --member-id int (required) — Member ID
  --role-ids []int (required) — Role IDs to remove from the member.
`,
		Example: `  flashduty member role-revoke --data '{"member_id":5068740052131,"role_ids":[6]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("member-id") {
						body["member_id"] = fMemberID
					}
					if cmd.Flags().Changed("role-ids") {
						body["role_ids"] = fRoleIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MemberRoleRevokeRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Members.MemberRevokeRole(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /member/role/revoke")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fMemberID, "member-id", 0, "Member ID (required)")
	cmd.Flags().IntSliceVar(&fRoleIDs, "role-ids", nil, "Role IDs to remove from the member. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMembersMemberUpdateRoleCmd() *cobra.Command {
	var dataJSON string
	var fMemberID int64
	var fRoleIDs []int
	cmd := &cobra.Command{
		Use:   "role-update",
		Short: "Update member roles",
		Long: `Update member roles.

Replace all role assignments for a member at once.

API: POST /member/role/update (memberUpdateRole)

Request fields:
  --member-id int (required) — Member ID
  --role-ids []int (required) — New set of role IDs
`,
		Example: `  flashduty member role-update --data '{"member_id":5068740052131,"role_ids":[2,6]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("member-id") {
						body["member_id"] = fMemberID
					}
					if cmd.Flags().Changed("role-ids") {
						body["role_ids"] = fRoleIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MemberRoleUpdateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Members.MemberUpdateRole(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /member/role/update")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fMemberID, "member-id", 0, "Member ID (required)")
	cmd.Flags().IntSliceVar(&fRoleIDs, "role-ids", nil, "New set of role IDs (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMembersPersonInfosCmd() *cobra.Command {
	var dataJSON string
	var fPersonIDs []int
	cmd := &cobra.Command{
		Use:   "infos",
		Short: "Batch get persons",
		Long: `Batch get persons.

Return profile information for a batch of person IDs (members or accounts).

API: POST /person/infos (personInfos)

Request fields:
  --person-ids []int (required) — List of person IDs

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>) — Person profiles
    - account_id (integer) (required) — Account ID
    - as (string) — Login role (account/member)
    - avatar (string) — Avatar URL
    - email (string) — Email address
    - email_verified (boolean) (required) — Email verified
    - locale (string) — Locale
    - person_id (integer) (required) — Person ID
    - person_name (string) — Display name
    - phone (string) — Phone number
    - phone_verified (boolean) (required) — Phone verified
    - status (string) — Person status. 'enabled' — active; 'pending' — invited but not yet accepted; 'deleted' — removed. [enabled, pending, deleted]
    - time_zone (string) — Time zone
`,
		Example: `  flashduty person infos --data '{"person_ids":[2476444212131,3790925372131]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("person-ids") {
						body["person_ids"] = fPersonIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.PersonInfosRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Members.PersonInfos(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().IntSliceVar(&fPersonIDs, "person-ids", nil, "List of person IDs (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedMembers(root *cobra.Command) {
	gMember := genGroup(root, "member", "Platform/Members API")
	genAddLeaf(gMember, genMembersMemberDeleteCmd())
	genAddLeaf(gMember, genMembersMemberGrantRoleCmd())
	genAddLeaf(gMember, genMembersMemberInfoCmd())
	genAddLeaf(gMember, genMembersMemberInviteCmd())
	genAddLeaf(gMember, genMembersMemberListCmd())
	genAddLeaf(gMember, genMembersMemberResetInfoCmd())
	genAddLeaf(gMember, genMembersMemberRevokeRoleCmd())
	genAddLeaf(gMember, genMembersMemberUpdateRoleCmd())
	gPerson := genGroup(root, "person", "Platform/Members API")
	genAddLeaf(gPerson, genMembersPersonInfosCmd())
}
