// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genArtifactsReadGetCmd() *cobra.Command {
	var dataJSON string
	var fArtifactID string
	cmd := &cobra.Command{
		Use:   "artifact-gallery-get <artifact-id>",
		Short: "Get artifact detail",
		Long: `Get artifact detail.

Get a single published artifact by ID.

API: POST /safari/artifact/gallery/get (artifact-read-get)

Request fields:
  --artifact-id string (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - artifact_id (string) (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
  - can_edit (boolean) (required) — Whether the caller may manage this artifact (rename, transfer, delete, share): the creator, any member of the owning team, or a manager of the source session.
  - content_type (string) (required) — MIME type of the file.
  - created_at (string) (required) — Unix timestamp in milliseconds when the artifact was published. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - creator_name (string) (required) — Creator's display name.
  - file_id (string) (required) — Presented-file ID ('pf_' prefix) currently holding the artifact's bytes. Changes on every republish.
  - is_mine (boolean) (required) — Whether the caller is the creator.
  - name (string) (required) — Underlying file name including extension.
  - person_id (integer) (required) — Person (member) ID of the creator.
  - public_url (string) — Anonymous public link — a console '/share/artifact/<artifact_id>' page served entirely from CDN. Present only while shared; anyone with the link can view it, no login required.
  - session_id (string) (required) — Source session ID ('sess_' prefix) that produced the file.
  - session_title (string) — Source session's title. Omitted when the session has been deleted.
  - share_enabled (boolean) — Whether anonymous public sharing is on. Omitted when false.
  - share_file_id (string) — Presented-file ID the public snapshot was materialized from. When 'share_enabled' is true and 'file_id' differs from 'share_file_id', the public snapshot is stale — call '/safari/artifact/gallery/share/sync' to refresh it.
  - shared_at (string) — Unix timestamp in milliseconds of the last share enable or snapshot sync. Present only while shared. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - shared_by (integer) — Person ID of the member who enabled sharing. Present only while shared.
  - size (integer) (required) — File size in bytes.
  - team_id (integer) (required) — Owning team ID. '0' means a personal artifact (creator-only management); a positive value means team-owned.
  - team_name (string) — Owning team's display name. Omitted for personal artifacts.
  - title (string) (required) — Display title in the gallery.
  - updated_at (string) (required) — Unix timestamp in milliseconds when the artifact was last updated (rename, transfer, or republish). CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
`,
		Args:    requireBodyFieldOrExactArg("artifact_id", "artifact-id"),
		Example: `  flashduty safari artifact-gallery-get --data '{"artifact_id":"art_VnfrWic8UbB9q3EfYR4Gmg"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "artifact_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("artifact-id") {
						body["artifact_id"] = fArtifactID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.ReadGet(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fArtifactID, "artifact-id", "", "Artifact ID ('art_' prefix). Also the key of the public-share link. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsReadGetFileStateCmd() *cobra.Command {
	var dataJSON string
	var fFileIDs []string
	cmd := &cobra.Command{
		Use:   "artifact-gallery-file-state <file-id> [<id2>...]",
		Short: "Get file publish state",
		Long: `Get file publish state.

Check which presented files already have a live published artifact.

API: POST /safari/artifact/gallery/file-state (artifact-read-get-file-state)

Request fields:
  --file-ids []string (required) — Presented-file IDs ('pf_' prefix) to probe. At most 50 per call; duplicates and empty strings are ignored.

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>) (required) — One entry per requested file that has a live published artifact; files without one are omitted.
    - artifact_id (string) (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
    - file_id (string) (required) — Echoes the requested presented-file ID.
    - gallery_path (string) (required) — Console-relative path of the artifact page: '/ai-sre/artifacts/<artifact_id>'.
    - title (string) (required) — Gallery display title of the published artifact.
`,
		Args:    requireBodyFieldOrArgs("file_ids", "file-ids"),
		Example: `  flashduty safari artifact-gallery-file-state --data '{"file_ids":["pf_SdhEA5fbZJGnHzwrNJMMSB","pf_9kLm2nQpRsTuVwXyZaBcDe"]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "file_ids", "slice"); err != nil {
						return err
					}
					if cmd.Flags().Changed("file-ids") {
						body["file_ids"] = fFileIDs
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactFileStateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.ReadGetFileState(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringSliceVar(&fFileIDs, "file-ids", nil, "Presented-file IDs ('pf_' prefix) to probe. At most 50 per call; duplicates and empty strings are ignored. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsReadListCmd() *cobra.Command {
	var dataJSON string
	var fAsc bool
	var fLimit int64
	var fOrderby string
	var fPage int64
	var fQuery string
	var fScope string
	var fTeamIDs []int
	cmd := &cobra.Command{
		Use:   "artifact-gallery-list",
		Short: "List artifacts",
		Long: `List artifacts.

List published artifacts visible to the caller, with pagination and title search.

API: POST /safari/artifact/gallery/list (artifact-read-list)

Request fields:
  --asc bool — Sort ascending when true, descending when false. Applies only when 'orderby' is set.
  --limit int — Page size. Defaults to 20; capped at 100. (max 100)
  --orderby string — Sort field: 'created_at' or 'updated_at'. Empty means 'updated_at' descending. [created_at, updated_at]
  --page int — Page number, 1-based. (min 1)
  --query string — Case-insensitive substring match on the artifact title.
  --scope string — Visibility scope. 'all' (default) lists the caller's own personal artifacts plus artifacts of every team the caller belongs to; 'personal' lists only the caller's own; 'team' lists only team-owned artifacts of the caller's teams. [all, personal, team]
  --team-ids []int — Restrict to artifacts owned by these team IDs, intersected with the caller's visibility — teams the caller does not belong to silently return nothing.

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>) — Artifacts on this page.
    - artifact_id (string) (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
    - can_edit (boolean) (required) — Whether the caller may manage this artifact (rename, transfer, delete, share): the creator, any member of the owning team, or a manager of the source session.
    - content_type (string) (required) — MIME type of the file.
    - created_at (string) (required) — Unix timestamp in milliseconds when the artifact was published. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
    - creator_name (string) (required) — Creator's display name.
    - file_id (string) (required) — Presented-file ID ('pf_' prefix) currently holding the artifact's bytes. Changes on every republish.
    - is_mine (boolean) (required) — Whether the caller is the creator.
    - name (string) (required) — Underlying file name including extension.
    - person_id (integer) (required) — Person (member) ID of the creator.
    - public_url (string) — Anonymous public link — a console '/share/artifact/<artifact_id>' page served entirely from CDN. Present only while shared; anyone with the link can view it, no login required.
    - session_id (string) (required) — Source session ID ('sess_' prefix) that produced the file.
    - session_title (string) — Source session's title. Omitted when the session has been deleted.
    - share_enabled (boolean) — Whether anonymous public sharing is on. Omitted when false.
    - share_file_id (string) — Presented-file ID the public snapshot was materialized from. When 'share_enabled' is true and 'file_id' differs from 'share_file_id', the public snapshot is stale — call '/safari/artifact/gallery/share/sync' to refresh it.
    - shared_at (string) — Unix timestamp in milliseconds of the last share enable or snapshot sync. Present only while shared. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
    - shared_by (integer) — Person ID of the member who enabled sharing. Present only while shared.
    - size (integer) (required) — File size in bytes.
    - team_id (integer) (required) — Owning team ID. '0' means a personal artifact (creator-only management); a positive value means team-owned.
    - team_name (string) — Owning team's display name. Omitted for personal artifacts.
    - title (string) (required) — Display title in the gallery.
    - updated_at (string) (required) — Unix timestamp in milliseconds when the artifact was last updated (rename, transfer, or republish). CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - total (integer) — Total number of artifacts matching the filter across all pages.
`,
		Example: `  flashduty safari artifact-gallery-list --data '{"limit":20,"page":1,"scope":"all"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("asc") {
						body["asc"] = fAsc
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("orderby") {
						body["orderby"] = fOrderby
					}
					if cmd.Flags().Changed("page") {
						body["page"] = fPage
					}
					if cmd.Flags().Changed("query") {
						body["query"] = fQuery
					}
					if cmd.Flags().Changed("scope") {
						body["scope"] = fScope
					}
					if cmd.Flags().Changed("team-ids") {
						body["team_ids"] = fTeamIDs
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.ReadList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().BoolVar(&fAsc, "asc", false, "Sort ascending when true, descending when false. Applies only when 'orderby' is set.")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size. Defaults to 20; capped at 100. (max 100)")
	cmd.Flags().StringVar(&fOrderby, "orderby", "", "Sort field: 'created_at' or 'updated_at'. Empty means 'updated_at' descending. [created_at, updated_at]")
	cmd.Flags().Int64Var(&fPage, "page", 0, "Page number, 1-based. (min 1)")
	cmd.Flags().StringVar(&fQuery, "query", "", "Case-insensitive substring match on the artifact title.")
	cmd.Flags().StringVar(&fScope, "scope", "", "Visibility scope. 'all' (default) lists the caller's own personal artifacts plus artifacts of every team the caller belongs to; 'personal' lists only the caller's own; 'team' lists only team-owned artifacts of the caller's teams. [all, personal, team]")
	cmd.Flags().IntSliceVar(&fTeamIDs, "team-ids", nil, "Restrict to artifacts owned by these team IDs, intersected with the caller's visibility — teams the caller does not belong to silently return nothing.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsReadSignCmd() *cobra.Command {
	var dataJSON string
	var fFileID string
	var fShareToken string
	cmd := &cobra.Command{
		Use:   "artifact-sign <file-id>",
		Short: "Create signed file URLs",
		Long: `Create signed file URLs.

Create short-lived signed URLs to download or preview a presented file.

API: POST /safari/artifact/sign (artifact-read-sign)

Request fields:
  --file-id string (required) — Presented-file ID ('pf_' prefix) to sign.
  --share-token string — Optional session share-link token. Needed only when the caller reaches the file through a shared session link rather than account membership.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - content_type (string) (required) — MIME type of the file.
  - download_url (string) (required) — Relative URL ('/safari/artifact/stream?...') that serves the file as an attachment. Prepend the API base 'https://api.flashcat.cloud' before use; expires with 'expires_in'.
  - expires_in (integer) (required) — Validity of both URLs in seconds (300).
  - name (string) (required) — File name including extension.
  - preview_url (string) (required) — Same as 'download_url' but served inline for browser preview.
  - size (integer) (required) — File size in bytes.
`,
		Args:    requireBodyFieldOrExactArg("file_id", "file-id"),
		Example: `  flashduty safari artifact-sign --data '{"file_id":"pf_SdhEA5fbZJGnHzwrNJMMSB"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "file_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("file-id") {
						body["file_id"] = fFileID
					}
					if cmd.Flags().Changed("share-token") {
						body["share_token"] = fShareToken
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactSignRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.ReadSign(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fFileID, "file-id", "", "Presented-file ID ('pf_' prefix) to sign. (required)")
	cmd.Flags().StringVar(&fShareToken, "share-token", "", "Optional session share-link token. Needed only when the caller reaches the file through a shared session link rather than account membership.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsReadStreamCmd() *cobra.Command {
	var dataJSON string
	var fT string
	var fMode string
	cmd := &cobra.Command{
		Use:   "artifact-stream",
		Short: "Download or preview a file",
		Long: `Download or preview a file.

Download or preview a file's bytes using a signed token.

API: GET /safari/artifact/stream (artifact-read-stream)

Request fields:
  --t string (required) — Signed token issued by 'POST /safari/artifact/sign'. Bound to the calling account and person; valid for 5 minutes.
  --mode string — 'download' (default) serves the file as an attachment; 'preview' serves it inline for browser display. Any other value falls back to 'download'. [download, preview]
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("t") {
						body["t"] = fT
					}
					if cmd.Flags().Changed("mode") {
						body["mode"] = fMode
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactsReadStreamRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Artifacts.ReadStream(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: GET /safari/artifact/stream")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fT, "t", "", "Signed token issued by 'POST /safari/artifact/sign'. Bound to the calling account and person; valid for 5 minutes. (required)")
	cmd.Flags().StringVar(&fMode, "mode", "", "'download' (default) serves the file as an attachment; 'preview' serves it inline for browser display. Any other value falls back to 'download'. [download, preview]")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsWriteDeleteCmd() *cobra.Command {
	var dataJSON string
	var fArtifactID string
	cmd := &cobra.Command{
		Use:   "artifact-gallery-delete <artifact-id>",
		Short: "Remove artifact from gallery",
		Long: `Remove artifact from gallery.

Detach an artifact from the gallery; the source file stays with its session.

API: POST /safari/artifact/gallery/delete (artifact-write-delete)

Request fields:
  --artifact-id string (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
`,
		Args:    requireBodyFieldOrExactArg("artifact_id", "artifact-id"),
		Example: `  flashduty safari artifact-gallery-delete --data '{"artifact_id":"art_CWQzDU2PXSRJvKDhQbuMKu"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "artifact_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("artifact-id") {
						body["artifact_id"] = fArtifactID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.WriteDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fArtifactID, "artifact-id", "", "Artifact ID ('art_' prefix). Also the key of the public-share link. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsWritePublishCmd() *cobra.Command {
	var dataJSON string
	var fFileID string
	var fTitle string
	cmd := &cobra.Command{
		Use:   "artifact-gallery-publish-from-file <file-id>",
		Short: "Publish file as artifact",
		Long: `Publish file as artifact.

Publish a session-produced file to the artifact gallery.

API: POST /safari/artifact/gallery/publish-from-file (artifact-write-publish)

Request fields:
  --file-id string (required) — Presented-file ID ('pf_' prefix) of a file produced in a session, as shown on the file card in chat.
  --title string (required) — Gallery display title. Trimmed; must be non-empty.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - artifact_id (string) (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
  - gallery_path (string) (required) — Console-relative path of the artifact page: '/ai-sre/artifacts/<artifact_id>'.
  - title (string) (required) — Gallery display title.
`,
		Args:    requireBodyFieldOrExactArg("file_id", "file-id"),
		Example: `  flashduty safari artifact-gallery-publish-from-file --data '{"file_id":"pf_SdhEA5fbZJGnHzwrNJMMSB","title":"SK 海力士 2026 Q2 财报深度分析"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "file_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("file-id") {
						body["file_id"] = fFileID
					}
					if cmd.Flags().Changed("title") {
						body["title"] = fTitle
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactPublishFromFileRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.WritePublish(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fFileID, "file-id", "", "Presented-file ID ('pf_' prefix) of a file produced in a session, as shown on the file card in chat. (required)")
	cmd.Flags().StringVar(&fTitle, "title", "", "Gallery display title. Trimmed; must be non-empty. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsWriteShareEnableCmd() *cobra.Command {
	var dataJSON string
	var fArtifactID string
	cmd := &cobra.Command{
		Use:   "artifact-gallery-share-enable <artifact-id>",
		Short: "Enable public sharing",
		Long: `Enable public sharing.

Turn on anonymous public sharing for an artifact and return its public link.

API: POST /safari/artifact/gallery/share/enable (artifact-write-share-enable)

Request fields:
  --artifact-id string (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - artifact_id (string) (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
  - public_url (string) (required) — Anonymous public link served entirely from CDN. Anyone with the link can view the content, no login required.
  - share_enabled (boolean) (required) — Always 'true' in this response.
  - shared_at (string) (required) — Unix timestamp in milliseconds of the last share enable or snapshot sync. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - shared_by (integer) (required) — Person ID of the member who enabled sharing.
`,
		Args:    requireBodyFieldOrExactArg("artifact_id", "artifact-id"),
		Example: `  flashduty safari artifact-gallery-share-enable --data '{"artifact_id":"art_VnfrWic8UbB9q3EfYR4Gmg"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "artifact_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("artifact-id") {
						body["artifact_id"] = fArtifactID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.WriteShareEnable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fArtifactID, "artifact-id", "", "Artifact ID ('art_' prefix). Also the key of the public-share link. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsWriteShareRevokeCmd() *cobra.Command {
	var dataJSON string
	var fArtifactID string
	cmd := &cobra.Command{
		Use:   "artifact-gallery-share-revoke <artifact-id>",
		Short: "Revoke public sharing",
		Long: `Revoke public sharing.

Turn off public sharing; the link stops resolving immediately.

API: POST /safari/artifact/gallery/share/revoke (artifact-write-share-revoke)

Request fields:
  --artifact-id string (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
`,
		Args:    requireBodyFieldOrExactArg("artifact_id", "artifact-id"),
		Example: `  flashduty safari artifact-gallery-share-revoke --data '{"artifact_id":"art_VnfrWic8UbB9q3EfYR4Gmg"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "artifact_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("artifact-id") {
						body["artifact_id"] = fArtifactID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.WriteShareRevoke(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fArtifactID, "artifact-id", "", "Artifact ID ('art_' prefix). Also the key of the public-share link. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsWriteShareSyncCmd() *cobra.Command {
	var dataJSON string
	var fArtifactID string
	cmd := &cobra.Command{
		Use:   "artifact-gallery-share-sync <artifact-id>",
		Short: "Update shared snapshot",
		Long: `Update shared snapshot.

Refresh the public snapshot of a shared artifact with its latest content.

API: POST /safari/artifact/gallery/share/sync (artifact-write-share-sync)

Request fields:
  --artifact-id string (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - artifact_id (string) (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
  - public_url (string) (required) — Anonymous public link served entirely from CDN. Anyone with the link can view the content, no login required.
  - share_enabled (boolean) (required) — Always 'true' in this response.
  - shared_at (string) (required) — Unix timestamp in milliseconds of the last share enable or snapshot sync. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - shared_by (integer) (required) — Person ID of the member who enabled sharing.
`,
		Args:    requireBodyFieldOrExactArg("artifact_id", "artifact-id"),
		Example: `  flashduty safari artifact-gallery-share-sync --data '{"artifact_id":"art_VnfrWic8UbB9q3EfYR4Gmg"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "artifact_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("artifact-id") {
						body["artifact_id"] = fArtifactID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.WriteShareSync(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fArtifactID, "artifact-id", "", "Artifact ID ('art_' prefix). Also the key of the public-share link. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genArtifactsWriteUpdateCmd() *cobra.Command {
	var dataJSON string
	var fArtifactID string
	var fTeamID int64
	var fTitle string
	cmd := &cobra.Command{
		Use:   "artifact-gallery-update <artifact-id>",
		Short: "Update artifact",
		Long: `Update artifact.

Rename an artifact or transfer it between personal and team scope.

API: POST /safari/artifact/gallery/update (artifact-write-update)

Request fields:
  --artifact-id string (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
  --team-id int — Transfer target scope. '0' moves the artifact to personal scope (only the creator can manage it); a positive value moves it to a team the caller must belong to. Omit to leave unchanged.
  --title string — New title. Trimmed; must be non-empty when provided. Omit to leave unchanged.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - artifact_id (string) (required) — Artifact ID ('art_' prefix). Also the key of the public-share link.
  - can_edit (boolean) (required) — Whether the caller may manage this artifact (rename, transfer, delete, share): the creator, any member of the owning team, or a manager of the source session.
  - content_type (string) (required) — MIME type of the file.
  - created_at (string) (required) — Unix timestamp in milliseconds when the artifact was published. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - creator_name (string) (required) — Creator's display name.
  - file_id (string) (required) — Presented-file ID ('pf_' prefix) currently holding the artifact's bytes. Changes on every republish.
  - is_mine (boolean) (required) — Whether the caller is the creator.
  - name (string) (required) — Underlying file name including extension.
  - person_id (integer) (required) — Person (member) ID of the creator.
  - public_url (string) — Anonymous public link — a console '/share/artifact/<artifact_id>' page served entirely from CDN. Present only while shared; anyone with the link can view it, no login required.
  - session_id (string) (required) — Source session ID ('sess_' prefix) that produced the file.
  - session_title (string) — Source session's title. Omitted when the session has been deleted.
  - share_enabled (boolean) — Whether anonymous public sharing is on. Omitted when false.
  - share_file_id (string) — Presented-file ID the public snapshot was materialized from. When 'share_enabled' is true and 'file_id' differs from 'share_file_id', the public snapshot is stale — call '/safari/artifact/gallery/share/sync' to refresh it.
  - shared_at (string) — Unix timestamp in milliseconds of the last share enable or snapshot sync. Present only while shared. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - shared_by (integer) — Person ID of the member who enabled sharing. Present only while shared.
  - size (integer) (required) — File size in bytes.
  - team_id (integer) (required) — Owning team ID. '0' means a personal artifact (creator-only management); a positive value means team-owned.
  - team_name (string) — Owning team's display name. Omitted for personal artifacts.
  - title (string) (required) — Display title in the gallery.
  - updated_at (string) (required) — Unix timestamp in milliseconds when the artifact was last updated (rename, transfer, or republish). CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
`,
		Args:    requireBodyFieldOrExactArg("artifact_id", "artifact-id"),
		Example: `  flashduty safari artifact-gallery-update --data '{"artifact_id":"art_VnfrWic8UbB9q3EfYR4Gmg","title":"SK 海力士 2026 Q2 财报深度分析（终稿）"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "artifact_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("artifact-id") {
						body["artifact_id"] = fArtifactID
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("title") {
						body["title"] = fTitle
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ArtifactUpdateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Artifacts.WriteUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fArtifactID, "artifact-id", "", "Artifact ID ('art_' prefix). Also the key of the public-share link. (required)")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Transfer target scope. '0' moves the artifact to personal scope (only the creator can manage it); a positive value moves it to a team the caller must belong to. Omit to leave unchanged.")
	cmd.Flags().StringVar(&fTitle, "title", "", "New title. Trimmed; must be non-empty when provided. Omit to leave unchanged.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedArtifacts(root *cobra.Command) {
	gSafari := genGroup(root, "safari", "AI SRE API")
	genAddLeaf(gSafari, genArtifactsReadGetCmd())
	genAddLeaf(gSafari, genArtifactsReadGetFileStateCmd())
	genAddLeaf(gSafari, genArtifactsReadListCmd())
	genAddLeaf(gSafari, genArtifactsReadSignCmd())
	genAddLeaf(gSafari, genArtifactsReadStreamCmd())
	genAddLeaf(gSafari, genArtifactsWriteDeleteCmd())
	genAddLeaf(gSafari, genArtifactsWritePublishCmd())
	genAddLeaf(gSafari, genArtifactsWriteShareEnableCmd())
	genAddLeaf(gSafari, genArtifactsWriteShareRevokeCmd())
	genAddLeaf(gSafari, genArtifactsWriteShareSyncCmd())
	genAddLeaf(gSafari, genArtifactsWriteUpdateCmd())
}
