// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genStatusPagesReadPageListCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List status pages",
		Long: `List status pages.

List all status pages owned by the account, including their components and sections.

API: GET /status-page/list (status-page-read-page-list)
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				out, _, err := ctx.Client.StatusPages.ReadPageList(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeActiveListCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "change-active-list",
		Short: "List active status page events",
		Long: `List active status page events.

List in-progress (non-terminal) events of a given type for a status page.

API: GET /status-page/change/active/list (statusPageChangeActiveList)
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				req := new(flashduty.StatusPagesChangeActiveListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.ChangeActiveList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeCreateCmd() *cobra.Command {
	var dataJSON string
	var fAutoUpdateBySchedule bool
	var fCloseAtSeconds int64
	var fDescription string
	var fIsRetrospective bool
	var fLinkedChanges []string
	var fNotifySubscribers bool
	var fPageID int64
	var fResponders []int
	var fStartAtSeconds int64
	var fStatus string
	var fTitle string
	var fType string
	cmd := &cobra.Command{
		Use:   "change-create",
		Short: "Create status page event",
		Long: `Create status page event.

Create a new incident or maintenance event on a status page.

API: POST /status-page/change/create (statusPageChangeCreate)

Request fields:
  --auto-update-by-schedule bool — Maintenance only: automatically advance the status based on the scheduled window.
  --close-at-seconds int — Scheduled close time for retrospective events. Must be greater than 'start_at_seconds'.
  --description string — Event description (Markdown). Required by the validator.
  --is-retrospective bool — Mark this event as a retrospective (historical) one.
  --linked-changes []string — Linked change IDs (related incidents, deployments, etc.).
  --notify-subscribers bool — Notify subscribers about this event and all its updates.
  --page-id int (required) — Status page ID.
  --responders []int — Member IDs responsible for this event.
  --start-at-seconds int — Event start time in unix seconds. Defaults to now when omitted.
  --status string (required) — Initial event status. 'investigating'/'identified'/'monitoring'/'resolved' apply to incidents; 'scheduled'/'ongoing'/'completed' apply to maintenances. [investigating, identified, monitoring, resolved, scheduled, ongoing, completed]
  --title string (required) — Event title, up to 255 characters.
  --type string (required) — Event type. [incident, maintenance]
  updates (JSON, via --data) (required) — Timeline updates. Immediate events normally pass one update; retrospective events must pass all historical updates.
`,
		Example: `  flashduty status-page change-create --data '{"description":"We are investigating degraded performance affecting the web console.","notify_subscribers":true,"page_id":5750613685214,"start_at_seconds":1712000000,"status":"investigating","title":"Web Console Degraded Performance","type":"incident","updates":[{"component_changes":[{"component_id":"01KC3GAZ6ZJE40H55GM31RPWZE","status":"degraded"}],"description":"We are currently investigating an issue affecting some users.","status":"investigating"}]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("auto-update-by-schedule") {
						body["auto_update_by_schedule"] = fAutoUpdateBySchedule
					}
					if cmd.Flags().Changed("close-at-seconds") {
						body["close_at_seconds"] = fCloseAtSeconds
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("is-retrospective") {
						body["is_retrospective"] = fIsRetrospective
					}
					if cmd.Flags().Changed("linked-changes") {
						body["linked_changes"] = fLinkedChanges
					}
					if cmd.Flags().Changed("notify-subscribers") {
						body["notify_subscribers"] = fNotifySubscribers
					}
					if cmd.Flags().Changed("page-id") {
						body["page_id"] = fPageID
					}
					if cmd.Flags().Changed("responders") {
						body["responders"] = fResponders
					}
					if cmd.Flags().Changed("start-at-seconds") {
						body["start_at_seconds"] = fStartAtSeconds
					}
					if cmd.Flags().Changed("status") {
						body["status"] = fStatus
					}
					if cmd.Flags().Changed("title") {
						body["title"] = fTitle
					}
					if cmd.Flags().Changed("type") {
						body["type"] = fType
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CreateStatusPageChangeRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.ChangeCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().BoolVar(&fAutoUpdateBySchedule, "auto-update-by-schedule", false, "Maintenance only: automatically advance the status based on the scheduled window.")
	cmd.Flags().Int64Var(&fCloseAtSeconds, "close-at-seconds", 0, "Scheduled close time for retrospective events. Must be greater than `start_at_seconds`.")
	cmd.Flags().StringVar(&fDescription, "description", "", "Event description (Markdown). Required by the validator.")
	cmd.Flags().BoolVar(&fIsRetrospective, "is-retrospective", false, "Mark this event as a retrospective (historical) one.")
	cmd.Flags().StringSliceVar(&fLinkedChanges, "linked-changes", nil, "Linked change IDs (related incidents, deployments, etc.).")
	cmd.Flags().BoolVar(&fNotifySubscribers, "notify-subscribers", false, "Notify subscribers about this event and all its updates.")
	cmd.Flags().Int64Var(&fPageID, "page-id", 0, "Status page ID. (required)")
	cmd.Flags().IntSliceVar(&fResponders, "responders", nil, "Member IDs responsible for this event.")
	cmd.Flags().Int64Var(&fStartAtSeconds, "start-at-seconds", 0, "Event start time in unix seconds. Defaults to now when omitted.")
	cmd.Flags().StringVar(&fStatus, "status", "", "Initial event status. `investigating`/`identified`/`monitoring`/`resolved` apply to incidents; `scheduled`/`ongoing`/`completed` apply to maintenances. (required) [investigating, identified, monitoring, resolved, scheduled, ongoing, completed]")
	cmd.Flags().StringVar(&fTitle, "title", "", "Event title, up to 255 characters. (required)")
	cmd.Flags().StringVar(&fType, "type", "", "Event type. (required) [incident, maintenance]")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeDeleteCmd() *cobra.Command {
	var dataJSON string
	var fChangeID int64
	var fPageID int64
	cmd := &cobra.Command{
		Use:   "change-delete",
		Short: "Delete status page event",
		Long: `Delete status page event.

Delete a status page event.

API: POST /status-page/change/delete (statusPageChangeDelete)

Request fields:
  --change-id int (required) — Target event ID.
  --page-id int (required) — Status page ID.
`,
		Example: `  flashduty status-page change-delete --data '{"change_id":5821693893131,"page_id":5750613685214}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("change-id") {
						body["change_id"] = fChangeID
					}
					if cmd.Flags().Changed("page-id") {
						body["page_id"] = fPageID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.DeleteStatusPageChangeRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.StatusPages.ChangeDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /status-page/change/delete")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChangeID, "change-id", 0, "Target event ID. (required)")
	cmd.Flags().Int64Var(&fPageID, "page-id", 0, "Status page ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeInfoCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "change-info",
		Short: "Get status page event detail",
		Long: `Get status page event detail.

Retrieve details of a specific status page event (incident or maintenance).

API: GET /status-page/change/info (statusPageChangeInfo)
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				req := new(flashduty.StatusPagesChangeInfoRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.ChangeInfo(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeListCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "change-list",
		Short: "List status page events",
		Long: `List status page events.

List events (incidents and maintenances) for a status page.

API: GET /status-page/change/list (statusPageChangeList)
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				req := new(flashduty.StatusPagesChangeListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.ChangeList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeTimelineCreateCmd() *cobra.Command {
	var dataJSON string
	var fAtSeconds int64
	var fChangeID int64
	var fDescription string
	var fPageID int64
	var fStatus string
	cmd := &cobra.Command{
		Use:   "change-timeline-create",
		Short: "Create event timeline entry",
		Long: `Create event timeline entry.

Add a timeline update to a status page event.

API: POST /status-page/change/timeline/create (statusPageChangeTimelineCreate)

Request fields:
  --at-seconds int — Update timestamp in unix seconds. Defaults to now when omitted.
  --change-id int (required) — Target event ID.
  --description string — Update description (Markdown). Required.
  --page-id int (required) — Status page ID.
  --status string (required) — New event status. Must match the event type. When the status transitions to 'resolved' or 'completed', all referenced components must become 'operational'. [investigating, identified, monitoring, resolved, scheduled, ongoing, completed]
  component_changes (JSON, via --data) — Component status transitions applied by this update. Component IDs must be unique.
`,
		Example: `  flashduty status-page change-timeline-create --data '{"at_seconds":1712003600,"change_id":5821693893131,"component_changes":[{"component_id":"01KC3GAZ6ZJE40H55GM31RPWZE","status":"partial_outage"}],"description":"We have identified the root cause and are working on a fix.","page_id":5750613685214,"status":"identified"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("at-seconds") {
						body["at_seconds"] = fAtSeconds
					}
					if cmd.Flags().Changed("change-id") {
						body["change_id"] = fChangeID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("page-id") {
						body["page_id"] = fPageID
					}
					if cmd.Flags().Changed("status") {
						body["status"] = fStatus
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CreateStatusPageChangeTimelineRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.ChangeTimelineCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fAtSeconds, "at-seconds", 0, "Update timestamp in unix seconds. Defaults to now when omitted.")
	cmd.Flags().Int64Var(&fChangeID, "change-id", 0, "Target event ID. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Update description (Markdown). Required.")
	cmd.Flags().Int64Var(&fPageID, "page-id", 0, "Status page ID. (required)")
	cmd.Flags().StringVar(&fStatus, "status", "", "New event status. Must match the event type. When the status transitions to `resolved` or `completed`, all referenced components must become `operational`. (required) [investigating, identified, monitoring, resolved, scheduled, ongoing, completed]")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeTimelineDeleteCmd() *cobra.Command {
	var dataJSON string
	var fChangeID int64
	var fPageID int64
	var fUpdateID string
	cmd := &cobra.Command{
		Use:   "change-timeline-delete",
		Short: "Delete event timeline entry",
		Long: `Delete event timeline entry.

Delete a timeline entry from a status page event.

API: POST /status-page/change/timeline/delete (statusPageChangeTimelineDelete)

Request fields:
  --change-id int (required) — Parent event ID.
  --page-id int (required) — Status page ID.
  --update-id string (required) — Timeline update ID to delete.
`,
		Example: `  flashduty status-page change-timeline-delete --data '{"change_id":5821693893131,"page_id":5750613685214,"update_id":"01KP0311872NVYFRRQ82FWXAP4"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("change-id") {
						body["change_id"] = fChangeID
					}
					if cmd.Flags().Changed("page-id") {
						body["page_id"] = fPageID
					}
					if cmd.Flags().Changed("update-id") {
						body["update_id"] = fUpdateID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.DeleteStatusPageChangeTimelineRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.StatusPages.ChangeTimelineDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /status-page/change/timeline/delete")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChangeID, "change-id", 0, "Parent event ID. (required)")
	cmd.Flags().Int64Var(&fPageID, "page-id", 0, "Status page ID. (required)")
	cmd.Flags().StringVar(&fUpdateID, "update-id", "", "Timeline update ID to delete. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeTimelineUpdateCmd() *cobra.Command {
	var dataJSON string
	var fAtSeconds int64
	var fChangeID int64
	var fDescription string
	var fPageID int64
	var fUpdateID string
	cmd := &cobra.Command{
		Use:   "change-timeline-update",
		Short: "Update event timeline entry",
		Long: `Update event timeline entry.

Update a timeline entry for a status page event.

API: POST /status-page/change/timeline/update (statusPageChangeTimelineUpdate)

Request fields:
  --at-seconds int — New update timestamp in unix seconds.
  --change-id int (required) — Parent event ID.
  --description string — New update description (Markdown).
  --page-id int (required) — Status page ID.
  --update-id string (required) — Target timeline update ID.
`,
		Example: `  flashduty status-page change-timeline-update --data '{"at_seconds":1712003600,"change_id":5821693893131,"description":"Corrected description: root cause identified in database layer.","page_id":5750613685214,"update_id":"01KP0311872NVYFRRQ82FWXAP4"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("at-seconds") {
						body["at_seconds"] = fAtSeconds
					}
					if cmd.Flags().Changed("change-id") {
						body["change_id"] = fChangeID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("page-id") {
						body["page_id"] = fPageID
					}
					if cmd.Flags().Changed("update-id") {
						body["update_id"] = fUpdateID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.UpdateStatusPageChangeTimelineRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.StatusPages.ChangeTimelineUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /status-page/change/timeline/update")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fAtSeconds, "at-seconds", 0, "New update timestamp in unix seconds.")
	cmd.Flags().Int64Var(&fChangeID, "change-id", 0, "Parent event ID. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "New update description (Markdown).")
	cmd.Flags().Int64Var(&fPageID, "page-id", 0, "Status page ID. (required)")
	cmd.Flags().StringVar(&fUpdateID, "update-id", "", "Target timeline update ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesChangeUpdateCmd() *cobra.Command {
	var dataJSON string
	var fChangeID int64
	var fLinkedChanges []string
	var fPageID int64
	var fResponders []int
	var fTitle string
	cmd := &cobra.Command{
		Use:   "change-update",
		Short: "Update status page event",
		Long: `Update status page event.

Update an existing status page event.

API: POST /status-page/change/update (statusPageChangeUpdate)

Request fields:
  --change-id int (required) — Target event ID.
  --linked-changes []string — Linked event IDs. Pass the full replacement list.
  --page-id int (required) — Status page ID.
  --responders []int — Member IDs responsible for this event. Pass the full replacement list.
  --title string — New event title, up to 255 characters. Omit to keep the existing value.
`,
		Example: `  flashduty status-page change-update --data '{"change_id":5821693893131,"page_id":5750613685214,"title":"Web Console Degraded Performance (Updated)"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("change-id") {
						body["change_id"] = fChangeID
					}
					if cmd.Flags().Changed("linked-changes") {
						body["linked_changes"] = fLinkedChanges
					}
					if cmd.Flags().Changed("page-id") {
						body["page_id"] = fPageID
					}
					if cmd.Flags().Changed("responders") {
						body["responders"] = fResponders
					}
					if cmd.Flags().Changed("title") {
						body["title"] = fTitle
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.UpdateStatusPageChangeRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.StatusPages.ChangeUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /status-page/change/update")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChangeID, "change-id", 0, "Target event ID. (required)")
	cmd.Flags().StringSliceVar(&fLinkedChanges, "linked-changes", nil, "Linked event IDs. Pass the full replacement list.")
	cmd.Flags().Int64Var(&fPageID, "page-id", 0, "Status page ID. (required)")
	cmd.Flags().IntSliceVar(&fResponders, "responders", nil, "Member IDs responsible for this event. Pass the full replacement list.")
	cmd.Flags().StringVar(&fTitle, "title", "", "New event title, up to 255 characters. Omit to keep the existing value.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesMigrateEmailSubscribersCmd() *cobra.Command {
	var dataJSON string
	var fAPIKey string
	var fSourcePageID string
	var fTargetPageID int64
	cmd := &cobra.Command{
		Use:   "migrate-email-subscribers",
		Short: "Migrate email subscribers",
		Long: `Migrate email subscribers.

Start a migration job that imports email subscribers from an Atlassian Statuspage into an existing Flashduty status page.

API: POST /status-page/migrate-email-subscribers (statusPageMigrateEmailSubscribers)

Request fields:
  --api-key string (required) — Atlassian Statuspage API key with access to the source page.
  --source-page-id string (required) — Atlassian Statuspage source page ID.
  --target-page-id int (required) — Flashduty target status page ID that will receive the imported subscribers.
`,
		Example: `  flashduty status-page migrate-email-subscribers --data '{"api_key":"sk-stsp-xxxxxxxxxxxxxxxxxxxx","source_page_id":"abcdefghij","target_page_id":5750613685214}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("api-key") {
						body["api_key"] = fAPIKey
					}
					if cmd.Flags().Changed("source-page-id") {
						body["source_page_id"] = fSourcePageID
					}
					if cmd.Flags().Changed("target-page-id") {
						body["target_page_id"] = fTargetPageID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MigrateStatusPageEmailSubscribersRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.MigrateEmailSubscribers(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fAPIKey, "api-key", "", "Atlassian Statuspage API key with access to the source page. (required)")
	cmd.Flags().StringVar(&fSourcePageID, "source-page-id", "", "Atlassian Statuspage source page ID. (required)")
	cmd.Flags().Int64Var(&fTargetPageID, "target-page-id", 0, "Flashduty target status page ID that will receive the imported subscribers. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesMigrateStructureCmd() *cobra.Command {
	var dataJSON string
	var fAPIKey string
	var fSourcePageID string
	var fURLName string
	cmd := &cobra.Command{
		Use:   "migrate-structure",
		Short: "Migrate status page structure",
		Long: `Migrate status page structure.

Start a migration job that imports the structure and historical events of an Atlassian Statuspage into a new Flashduty status page.

API: POST /status-page/migrate-structure (statusPageMigrateStructure)

Request fields:
  --api-key string (required) — Atlassian Statuspage API key with access to the source page.
  --source-page-id string (required) — Atlassian Statuspage source page ID.
  --url-name string — Target URL name for the migrated status page. When omitted, the source page's URL name is reused.
`,
		Example: `  flashduty status-page migrate-structure --data '{"api_key":"sk-stsp-xxxxxxxxxxxxxxxxxxxx","source_page_id":"abcdefghij"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("api-key") {
						body["api_key"] = fAPIKey
					}
					if cmd.Flags().Changed("source-page-id") {
						body["source_page_id"] = fSourcePageID
					}
					if cmd.Flags().Changed("url-name") {
						body["url_name"] = fURLName
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.MigrateStatusPageStructureRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.MigrateStructure(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fAPIKey, "api-key", "", "Atlassian Statuspage API key with access to the source page. (required)")
	cmd.Flags().StringVar(&fSourcePageID, "source-page-id", "", "Atlassian Statuspage source page ID. (required)")
	cmd.Flags().StringVar(&fURLName, "url-name", "", "Target URL name for the migrated status page. When omitted, the source page's URL name is reused.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesMigrationCancelCmd() *cobra.Command {
	var dataJSON string
	var fJobID string
	cmd := &cobra.Command{
		Use:   "migration-cancel",
		Short: "Cancel status page migration",
		Long: `Cancel status page migration.

Cancel an in-progress status page migration job. Only jobs currently in the 'running' state can be cancelled.

API: POST /status-page/migration/cancel (statusPageMigrationCancel)

Request fields:
  --job-id string (required) — Migration job ID.
`,
		Example: `  flashduty status-page migration-cancel --data '{"job_id":"01KP0311872NVYFRRQ82FW0001"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("job-id") {
						body["job_id"] = fJobID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CancelStatusPageMigrationRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.StatusPages.MigrationCancel(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /status-page/migration/cancel")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fJobID, "job-id", "", "Migration job ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesMigrationStatusCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "migration-status",
		Short: "Get migration status",
		Long: `Get migration status.

Get the current status and progress of a status page migration job.

API: GET /status-page/migration/status (statusPageMigrationStatus)
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				req := new(flashduty.StatusPagesMigrationStatusRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.MigrationStatus(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesSubscriberExportCmd() *cobra.Command {
	var dataJSON string
	var fComponentIDs []string
	var fPageID int64
	cmd := &cobra.Command{
		Use:   "subscriber-export",
		Short: "Export subscribers",
		Long: `Export subscribers.

Export subscribers list for a status page as a CSV attachment. The response is a 'text/csv' file with columns: Method, Recipient, Components, Subscribe All, Locale.

API: POST /status-page/subscriber/export (statusPageSubscriberExport)

Request fields:
  --component-ids []string — Optional component IDs to filter subscribers by.
  --page-id int (required) — Status page ID.
`,
		Example: `  flashduty status-page subscriber-export --data '{"page_id":5750613685214}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("component-ids") {
						body["component_ids"] = fComponentIDs
					}
					if cmd.Flags().Changed("page-id") {
						body["page_id"] = fPageID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ExportStatusPageSubscribersRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.SubscriberExport(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringSliceVar(&fComponentIDs, "component-ids", nil, "Optional component IDs to filter subscribers by.")
	cmd.Flags().Int64Var(&fPageID, "page-id", 0, "Status page ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesSubscriberImportCmd() *cobra.Command {
	var dataJSON string
	var fMethod string
	var fPageID int64
	cmd := &cobra.Command{
		Use:   "subscriber-import",
		Short: "Import subscribers",
		Long: `Import subscribers.

Bulk import subscribers for a status page.

API: POST /status-page/subscriber/import (statusPageSubscriberImport)

Request fields:
  --method string (required) — Subscription method. 'email' is only valid for public pages; 'im' is only valid for internal pages. [email, im]
  --page-id int (required) — Target status page ID.
  subscribers (JSON, via --data) — Subscribers to import.
`,
		Example: `  flashduty status-page subscriber-import --data '{"method":"email","page_id":5750613685214,"subscribers":[{"all":true,"locale":"en-US","recipient":"alice@example.com"},{"all":false,"component_ids":["01KC3GAZ6ZJE40H55GM31RPWZE"],"locale":"zh-CN","recipient":"bob@example.com"}]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("method") {
						body["method"] = fMethod
					}
					if cmd.Flags().Changed("page-id") {
						body["page_id"] = fPageID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ImportStatusPageSubscribersRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.StatusPages.SubscriberImport(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /status-page/subscriber/import")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fMethod, "method", "", "Subscription method. `email` is only valid for public pages; `im` is only valid for internal pages. (required) [email, im]")
	cmd.Flags().Int64Var(&fPageID, "page-id", 0, "Target status page ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genStatusPagesSubscriberListCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "subscriber-list",
		Short: "List status page subscribers",
		Long: `List status page subscribers.

List subscribers who have signed up for status page notifications.

API: GET /status-page/subscriber/list (statusPageSubscriberList)
`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				req := new(flashduty.StatusPagesSubscriberListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.StatusPages.SubscriberList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func registerGeneratedStatusPages(root *cobra.Command) {
	gStatusPage := genGroup(root, "status-page", "On-call/Status pages API")
	genAddLeaf(gStatusPage, genStatusPagesReadPageListCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeActiveListCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeCreateCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeDeleteCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeInfoCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeListCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeTimelineCreateCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeTimelineDeleteCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeTimelineUpdateCmd())
	genAddLeaf(gStatusPage, genStatusPagesChangeUpdateCmd())
	genAddLeaf(gStatusPage, genStatusPagesMigrateEmailSubscribersCmd())
	genAddLeaf(gStatusPage, genStatusPagesMigrateStructureCmd())
	genAddLeaf(gStatusPage, genStatusPagesMigrationCancelCmd())
	genAddLeaf(gStatusPage, genStatusPagesMigrationStatusCmd())
	genAddLeaf(gStatusPage, genStatusPagesSubscriberExportCmd())
	genAddLeaf(gStatusPage, genStatusPagesSubscriberImportCmd())
	genAddLeaf(gStatusPage, genStatusPagesSubscriberListCmd())
}
