// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genSchedulesCreateCmd() *cobra.Command {
	var dataJSON string
	var fDescription string
	var fEnd int64
	var fName string
	var fScheduleID int64
	var fScheduleName string
	var fStart int64
	var fTeamID int64
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create schedule",
		Long: `Create schedule.

Create a new on-call schedule (escalation rule schedule).

API: POST /schedule/create (scheduleCreate)

Request fields:
  --description string — Schedule description. Max 500 characters.
  --end int — Preview window end (Unix seconds, 10 digits). Required for /schedule/preview. Max 45 days after start.
  --name string — Legacy schedule name field. Used when schedule_name is empty.
  --schedule-id int — Schedule ID. Required on update.
  --schedule-name string — Schedule display name. Max 40 characters.
  --start int — Preview window start (Unix seconds, 10 digits). Required for /schedule/preview.
  --team-id int — Owning team ID.
  layers (JSON, via --data) — Rotation layers.
  notify (JSON, via --data) — Notification configuration attached to a schedule.
`,
		Example: `  flashduty schedule create --data '{"description":"Primary on-call rotation for the production team","layers":[{"day_mask":{"repeat":[1,2,3,4,5]},"enable_time":1712000000,"expire_time":0,"fair_rotation":false,"groups":[{"end":0,"group_name":"A","members":[{"person_ids":[2451002751131],"role_id":0}],"name":"A","start":0},{"end":0,"group_name":"B","members":[{"person_ids":[2476123212131],"role_id":0}],"name":"B","start":0}],"handoff_time":0,"hidden":0,"layer_name":"Layer 1","mask_continuous_enabled":false,"mode":0,"name":"Layer 1","restrict_end":0,"restrict_mode":0,"restrict_periods":[],"restrict_start":0,"rotation_duration":86400,"rotation_unit":"day","rotation_value":1,"weight":0}],"notify":{"advance_in_time":300,"by":{"follow_preference":true,"personal_channels":null},"fixed_time":null,"webhooks":null},"schedule_name":"Production On-Call","team_id":4291079133131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("end") {
						body["end"] = fEnd
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("schedule-id") {
						body["schedule_id"] = fScheduleID
					}
					if cmd.Flags().Changed("schedule-name") {
						body["schedule_name"] = fScheduleName
					}
					if cmd.Flags().Changed("start") {
						body["start"] = fStart
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ScheduleUpsertRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Schedules.Create(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fDescription, "description", "", "Schedule description. Max 500 characters.")
	cmd.Flags().Int64Var(&fEnd, "end", 0, "Preview window end (Unix seconds, 10 digits). Required for /schedule/preview. Max 45 days after start.")
	cmd.Flags().StringVar(&fName, "name", "", "Legacy schedule name field. Used when schedule_name is empty.")
	cmd.Flags().Int64Var(&fScheduleID, "schedule-id", 0, "Schedule ID. Required on update.")
	cmd.Flags().StringVar(&fScheduleName, "schedule-name", "", "Schedule display name. Max 40 characters.")
	cmd.Flags().Int64Var(&fStart, "start", 0, "Preview window start (Unix seconds, 10 digits). Required for /schedule/preview.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Owning team ID.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genSchedulesDeleteCmd() *cobra.Command {
	var dataJSON string
	var fScheduleIDs []int
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete schedules",
		Long: `Delete schedules.

Delete one or more on-call schedules by ID.

API: POST /schedule/delete (scheduleDelete)

Request fields:
  --schedule-ids []int (required) — Schedule IDs to operate on.
`,
		Example: `  flashduty schedule delete --data '{"schedule_ids":[2001]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("schedule-ids") {
						body["schedule_ids"] = fScheduleIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ScheduleIDsBodyRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Schedules.Delete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /schedule/delete")
				return nil
			})
		},
	}
	cmd.Flags().IntSliceVar(&fScheduleIDs, "schedule-ids", nil, "Schedule IDs to operate on. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genSchedulesInfoCmd() *cobra.Command {
	var dataJSON string
	var fEnd int64
	var fScheduleID int64
	var fStart int64
	cmd := &cobra.Command{
		Use:   "info",
		Short: "Get schedule info",
		Long: `Get schedule info.

Return details of an on-call schedule including the computed schedule layers for the requested time window (max 45 days).

API: POST /schedule/info (scheduleInfo)

Request fields:
  --end int (required) — Preview end timestamp (Unix seconds, 10 digits).
  --schedule-id int (required) — Schedule ID.
  --start int (required) — Preview start timestamp (Unix seconds, 10 digits).
`,
		Example: `  flashduty schedule info --data '{"end":1712086400,"schedule_id":2001,"start":1712000000}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("end") {
						body["end"] = fEnd
					}
					if cmd.Flags().Changed("schedule-id") {
						body["schedule_id"] = fScheduleID
					}
					if cmd.Flags().Changed("start") {
						body["start"] = fStart
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ScheduleInfoRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Schedules.Info(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fEnd, "end", 0, "Preview end timestamp (Unix seconds, 10 digits). (required)")
	cmd.Flags().Int64Var(&fScheduleID, "schedule-id", 0, "Schedule ID. (required)")
	cmd.Flags().Int64Var(&fStart, "start", 0, "Preview start timestamp (Unix seconds, 10 digits). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genSchedulesInfosCmd() *cobra.Command {
	var dataJSON string
	var fScheduleIDs []int
	cmd := &cobra.Command{
		Use:   "infos",
		Short: "Batch get schedules",
		Long: `Batch get schedules.

Return details of multiple on-call schedules by their IDs.

API: POST /schedule/infos (scheduleInfos)

Request fields:
  --schedule-ids []int (required) — Schedule ID list.
`,
		Example: `  flashduty schedule infos --data '{"schedule_ids":[2001,2002,2003]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("schedule-ids") {
						body["schedule_ids"] = fScheduleIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ScheduleIDsRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Schedules.Infos(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().IntSliceVar(&fScheduleIDs, "schedule-ids", nil, "Schedule ID list. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genSchedulesListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fEnd int64
	var fIsMyManage bool
	var fIsMyTeam bool
	var fQuery string
	var fStart int64
	var fTeamIDs []int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List schedules",
		Long: `List schedules.

Return a paginated list of on-call schedules. When both start and end are provided (max 45 days apart), computed layer schedules are included.

API: POST /schedule/list (scheduleList)

Request fields:
  --p int — Page number (1-indexed).
  --limit int — Page size. Default 10, max 100.
  --search-after-ctx string
  --end int — Window end timestamp (Unix seconds).
  --is-my-manage bool — Only return schedules created by the current user within their teams.
  --is-my-team bool — Only return schedules whose owning team the current user belongs to.
  --query string — Search keyword matched against schedule names.
  --start int — When set together with end, computed layer schedules are returned. Span must be less than 45 days.
  --team-ids []int — Filter by team IDs.
`,
		Example: `  flashduty schedule list --data '{"is_my_team":true,"limit":20,"p":1,"query":"production"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("p") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("end") {
						body["end"] = fEnd
					}
					if cmd.Flags().Changed("is-my-manage") {
						body["is_my_manage"] = fIsMyManage
					}
					if cmd.Flags().Changed("is-my-team") {
						body["is_my_team"] = fIsMyTeam
					}
					if cmd.Flags().Changed("query") {
						body["query"] = fQuery
					}
					if cmd.Flags().Changed("start") {
						body["start"] = fStart
					}
					if cmd.Flags().Changed("team-ids") {
						body["team_ids"] = fTeamIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ScheduleListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Schedules.List(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "p", 0, "Page number (1-indexed).")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size. Default 10, max 100.")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().Int64Var(&fEnd, "end", 0, "Window end timestamp (Unix seconds).")
	cmd.Flags().BoolVar(&fIsMyManage, "is-my-manage", false, "Only return schedules created by the current user within their teams.")
	cmd.Flags().BoolVar(&fIsMyTeam, "is-my-team", false, "Only return schedules whose owning team the current user belongs to.")
	cmd.Flags().StringVar(&fQuery, "query", "", "Search keyword matched against schedule names.")
	cmd.Flags().Int64Var(&fStart, "start", 0, "When set together with end, computed layer schedules are returned. Span must be less than 45 days.")
	cmd.Flags().IntSliceVar(&fTeamIDs, "team-ids", nil, "Filter by team IDs.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genSchedulesPreviewCmd() *cobra.Command {
	var dataJSON string
	var fDescription string
	var fEnd int64
	var fName string
	var fScheduleID int64
	var fScheduleName string
	var fStart int64
	var fTeamID int64
	cmd := &cobra.Command{
		Use:   "preview",
		Short: "Preview schedule",
		Long: `Preview schedule.

Preview the coverage generated by a schedule configuration without persisting it. The request accepts the same body as create/update plus a required start/end window (max 45 days).

API: POST /schedule/preview (schedulePreview)

Request fields:
  --description string — Schedule description. Max 500 characters.
  --end int — Preview window end (Unix seconds, 10 digits). Required for /schedule/preview. Max 45 days after start.
  --name string — Legacy schedule name field. Used when schedule_name is empty.
  --schedule-id int — Schedule ID. Required on update.
  --schedule-name string — Schedule display name. Max 40 characters.
  --start int — Preview window start (Unix seconds, 10 digits). Required for /schedule/preview.
  --team-id int — Owning team ID.
  layers (JSON, via --data) — Rotation layers.
  notify (JSON, via --data) — Notification configuration attached to a schedule.
`,
		Example: `  flashduty schedule preview --data '{"end":1712086400,"layers":[{"day_mask":{"repeat":[1,2,3,4,5]},"enable_time":1712000000,"expire_time":0,"fair_rotation":false,"groups":[{"end":0,"group_name":"A","members":[{"person_ids":[2451002751131],"role_id":0}],"name":"A","start":0}],"handoff_time":0,"hidden":0,"layer_name":"Layer 1","mask_continuous_enabled":false,"mode":0,"name":"Layer 1","restrict_end":0,"restrict_mode":0,"restrict_periods":[],"restrict_start":0,"rotation_duration":86400,"rotation_unit":"day","rotation_value":1,"weight":0}],"schedule_name":"Preview Schedule","start":1712000000}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("end") {
						body["end"] = fEnd
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("schedule-id") {
						body["schedule_id"] = fScheduleID
					}
					if cmd.Flags().Changed("schedule-name") {
						body["schedule_name"] = fScheduleName
					}
					if cmd.Flags().Changed("start") {
						body["start"] = fStart
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ScheduleUpsertRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Schedules.Preview(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fDescription, "description", "", "Schedule description. Max 500 characters.")
	cmd.Flags().Int64Var(&fEnd, "end", 0, "Preview window end (Unix seconds, 10 digits). Required for /schedule/preview. Max 45 days after start.")
	cmd.Flags().StringVar(&fName, "name", "", "Legacy schedule name field. Used when schedule_name is empty.")
	cmd.Flags().Int64Var(&fScheduleID, "schedule-id", 0, "Schedule ID. Required on update.")
	cmd.Flags().StringVar(&fScheduleName, "schedule-name", "", "Schedule display name. Max 40 characters.")
	cmd.Flags().Int64Var(&fStart, "start", 0, "Preview window start (Unix seconds, 10 digits). Required for /schedule/preview.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Owning team ID.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genSchedulesSelfCmd() *cobra.Command {
	var dataJSON string
	var fEnd int64
	var fStart int64
	cmd := &cobra.Command{
		Use:   "self",
		Short: "List my schedules",
		Long: `List my schedules.

Return on-call schedules where the current user is assigned.

API: POST /schedule/self (scheduleSelf)

Request fields:
  --end int — Window end (Unix seconds, 10 digits). Must be within 30 days of start.
  --start int — Window start (Unix seconds, 10 digits).
`,
		Example: `  flashduty schedule self --data '{"end":1712086400,"start":1712000000}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("end") {
						body["end"] = fEnd
					}
					if cmd.Flags().Changed("start") {
						body["start"] = fStart
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ScheduleSelfRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Schedules.Self(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fEnd, "end", 0, "Window end (Unix seconds, 10 digits). Must be within 30 days of start.")
	cmd.Flags().Int64Var(&fStart, "start", 0, "Window start (Unix seconds, 10 digits).")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genSchedulesUpdateCmd() *cobra.Command {
	var dataJSON string
	var fDescription string
	var fEnd int64
	var fName string
	var fScheduleID int64
	var fScheduleName string
	var fStart int64
	var fTeamID int64
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update schedule",
		Long: `Update schedule.

Update an existing on-call schedule. Provide schedule_id to identify the schedule.

API: POST /schedule/update (scheduleUpdate)

Request fields:
  --description string — Schedule description. Max 500 characters.
  --end int — Preview window end (Unix seconds, 10 digits). Required for /schedule/preview. Max 45 days after start.
  --name string — Legacy schedule name field. Used when schedule_name is empty.
  --schedule-id int — Schedule ID. Required on update.
  --schedule-name string — Schedule display name. Max 40 characters.
  --start int — Preview window start (Unix seconds, 10 digits). Required for /schedule/preview.
  --team-id int — Owning team ID.
  layers (JSON, via --data) — Rotation layers.
  notify (JSON, via --data) — Notification configuration attached to a schedule.
`,
		Example: `  flashduty schedule update --data '{"description":"Updated primary on-call rotation","schedule_id":2001,"schedule_name":"Production On-Call (Updated)","team_id":4291079133131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("end") {
						body["end"] = fEnd
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("schedule-id") {
						body["schedule_id"] = fScheduleID
					}
					if cmd.Flags().Changed("schedule-name") {
						body["schedule_name"] = fScheduleName
					}
					if cmd.Flags().Changed("start") {
						body["start"] = fStart
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ScheduleUpsertRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Schedules.Update(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /schedule/update")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fDescription, "description", "", "Schedule description. Max 500 characters.")
	cmd.Flags().Int64Var(&fEnd, "end", 0, "Preview window end (Unix seconds, 10 digits). Required for /schedule/preview. Max 45 days after start.")
	cmd.Flags().StringVar(&fName, "name", "", "Legacy schedule name field. Used when schedule_name is empty.")
	cmd.Flags().Int64Var(&fScheduleID, "schedule-id", 0, "Schedule ID. Required on update.")
	cmd.Flags().StringVar(&fScheduleName, "schedule-name", "", "Schedule display name. Max 40 characters.")
	cmd.Flags().Int64Var(&fStart, "start", 0, "Preview window start (Unix seconds, 10 digits). Required for /schedule/preview.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Owning team ID.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func registerGeneratedSchedules(root *cobra.Command) {
	gSchedule := genGroup(root, "schedule", "On-call/Schedules API")
	genAddLeaf(gSchedule, genSchedulesCreateCmd())
	genAddLeaf(gSchedule, genSchedulesDeleteCmd())
	genAddLeaf(gSchedule, genSchedulesInfoCmd())
	genAddLeaf(gSchedule, genSchedulesInfosCmd())
	genAddLeaf(gSchedule, genSchedulesListCmd())
	genAddLeaf(gSchedule, genSchedulesPreviewCmd())
	genAddLeaf(gSchedule, genSchedulesSelfCmd())
	genAddLeaf(gSchedule, genSchedulesUpdateCmd())
}
