// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genCalendarsCalEventDeleteCmd() *cobra.Command {
	var dataJSON string
	var fCalID string
	var fEventID string
	cmd := &cobra.Command{
		Use:   "event-delete",
		Short: "Delete calendar event",
		Long: `Delete calendar event.

Delete a calendar event by calendar ID and event ID.

API: POST /calendar/event/delete (calEventDelete)

Request fields:
  --cal-id string (required) — Calendar ID.
  --event-id string (required) — Event ID.
`,
		Example: `  flashduty calendar event-delete --data '{"cal_id":"cal.QiNvtdKs4Wj52kZhT3LafM","event_id":"cale.KyG9XWTCU5CucbwukEVBQ4"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("cal-id") {
						body["cal_id"] = fCalID
					}
					if cmd.Flags().Changed("event-id") {
						body["event_id"] = fEventID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CalEventIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Calendars.CalEventDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /calendar/event/delete")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fCalID, "cal-id", "", "Calendar ID. (required)")
	cmd.Flags().StringVar(&fEventID, "event-id", "", "Event ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genCalendarsCalEventListCmd() *cobra.Command {
	var dataJSON string
	var fCalID string
	var fDay int64
	var fMonth int64
	var fYear int64
	cmd := &cobra.Command{
		Use:   "event-list",
		Short: "List calendar events",
		Long: `List calendar events.

Return events for a personal calendar within a year/month/day scope. When month and day are both omitted the whole year is returned.

API: POST /calendar/event/list (calEventList)

Request fields:
  --cal-id string (required) — Calendar ID.
  --day int — Day (1-31). 0 means no day filter. (0-31)
  --month int — Month (1-12). 0 means no month filter. (0-12)
  --year int — Year. Defaults to the current year when omitted. (min 2023)

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>) (required) — Calendar events sorted by start_at.
    - account_id (integer) — Account ID. Only present for private events.
    - cal_id (string) (required) — Calendar ID. For public events this is a locale key such as zh-cn.china.official.
    - created_at (integer) (required) — Creation timestamp (Unix seconds).
    - creator_id (integer) — Creator person ID. Only present for private events.
    - description (string) (required) — Event description.
    - end_at (string) (required) — Event end date (YYYY-MM-DD, exclusive).
    - event_id (string) (required) — Event ID.
    - is_off (boolean) (required) — Whether the event marks a non-working day.
    - start_at (string) (required) — Event start date (YYYY-MM-DD).
    - summary (string) (required) — Event summary.
    - updated_at (integer) (required) — Last update timestamp (Unix seconds).
  - total (integer) (required) — Total number of events returned.
`,
		Example: `  flashduty calendar event-list --data '{"cal_id":"cal.QiNvtdKs4Wj52kZhT3LafM","month":5,"year":2024}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("cal-id") {
						body["cal_id"] = fCalID
					}
					if cmd.Flags().Changed("day") {
						body["day"] = fDay
					}
					if cmd.Flags().Changed("month") {
						body["month"] = fMonth
					}
					if cmd.Flags().Changed("year") {
						body["year"] = fYear
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CalEventListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Calendars.CalEventList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fCalID, "cal-id", "", "Calendar ID. (required)")
	cmd.Flags().Int64Var(&fDay, "day", 0, "Day (1-31). 0 means no day filter. (0-31)")
	cmd.Flags().Int64Var(&fMonth, "month", 0, "Month (1-12). 0 means no month filter. (0-12)")
	cmd.Flags().Int64Var(&fYear, "year", 0, "Year. Defaults to the current year when omitted. (min 2023)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genCalendarsCalEventUpsertCmd() *cobra.Command {
	var dataJSON string
	var fCalID string
	var fDescription string
	var fEndAt string
	var fEventID string
	var fIsOff bool
	var fStartAt string
	var fSummary string
	cmd := &cobra.Command{
		Use:   "event-upsert",
		Short: "Upsert calendar event",
		Long: `Upsert calendar event.

Create or update a calendar event (holiday or workday override). Omit event_id to create a new event.

API: POST /calendar/event/upsert (calEventUpsert)

Request fields:
  --cal-id string (required) — Calendar ID.
  --description string — Event description. (≤499 chars)
  --end-at string (required) — Event end date in YYYY-MM-DD (exclusive).
  --event-id string — Event ID. Omit when creating. (≤63 chars)
  --is-off bool (required) — Whether the event marks a non-working day. true = day off, false = working day override.
  --start-at string (required) — Event start date in YYYY-MM-DD.
  --summary string (required) — Event summary. (1-39 chars)

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - cal_id (string) (required) — Calendar ID.
  - event_id (string) (required) — Event ID (existing or newly generated).
  - summary (string) (required) — Event summary.
`,
		Example: `  flashduty calendar event-upsert --data '{"cal_id":"cal.QiNvtdKs4Wj52kZhT3LafM","description":"International Workers Day holiday","end_at":"2024-05-06","is_off":true,"start_at":"2024-05-01","summary":"Labour Day"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("cal-id") {
						body["cal_id"] = fCalID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("end-at") {
						body["end_at"] = fEndAt
					}
					if cmd.Flags().Changed("event-id") {
						body["event_id"] = fEventID
					}
					if cmd.Flags().Changed("is-off") {
						body["is_off"] = fIsOff
					}
					if cmd.Flags().Changed("start-at") {
						body["start_at"] = fStartAt
					}
					if cmd.Flags().Changed("summary") {
						body["summary"] = fSummary
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CalEventUpsertRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Calendars.CalEventUpsert(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fCalID, "cal-id", "", "Calendar ID. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Event description. (≤499 chars)")
	cmd.Flags().StringVar(&fEndAt, "end-at", "", "Event end date in YYYY-MM-DD (exclusive). (required)")
	cmd.Flags().StringVar(&fEventID, "event-id", "", "Event ID. Omit when creating. (≤63 chars)")
	cmd.Flags().BoolVar(&fIsOff, "is-off", false, "Whether the event marks a non-working day. true = day off, false = working day override. (required)")
	cmd.Flags().StringVar(&fStartAt, "start-at", "", "Event start date in YYYY-MM-DD. (required)")
	cmd.Flags().StringVar(&fSummary, "summary", "", "Event summary. (required) (1-39 chars)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genCalendarsCalendarCreateCmd() *cobra.Command {
	var dataJSON string
	var fCalName string
	var fDescription string
	var fExtraCalIDs []string
	var fTeamID int64
	var fTimezone string
	var fWorkdays []int
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create calendar",
		Long: `Create calendar.

Create a personal service calendar. Each account is limited to 5 calendars unless the Flashcat-Break-Cal-Limit header is set.

API: POST /calendar/create (calendarCreate)

Request fields:
  --cal-name string (required) — Calendar display name. (1-39 chars)
  --description string — Calendar description. (≤499 chars)
  --extra-cal-ids []string — Additional public-holiday calendar IDs to inherit events from (for example zh-cn.china.official).
  --team-id int — Owning team ID. 0 means no team.
  --timezone string — IANA timezone. Defaults to Asia/Shanghai when empty.
  --workdays []int — Workday numbers (0 = Sunday, 6 = Saturday).

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - cal_id (string) (required) — ID of the newly created calendar (format cal.<uuid>).
  - cal_name (string) (required) — Calendar display name.
`,
		Example: `  flashduty calendar create --data '{"cal_name":"Production On-Call Calendar","description":"Calendar for production on-call team","timezone":"Asia/Shanghai","workdays":[1,2,3,4,5]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("cal-name") {
						body["cal_name"] = fCalName
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("extra-cal-ids") {
						body["extra_cal_ids"] = fExtraCalIDs
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("timezone") {
						body["timezone"] = fTimezone
					}
					if cmd.Flags().Changed("workdays") {
						body["workdays"] = fWorkdays
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CalendarCreateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Calendars.CalendarCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fCalName, "cal-name", "", "Calendar display name. (required) (1-39 chars)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Calendar description. (≤499 chars)")
	cmd.Flags().StringSliceVar(&fExtraCalIDs, "extra-cal-ids", nil, "Additional public-holiday calendar IDs to inherit events from (for example zh-cn.china.official).")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Owning team ID. 0 means no team.")
	cmd.Flags().StringVar(&fTimezone, "timezone", "", "IANA timezone. Defaults to Asia/Shanghai when empty.")
	cmd.Flags().IntSliceVar(&fWorkdays, "workdays", nil, "Workday numbers (0 = Sunday, 6 = Saturday).")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genCalendarsCalendarDeleteCmd() *cobra.Command {
	var dataJSON string
	var fCalID string
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete calendar",
		Long: `Delete calendar.

Delete a personal service calendar. The call fails when referenced by escalation or silence rules.

API: POST /calendar/delete (calendarDelete)

Request fields:
  --cal-id string (required) — Calendar ID.
`,
		Example: `  flashduty calendar delete --data '{"cal_id":"cal.QiNvtdKs4Wj52kZhT3LafM"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("cal-id") {
						body["cal_id"] = fCalID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CalendarIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Calendars.CalendarDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /calendar/delete")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fCalID, "cal-id", "", "Calendar ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genCalendarsCalendarInfoCmd() *cobra.Command {
	var dataJSON string
	var fCalID string
	cmd := &cobra.Command{
		Use:   "info",
		Short: "Get calendar info",
		Long: `Get calendar info.

Return details of a service calendar.

API: POST /calendar/info (calendarInfo)

Request fields:
  --cal-id string (required) — Calendar ID.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) (required) — Account ID.
  - cal_id (string) (required) — Calendar ID.
  - cal_name (string) (required) — Calendar display name.
  - created_at (integer) (required) — Creation timestamp (Unix seconds).
  - creator_id (integer) (required) — Creator person ID.
  - description (string) (required) — Calendar description.
  - extra_cal_ids (array<string>) — Inherited public-holiday calendar IDs.
  - kind (string) (required) — Calendar kind. [region.official.holiday, religion.holiday, personal]
  - status (string) (required) — Calendar status. [enabled, deleted]
  - team_id (integer) (required) — Owning team ID (0 when not assigned).
  - timezone (string) (required) — IANA timezone.
  - updated_at (integer) (required) — Last update timestamp (Unix seconds).
  - updated_by (integer) (required) — Last updater person ID.
  - workdays (array<integer>) — Workday numbers (0 = Sunday, 6 = Saturday).
`,
		Example: `  flashduty calendar info --data '{"cal_id":"cal.eh9gvPtWeH3xXgKeVSRxRg"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("cal-id") {
						body["cal_id"] = fCalID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CalendarIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Calendars.CalendarInfo(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fCalID, "cal-id", "", "Calendar ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genCalendarsCalendarListCmd() *cobra.Command {
	var dataJSON string
	var fKind string
	var fNoLocale bool
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List calendars",
		Long: `List calendars.

Return the list of service calendars visible to the current account.

API: POST /calendar/list (calendarList)

Request fields:
  --kind string — Calendar kind filter. Defaults to personal when empty. [region.official.holiday, personal]
  --no-locale bool — Disable locale filtering when listing public-holiday calendars.

Response fields ('data' envelope is unwrapped — rows are nested under items[]; pipe 'jq '.items[]'', NOT '.data.items[]'):
  - items (array<object>) (required) — Calendar items.
    - account_id (integer) (required) — Account ID.
    - cal_id (string) (required) — Calendar ID.
    - cal_name (string) (required) — Calendar display name.
    - created_at (integer) (required) — Creation timestamp (Unix seconds).
    - creator_id (integer) (required) — Creator person ID.
    - description (string) (required) — Calendar description.
    - extra_cal_ids (array<string>) — Inherited public-holiday calendar IDs.
    - kind (string) (required) — Calendar kind. [region.official.holiday, religion.holiday, personal]
    - status (string) (required) — Calendar status. [enabled, deleted]
    - team_id (integer) (required) — Owning team ID (0 when not assigned).
    - timezone (string) (required) — IANA timezone.
    - updated_at (integer) (required) — Last update timestamp (Unix seconds).
    - updated_by (integer) (required) — Last updater person ID.
    - workdays (array<integer>) — Workday numbers (0 = Sunday, 6 = Saturday).
  - total (integer) (required) — Total number of calendars returned.
`,
		Example: `  flashduty calendar list --data '{"kind":"personal"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("kind") {
						body["kind"] = fKind
					}
					if cmd.Flags().Changed("no-locale") {
						body["no_locale"] = fNoLocale
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CalendarListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Calendars.CalendarList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fKind, "kind", "", "Calendar kind filter. Defaults to personal when empty. [region.official.holiday, personal]")
	cmd.Flags().BoolVar(&fNoLocale, "no-locale", false, "Disable locale filtering when listing public-holiday calendars.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genCalendarsCalendarUpdateCmd() *cobra.Command {
	var dataJSON string
	var fCalID string
	var fCalName string
	var fDescription string
	var fExtraCalIDs []string
	var fTeamID int64
	var fTimezone string
	var fWorkdays []int
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update calendar",
		Long: `Update calendar.

Update a personal service calendar. Only non-null fields are updated.

API: POST /calendar/update (calendarUpdate)

Request fields:
  --cal-id string (required) — Calendar ID.
  --cal-name string — New calendar name. (1-39 chars)
  --description string — New description. (≤499 chars)
  --extra-cal-ids []string — Additional public-holiday calendar IDs to inherit events from.
  --team-id int — New owning team ID.
  --timezone string — New IANA timezone.
  --workdays []int — Workday numbers (0 = Sunday, 6 = Saturday).
`,
		Example: `  flashduty calendar update --data '{"cal_id":"cal.QiNvtdKs4Wj52kZhT3LafM","cal_name":"Production On-Call Calendar (Updated)","timezone":"America/New_York","workdays":[1,2,3,4,5]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("cal-id") {
						body["cal_id"] = fCalID
					}
					if cmd.Flags().Changed("cal-name") {
						body["cal_name"] = fCalName
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("extra-cal-ids") {
						body["extra_cal_ids"] = fExtraCalIDs
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("timezone") {
						body["timezone"] = fTimezone
					}
					if cmd.Flags().Changed("workdays") {
						body["workdays"] = fWorkdays
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CalendarUpdateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.Calendars.CalendarUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /calendar/update")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&fCalID, "cal-id", "", "Calendar ID. (required)")
	cmd.Flags().StringVar(&fCalName, "cal-name", "", "New calendar name. (1-39 chars)")
	cmd.Flags().StringVar(&fDescription, "description", "", "New description. (≤499 chars)")
	cmd.Flags().StringSliceVar(&fExtraCalIDs, "extra-cal-ids", nil, "Additional public-holiday calendar IDs to inherit events from.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "New owning team ID.")
	cmd.Flags().StringVar(&fTimezone, "timezone", "", "New IANA timezone.")
	cmd.Flags().IntSliceVar(&fWorkdays, "workdays", nil, "Workday numbers (0 = Sunday, 6 = Saturday).")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedCalendars(root *cobra.Command) {
	gCalendar := genGroup(root, "calendar", "On-call/Calendars API")
	genAddLeaf(gCalendar, genCalendarsCalEventDeleteCmd())
	genAddLeaf(gCalendar, genCalendarsCalEventListCmd())
	genAddLeaf(gCalendar, genCalendarsCalEventUpsertCmd())
	genAddLeaf(gCalendar, genCalendarsCalendarCreateCmd())
	genAddLeaf(gCalendar, genCalendarsCalendarDeleteCmd())
	genAddLeaf(gCalendar, genCalendarsCalendarInfoCmd())
	genAddLeaf(gCalendar, genCalendarsCalendarListCmd())
	genAddLeaf(gCalendar, genCalendarsCalendarUpdateCmd())
}
