// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genRuleSetsCreateCmd() *cobra.Command {
	var dataJSON string
	var fNote string
	var fOpenFlag int64
	var fPayload string
	var fTypeIdent string
	cmd := &cobra.Command{
		Use:   "store-ruleset-create",
		Short: "Create ruleset",
		Long: `Create ruleset.

Create a new ruleset in the rule repository.

API: POST /monit/store/ruleset/create (monit-store-ruleset-create)

Request fields:
  --note string (required) — Description or title of the ruleset.
  --open-flag int — Sharing scope. '0' = private (creator only), '1' = account-shared, '2' = public. Defaults to '0' if omitted.
  --payload string (required) — JSON string containing the alert rule definitions.
  --type-ident string (required) — Datasource type identifier this ruleset applies to, e.g. 'prometheus'.

Response fields (under 'data'):
  - created_at (integer) (required) — Creation timestamp, Unix epoch seconds.
  - creator_account_id (integer) (required) — Account ID of the creator.
  - creator_id (integer) (required) — Member ID of the creator.
  - creator_name (string) (required) — Display name of the creator.
  - id (integer) (required) — Ruleset ID.
  - note (string) (required) — Description or title of the ruleset.
  - open_flag (integer) (required) — Sharing scope. '0' = private (creator only), '1' = account-shared, '2' = public.
  - payload (string) — JSON string containing the alert rule definitions. Omitted in list responses.
  - type_ident (string) (required) — Datasource type identifier this ruleset applies to.
  - updated_at (integer) (required) — Last update timestamp, Unix epoch seconds.
`,
		Example: `  flashduty monit store-ruleset-create --data '{"note":"CPU usage alerts","open_flag":1,"payload":"[{\"prom_ql\":\"rate(cpu_usage[5m]) \u003e 0.8\"}]","type_ident":"prometheus"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("note") {
						body["note"] = fNote
					}
					if cmd.Flags().Changed("open-flag") {
						body["open_flag"] = fOpenFlag
					}
					if cmd.Flags().Changed("payload") {
						body["payload"] = fPayload
					}
					if cmd.Flags().Changed("type-ident") {
						body["type_ident"] = fTypeIdent
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.StoreRulesetUpsertRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.RuleSets.Create(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fNote, "note", "", "Description or title of the ruleset. (required)")
	cmd.Flags().Int64Var(&fOpenFlag, "open-flag", 0, "Sharing scope. '0' = private (creator only), '1' = account-shared, '2' = public. Defaults to '0' if omitted.")
	cmd.Flags().StringVar(&fPayload, "payload", "", "JSON string containing the alert rule definitions. (required)")
	cmd.Flags().StringVar(&fTypeIdent, "type-ident", "", "Datasource type identifier this ruleset applies to, e.g. 'prometheus'. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genRuleSetsDeleteCmd() *cobra.Command {
	var dataJSON string
	var fID int64
	cmd := &cobra.Command{
		Use:   "store-ruleset-delete",
		Short: "Delete ruleset",
		Long: `Delete ruleset.

Delete a ruleset from the rule repository by ID.

API: POST /monit/store/ruleset/delete (monit-store-ruleset-delete)

Request fields:
  --id int (required) — Resource ID.
`,
		Example: `  flashduty monit store-ruleset-delete --data '{"id":1}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("id") {
						body["id"] = fID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.IDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.RuleSets.Delete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /monit/store/ruleset/delete")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fID, "id", 0, "Resource ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genRuleSetsInfoCmd() *cobra.Command {
	var dataJSON string
	var fID int64
	cmd := &cobra.Command{
		Use:   "store-ruleset-info",
		Short: "Get ruleset detail",
		Long: `Get ruleset detail.

Retrieve the full details of a ruleset including its 'payload' (the alert rule definitions as a JSON string).

API: POST /monit/store/ruleset/info (monit-store-ruleset-info)

Request fields:
  --id int (required) — Resource ID.

Response fields (under 'data'):
  - created_at (integer) (required) — Creation timestamp, Unix epoch seconds.
  - creator_account_id (integer) (required) — Account ID of the creator.
  - creator_id (integer) (required) — Member ID of the creator.
  - creator_name (string) (required) — Display name of the creator.
  - id (integer) (required) — Ruleset ID.
  - note (string) (required) — Description or title of the ruleset.
  - open_flag (integer) (required) — Sharing scope. '0' = private (creator only), '1' = account-shared, '2' = public.
  - payload (string) — JSON string containing the alert rule definitions. Omitted in list responses.
  - type_ident (string) (required) — Datasource type identifier this ruleset applies to.
  - updated_at (integer) (required) — Last update timestamp, Unix epoch seconds.
`,
		Example: `  flashduty monit store-ruleset-info --data '{"id":1}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("id") {
						body["id"] = fID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.IDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.RuleSets.Info(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fID, "id", 0, "Resource ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genRuleSetsListCmd() *cobra.Command {
	var dataJSON string
	var fTypeIdent string
	cmd := &cobra.Command{
		Use:   "store-ruleset-list",
		Short: "List rulesets",
		Long: `List rulesets.

Return all rulesets for a given datasource type that are accessible to the current user.

API: POST /monit/store/ruleset/list (monit-store-ruleset-list)

Request fields:
  --type-ident string (required) — Datasource type identifier to filter by, e.g. 'prometheus'.
`,
		Example: `  flashduty monit store-ruleset-list --data '{"type_ident":"prometheus"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("type-ident") {
						body["type_ident"] = fTypeIdent
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.StoreRulesetListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.RuleSets.List(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fTypeIdent, "type-ident", "", "Datasource type identifier to filter by, e.g. 'prometheus'. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genRuleSetsUpdateCmd() *cobra.Command {
	var dataJSON string
	var fID int64
	var fNote string
	var fOpenFlag int64
	var fPayload string
	cmd := &cobra.Command{
		Use:   "store-ruleset-update",
		Short: "Update ruleset",
		Long: `Update ruleset.

Update the note, sharing flag, and payload of an existing ruleset.

API: POST /monit/store/ruleset/update (monit-store-ruleset-update)

Request fields:
  --id int (required) — Ruleset ID to update.
  --note string (required) — New description.
  --open-flag int — New sharing scope. '0' = private, '1' = account-shared, '2' = public.
  --payload string (required) — New JSON string of alert rule definitions.

Response fields (under 'data'):
  - created_at (integer) (required) — Creation timestamp, Unix epoch seconds.
  - creator_account_id (integer) (required) — Account ID of the creator.
  - creator_id (integer) (required) — Member ID of the creator.
  - creator_name (string) (required) — Display name of the creator.
  - id (integer) (required) — Ruleset ID.
  - note (string) (required) — Description or title of the ruleset.
  - open_flag (integer) (required) — Sharing scope. '0' = private (creator only), '1' = account-shared, '2' = public.
  - payload (string) — JSON string containing the alert rule definitions. Omitted in list responses.
  - type_ident (string) (required) — Datasource type identifier this ruleset applies to.
  - updated_at (integer) (required) — Last update timestamp, Unix epoch seconds.
`,
		Example: `  flashduty monit store-ruleset-update --data '{"id":1,"note":"Updated CPU alerts","open_flag":2,"payload":"[{\"prom_ql\":\"rate(cpu_usage[5m]) \u003e 0.9\"}]"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("id") {
						body["id"] = fID
					}
					if cmd.Flags().Changed("note") {
						body["note"] = fNote
					}
					if cmd.Flags().Changed("open-flag") {
						body["open_flag"] = fOpenFlag
					}
					if cmd.Flags().Changed("payload") {
						body["payload"] = fPayload
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.StoreRulesetUpdateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.RuleSets.Update(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fID, "id", 0, "Ruleset ID to update. (required)")
	cmd.Flags().StringVar(&fNote, "note", "", "New description. (required)")
	cmd.Flags().Int64Var(&fOpenFlag, "open-flag", 0, "New sharing scope. '0' = private, '1' = account-shared, '2' = public.")
	cmd.Flags().StringVar(&fPayload, "payload", "", "New JSON string of alert rule definitions. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func registerGeneratedRuleSets(root *cobra.Command) {
	gMonit := genGroup(root, "monit", "Monitors API")
	genAddLeaf(gMonit, genRuleSetsCreateCmd())
	genAddLeaf(gMonit, genRuleSetsDeleteCmd())
	genAddLeaf(gMonit, genRuleSetsInfoCmd())
	genAddLeaf(gMonit, genRuleSetsListCmd())
	genAddLeaf(gMonit, genRuleSetsUpdateCmd())
}
