// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genMonitorUtilitiesSyncCmd() *cobra.Command {
	var dataJSON string
	var fDelaySeconds int64
	var fDsName string
	var fDsType string
	var fExpr string
	cmd := &cobra.Command{
		Use:   "preview-sync",
		Short: "Preview datasource query",
		Long: `Preview datasource query.

Execute a synchronous datasource query and return the raw result. Used to preview alert rule expressions before saving.

API: POST /monit/preview/sync (monit-preview-sync)

Request fields:
  --delay-seconds int — Shift the query window backward by this many seconds to compensate for data ingestion latency.
  --ds-name string (required) — Datasource display name as configured in the account.
  --ds-type string (required) — Datasource type, e.g. 'prometheus', 'loki', 'elasticsearch'.
  --expr string (required) — Query expression. Format depends on 'ds_type' (PromQL for Prometheus, LogQL for Loki, etc.).
  args (object, via --data) — Additional type-specific query arguments.
`,
		Example: `  flashduty monit preview-sync --data '{"delay_seconds":0,"ds_name":"Prometheus Prod","ds_type":"prometheus","expr":"rate(http_requests_total[5m])"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("delay-seconds") {
						body["delay_seconds"] = fDelaySeconds
					}
					if cmd.Flags().Changed("ds-name") {
						body["ds_name"] = fDsName
					}
					if cmd.Flags().Changed("ds-type") {
						body["ds_type"] = fDsType
					}
					if cmd.Flags().Changed("expr") {
						body["expr"] = fExpr
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.PreviewSyncRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				resp, err := ctx.Client.MonitorUtilities.Sync(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				if resp != nil && len(resp.Raw) > 0 {
					return ctx.WriteRaw(resp.Raw)
				}
				ctx.WriteResult("OK: POST /monit/preview/sync")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fDelaySeconds, "delay-seconds", 0, "Shift the query window backward by this many seconds to compensate for data ingestion latency.")
	cmd.Flags().StringVar(&fDsName, "ds-name", "", "Datasource display name as configured in the account. (required)")
	cmd.Flags().StringVar(&fDsType, "ds-type", "", "Datasource type, e.g. 'prometheus', 'loki', 'elasticsearch'. (required)")
	cmd.Flags().StringVar(&fExpr, "expr", "", "Query expression. Format depends on 'ds_type' (PromQL for Prometheus, LogQL for Loki, etc.). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedMonitorUtilities(root *cobra.Command) {
	gMonit := genGroup(root, "monit", "Monitors API")
	genAddLeaf(gMonit, genMonitorUtilitiesSyncCmd())
}
