// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import "github.com/spf13/cobra"

func genAccountInfoCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "info",
		Short: "Get account detail",
		Long: `Get account detail.

Return the current account's profile and settings.

API: POST /account/info (account-read-info)
`,
		Example: `  flashduty account info --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				out, _, err := ctx.Client.Account.Info(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func registerGeneratedAccount(root *cobra.Command) {
	gAccount := genGroup(root, "account", "Platform/Account API")
	genAddLeaf(gAccount, genAccountInfoCmd())
}
