// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genSourcemapsListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fAsc bool
	var fBuildID string
	var fEndTime int64
	var fOrderby string
	var fQuery string
	var fServices []string
	var fStartTime int64
	var fType string
	var fUuid string
	var fVersions []string
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List sourcemaps",
		Long: `List sourcemaps.

Return a paginated list of uploaded sourcemap files filtered by platform type, service, and version.

API: POST /sourcemap/list (sourcemap-read-list)

Request fields:
  --p int — Page number, starting at 1.
  --limit int — Page size. Maximum 100. Default 20.
  --search-after-ctx string
  --asc bool — Sort ascending. Default false (descending).
  --build-id string — Android only. Filter by Gradle plugin build identifier. Max 200 characters.
  --end-time int (required) — End of upload time range, Unix epoch milliseconds. Maximum window: 365 days.
  --orderby string — Sort field. [created_at, updated_at]
  --query string — Substring match on the minified URL (browser) or build ID (android). Max 200 characters.
  --services []string — Filter by service names. Up to 100 values.
  --start-time int (required) — Start of upload time range, Unix epoch milliseconds. Must be > 0 and before 'end_time'.
  --type string — Platform type. Defaults to 'browser' when omitted. [browser, android, ios]
  --uuid string — iOS only. Filter by dSYM bundle UUID. Max 200 characters.
  --versions []string — Filter by version strings. Up to 100 values.
`,
		Example: `  flashduty sourcemap list --data '{"end_time":1712700000000,"limit":20,"p":1,"services":["my-web-app"],"start_time":1712000000000,"type":"browser"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("p") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("asc") {
						body["asc"] = fAsc
					}
					if cmd.Flags().Changed("build-id") {
						body["build_id"] = fBuildID
					}
					if cmd.Flags().Changed("end-time") {
						body["end_time"] = fEndTime
					}
					if cmd.Flags().Changed("orderby") {
						body["orderby"] = fOrderby
					}
					if cmd.Flags().Changed("query") {
						body["query"] = fQuery
					}
					if cmd.Flags().Changed("services") {
						body["services"] = fServices
					}
					if cmd.Flags().Changed("start-time") {
						body["start_time"] = fStartTime
					}
					if cmd.Flags().Changed("type") {
						body["type"] = fType
					}
					if cmd.Flags().Changed("uuid") {
						body["uuid"] = fUuid
					}
					if cmd.Flags().Changed("versions") {
						body["versions"] = fVersions
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.SourcemapListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Sourcemaps.List(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "p", 0, "Page number, starting at 1.")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size. Maximum 100. Default 20.")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().BoolVar(&fAsc, "asc", false, "Sort ascending. Default false (descending).")
	cmd.Flags().StringVar(&fBuildID, "build-id", "", "Android only. Filter by Gradle plugin build identifier. Max 200 characters.")
	cmd.Flags().Int64Var(&fEndTime, "end-time", 0, "End of upload time range, Unix epoch milliseconds. Maximum window: 365 days. (required)")
	cmd.Flags().StringVar(&fOrderby, "orderby", "", "Sort field. [created_at, updated_at]")
	cmd.Flags().StringVar(&fQuery, "query", "", "Substring match on the minified URL (browser) or build ID (android). Max 200 characters.")
	cmd.Flags().StringSliceVar(&fServices, "services", nil, "Filter by service names. Up to 100 values.")
	cmd.Flags().Int64Var(&fStartTime, "start-time", 0, "Start of upload time range, Unix epoch milliseconds. Must be > 0 and before `end_time`. (required)")
	cmd.Flags().StringVar(&fType, "type", "", "Platform type. Defaults to `browser` when omitted. [browser, android, ios]")
	cmd.Flags().StringVar(&fUuid, "uuid", "", "iOS only. Filter by dSYM bundle UUID. Max 200 characters.")
	cmd.Flags().StringSliceVar(&fVersions, "versions", nil, "Filter by version strings. Up to 100 values.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func registerGeneratedSourcemaps(root *cobra.Command) {
	gSourcemap := genGroup(root, "sourcemap", "RUM/Sourcemaps API")
	genAddLeaf(gSourcemap, genSourcemapsListCmd())
}
