// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genMcpServersReadServerGetCmd() *cobra.Command {
	var dataJSON string
	var fServerID string
	cmd := &cobra.Command{
		Use:   "mcp-server-get <server-id>",
		Short: "Get MCP server detail",
		Long: `Get MCP server detail.

Get one MCP server and run a live probe of its tool list.

API: POST /safari/mcp/server/get (mcp-read-server-get)

Request fields:
  --server-id string (required) — Target MCP server ID.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) (required) — Owning account ID.
  - ai_description (string) — LLM-generated description, preferred over 'description' when present.
  - args (array<string>) — Command arguments (stdio transport).
  - auth_mode (string) — Authentication mode. [shared, per_user_secret, per_user_oauth]
  - call_timeout (integer) (required) — Tool-call timeout in seconds (0 = server default, 60s).
  - can_edit (boolean) (required) — Whether the caller may edit this server.
  - command (string) — Executable command (stdio transport only).
  - connect_timeout (integer) (required) — Connection timeout in seconds (0 = server default, 10s).
  - created_at (integer) (required) — Creation time. Unix timestamp in milliseconds.
  - created_by (integer) (required) — Member ID that created the server.
  - description (string) (required) — Server description.
  - env (object) — Environment variables (stdio transport). Secret values are masked.
  - headers (object) — HTTP headers (sse / streamable-http). Secret values are masked.
  - list_error (string) — Error message when the live tool list failed.
  - oauth_metadata (string) — JSON-encoded OAuth metadata (per_user_oauth mode).
  - proxy_url (string) — Outbound proxy URL used to reach the server.
  - secret_schema (string) — JSON-encoded secret schema (per_user_secret mode).
  - server_id (string) (required) — Unique MCP server ID (prefix 'mcp_').
  - server_name (string) (required) — MCP server name, unique within the account.
  - source_template_name (string) — Marketplace template this connector was installed from; empty for user-authored.
  - status (string) (required) — Server status. [enabled, disabled]
  - team_id (integer) (required) — Team scope: 0 = account-wide; >0 = the owning team.
  - tool_count (integer) — Number of tools in the live list.
  - tools (array<object>) — Live tool list; populated by the get/test endpoints.
    - description (string) (required) — Tool description.
    - input_schema (object) — JSON Schema describing the tool's input parameters.
    - name (string) (required) — Tool name.
  - transport (string) (required) — Transport protocol. [stdio, sse, streamable-http]
  - updated_at (integer) (required) — Last update time. Unix timestamp in milliseconds.
  - url (string) — Server URL (sse / streamable-http transport).
`,
		Args:    requireExactArg("server_id"),
		Example: `  flashduty safari mcp-server-get --data '{"server_id":"mcp_4kP9wQ2nLceRtY7uVb3xA1"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "server_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("server-id") {
						body["server_id"] = fServerID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.McpServerGetRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.McpServers.ReadServerGet(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fServerID, "server-id", "", "Target MCP server ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMcpServersReadServerListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fIncludeAccount bool
	var fTeamIDs []int
	cmd := &cobra.Command{
		Use:   "mcp-server-list",
		Short: "List MCP servers",
		Long: `List MCP servers.

List MCP servers visible to the caller across account and team scopes, with pagination.

API: POST /safari/mcp/server/list (mcp-read-server-list)

Request fields:
  --page int — Page number, 1-based.
  --limit int — Page size.
  --search-after-ctx string
  --include-account bool — Include account-scoped (team_id=0) rows. Defaults to true.
  --team-ids []int — Filter to these team IDs; empty = the caller's visible set.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - servers (array<object>) (required) — MCP servers on this page.
    - account_id (integer) (required) — Owning account ID.
    - ai_description (string) — LLM-generated description, preferred over 'description' when present.
    - args (array<string>) — Command arguments (stdio transport).
    - auth_mode (string) — Authentication mode. [shared, per_user_secret, per_user_oauth]
    - call_timeout (integer) (required) — Tool-call timeout in seconds (0 = server default, 60s).
    - can_edit (boolean) (required) — Whether the caller may edit this server.
    - command (string) — Executable command (stdio transport only).
    - connect_timeout (integer) (required) — Connection timeout in seconds (0 = server default, 10s).
    - created_at (integer) (required) — Creation time. Unix timestamp in milliseconds.
    - created_by (integer) (required) — Member ID that created the server.
    - description (string) (required) — Server description.
    - env (object) — Environment variables (stdio transport). Secret values are masked.
    - headers (object) — HTTP headers (sse / streamable-http). Secret values are masked.
    - list_error (string) — Error message when the live tool list failed.
    - oauth_metadata (string) — JSON-encoded OAuth metadata (per_user_oauth mode).
    - proxy_url (string) — Outbound proxy URL used to reach the server.
    - secret_schema (string) — JSON-encoded secret schema (per_user_secret mode).
    - server_id (string) (required) — Unique MCP server ID (prefix 'mcp_').
    - server_name (string) (required) — MCP server name, unique within the account.
    - source_template_name (string) — Marketplace template this connector was installed from; empty for user-authored.
    - status (string) (required) — Server status. [enabled, disabled]
    - team_id (integer) (required) — Team scope: 0 = account-wide; >0 = the owning team.
    - tool_count (integer) — Number of tools in the live list.
    - tools (array<object>) — Live tool list; populated by the get/test endpoints.
      - description (string) (required) — Tool description.
      - input_schema (object) — JSON Schema describing the tool's input parameters.
      - name (string) (required) — Tool name.
    - transport (string) (required) — Transport protocol. [stdio, sse, streamable-http]
    - updated_at (integer) (required) — Last update time. Unix timestamp in milliseconds.
    - url (string) — Server URL (sse / streamable-http transport).
  - total (integer) (required) — Total number of matching servers.
`,
		Example: `  flashduty safari mcp-server-list --data '{"include_account":true,"limit":20,"p":1}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("page") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("include-account") {
						body["include_account"] = fIncludeAccount
					}
					if cmd.Flags().Changed("team-ids") {
						body["team_ids"] = fTeamIDs
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.McpServerListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.McpServers.ReadServerList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "page", 0, "Page number, 1-based.")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size.")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().BoolVar(&fIncludeAccount, "include-account", false, "Include account-scoped (team_id=0) rows. Defaults to true.")
	cmd.Flags().IntSliceVar(&fTeamIDs, "team-ids", nil, "Filter to these team IDs; empty = the caller's visible set.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMcpServersWriteServerCreateCmd() *cobra.Command {
	var dataJSON string
	var fArgs []string
	var fAuthMode string
	var fCallTimeout int64
	var fCommand string
	var fConnectTimeout int64
	var fDescription string
	var fOauthMetadata string
	var fSecretSchema string
	var fServerName string
	var fSourceTemplateName string
	var fStatus string
	var fTeamID int64
	var fTransport string
	var fURL string
	cmd := &cobra.Command{
		Use:   "mcp-server-create",
		Short: "Create MCP server",
		Long: `Create MCP server.

Register a new MCP server (connector) on the account.

API: POST /safari/mcp/server/create (mcp-write-server-create)

Request fields:
  --args []string — Command arguments (stdio transport).
  --auth-mode string — Authentication mode: shared (default), per_user_secret, or per_user_oauth.
  --call-timeout int — Tool-call timeout in seconds. 0 = default (60s).
  --command string — Executable command (stdio transport).
  --connect-timeout int — Connection timeout in seconds. 0 = default (10s).
  --description string (required) — Server description. (1-1024 chars)
  --oauth-metadata string — JSON OAuth metadata; reserved for per_user_oauth.
  --secret-schema string — JSON secret schema; required when auth_mode=per_user_secret.
  --server-name string (required) — MCP server name, unique within the account. (1-255 chars)
  --source-template-name string — Marketplace template name when created from a connector template.
  --status string — Initial status. [enabled, disabled]
  --team-id int — Team scope: 0 = account-wide; >0 = team.
  --transport string (required) — Transport protocol. [stdio, sse, streamable-http]
  --url string — Server URL (sse / streamable-http transport).
  env (object, via --data) — Environment variables (stdio transport).
  headers (object, via --data) — HTTP headers (sse / streamable-http).

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) (required) — Owning account ID.
  - ai_description (string) — LLM-generated description, preferred over 'description' when present.
  - args (array<string>) — Command arguments (stdio transport).
  - auth_mode (string) — Authentication mode. [shared, per_user_secret, per_user_oauth]
  - call_timeout (integer) (required) — Tool-call timeout in seconds (0 = server default, 60s).
  - can_edit (boolean) (required) — Whether the caller may edit this server.
  - command (string) — Executable command (stdio transport only).
  - connect_timeout (integer) (required) — Connection timeout in seconds (0 = server default, 10s).
  - created_at (integer) (required) — Creation time. Unix timestamp in milliseconds.
  - created_by (integer) (required) — Member ID that created the server.
  - description (string) (required) — Server description.
  - env (object) — Environment variables (stdio transport). Secret values are masked.
  - headers (object) — HTTP headers (sse / streamable-http). Secret values are masked.
  - list_error (string) — Error message when the live tool list failed.
  - oauth_metadata (string) — JSON-encoded OAuth metadata (per_user_oauth mode).
  - proxy_url (string) — Outbound proxy URL used to reach the server.
  - secret_schema (string) — JSON-encoded secret schema (per_user_secret mode).
  - server_id (string) (required) — Unique MCP server ID (prefix 'mcp_').
  - server_name (string) (required) — MCP server name, unique within the account.
  - source_template_name (string) — Marketplace template this connector was installed from; empty for user-authored.
  - status (string) (required) — Server status. [enabled, disabled]
  - team_id (integer) (required) — Team scope: 0 = account-wide; >0 = the owning team.
  - tool_count (integer) — Number of tools in the live list.
  - tools (array<object>) — Live tool list; populated by the get/test endpoints.
    - description (string) (required) — Tool description.
    - input_schema (object) — JSON Schema describing the tool's input parameters.
    - name (string) (required) — Tool name.
  - transport (string) (required) — Transport protocol. [stdio, sse, streamable-http]
  - updated_at (integer) (required) — Last update time. Unix timestamp in milliseconds.
  - url (string) — Server URL (sse / streamable-http transport).
`,
		Example: `  flashduty safari mcp-server-create --data '{"description":"Query Prometheus metrics and alerts.","server_name":"prometheus","status":"enabled","transport":"streamable-http","url":"https://mcp.example.com/prometheus"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("args") {
						body["args"] = fArgs
					}
					if cmd.Flags().Changed("auth-mode") {
						body["auth_mode"] = fAuthMode
					}
					if cmd.Flags().Changed("call-timeout") {
						body["call_timeout"] = fCallTimeout
					}
					if cmd.Flags().Changed("command") {
						body["command"] = fCommand
					}
					if cmd.Flags().Changed("connect-timeout") {
						body["connect_timeout"] = fConnectTimeout
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("oauth-metadata") {
						body["oauth_metadata"] = fOauthMetadata
					}
					if cmd.Flags().Changed("secret-schema") {
						body["secret_schema"] = fSecretSchema
					}
					if cmd.Flags().Changed("server-name") {
						body["server_name"] = fServerName
					}
					if cmd.Flags().Changed("source-template-name") {
						body["source_template_name"] = fSourceTemplateName
					}
					if cmd.Flags().Changed("status") {
						body["status"] = fStatus
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("transport") {
						body["transport"] = fTransport
					}
					if cmd.Flags().Changed("url") {
						body["url"] = fURL
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.McpServerCreateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.McpServers.WriteServerCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringSliceVar(&fArgs, "args", nil, "Command arguments (stdio transport).")
	cmd.Flags().StringVar(&fAuthMode, "auth-mode", "", "Authentication mode: shared (default), per_user_secret, or per_user_oauth.")
	cmd.Flags().Int64Var(&fCallTimeout, "call-timeout", 0, "Tool-call timeout in seconds. 0 = default (60s).")
	cmd.Flags().StringVar(&fCommand, "command", "", "Executable command (stdio transport).")
	cmd.Flags().Int64Var(&fConnectTimeout, "connect-timeout", 0, "Connection timeout in seconds. 0 = default (10s).")
	cmd.Flags().StringVar(&fDescription, "description", "", "Server description. (required) (1-1024 chars)")
	cmd.Flags().StringVar(&fOauthMetadata, "oauth-metadata", "", "JSON OAuth metadata; reserved for per_user_oauth.")
	cmd.Flags().StringVar(&fSecretSchema, "secret-schema", "", "JSON secret schema; required when auth_mode=per_user_secret.")
	cmd.Flags().StringVar(&fServerName, "server-name", "", "MCP server name, unique within the account. (required) (1-255 chars)")
	cmd.Flags().StringVar(&fSourceTemplateName, "source-template-name", "", "Marketplace template name when created from a connector template.")
	cmd.Flags().StringVar(&fStatus, "status", "", "Initial status. [enabled, disabled]")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Team scope: 0 = account-wide; >0 = team.")
	cmd.Flags().StringVar(&fTransport, "transport", "", "Transport protocol. (required) [stdio, sse, streamable-http]")
	cmd.Flags().StringVar(&fURL, "url", "", "Server URL (sse / streamable-http transport).")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMcpServersWriteServerDeleteCmd() *cobra.Command {
	var dataJSON string
	var fServerID string
	cmd := &cobra.Command{
		Use:   "mcp-server-delete <server-id>",
		Short: "Delete MCP server",
		Long: `Delete MCP server.

Delete an MCP server by ID.

API: POST /safari/mcp/server/delete (mcp-write-server-delete)

Request fields:
  --server-id string (required) — Target MCP server ID.
`,
		Args:    requireExactArg("server_id"),
		Example: `  flashduty safari mcp-server-delete --data '{"server_id":"mcp_4kP9wQ2nLceRtY7uVb3xA1"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "server_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("server-id") {
						body["server_id"] = fServerID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.McpServerDeleteRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.McpServers.WriteServerDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fServerID, "server-id", "", "Target MCP server ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMcpServersWriteServerDisableCmd() *cobra.Command {
	var dataJSON string
	var fServerID string
	cmd := &cobra.Command{
		Use:   "mcp-server-disable <server-id>",
		Short: "Disable MCP server",
		Long: `Disable MCP server.

Disable an enabled MCP server.

API: POST /safari/mcp/server/disable (mcp-write-server-disable)

Request fields:
  --server-id string (required) — Target MCP server ID.
`,
		Args:    requireExactArg("server_id"),
		Example: `  flashduty safari mcp-server-disable --data '{"server_id":"mcp_4kP9wQ2nLceRtY7uVb3xA1"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "server_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("server-id") {
						body["server_id"] = fServerID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.McpServerStatusRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.McpServers.WriteServerDisable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fServerID, "server-id", "", "Target MCP server ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMcpServersWriteServerEnableCmd() *cobra.Command {
	var dataJSON string
	var fServerID string
	cmd := &cobra.Command{
		Use:   "mcp-server-enable <server-id>",
		Short: "Enable MCP server",
		Long: `Enable MCP server.

Enable a disabled MCP server.

API: POST /safari/mcp/server/enable (mcp-write-server-enable)

Request fields:
  --server-id string (required) — Target MCP server ID.
`,
		Args:    requireExactArg("server_id"),
		Example: `  flashduty safari mcp-server-enable --data '{"server_id":"mcp_4kP9wQ2nLceRtY7uVb3xA1"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "server_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("server-id") {
						body["server_id"] = fServerID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.McpServerStatusRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.McpServers.WriteServerEnable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fServerID, "server-id", "", "Target MCP server ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genMcpServersWriteServerUpdateCmd() *cobra.Command {
	var dataJSON string
	var fArgs []string
	var fAuthMode string
	var fCallTimeout int64
	var fCommand string
	var fConnectTimeout int64
	var fDescription string
	var fOauthMetadata string
	var fSecretSchema string
	var fServerID string
	var fServerName string
	var fTeamID int64
	var fTransport string
	var fURL string
	cmd := &cobra.Command{
		Use:   "mcp-server-update <server-id>",
		Short: "Update MCP server",
		Long: `Update MCP server.

Update an MCP server's configuration. Omit a field to leave it unchanged.

API: POST /safari/mcp/server/update (mcp-write-server-update)

Request fields:
  --args []string — Command arguments (stdio transport).
  --auth-mode string — Authentication mode: shared (default), per_user_secret, or per_user_oauth.
  --call-timeout int — Tool-call timeout in seconds. 0 = default (60s).
  --command string — Executable command (stdio transport).
  --connect-timeout int — Connection timeout in seconds. 0 = default (10s).
  --description string — New description. (1-1024 chars)
  --oauth-metadata string — JSON OAuth metadata; reserved for per_user_oauth.
  --secret-schema string — JSON secret schema; required when auth_mode=per_user_secret.
  --server-id string (required) — Target MCP server ID.
  --server-name string — New name. (1-255 chars)
  --team-id int — Reassign team scope: 0 = account-wide; >0 = team. Omit to leave unchanged.
  --transport string — Transport protocol. [stdio, sse, streamable-http]
  --url string — Server URL (sse / streamable-http transport).
  env (object, via --data) — Environment variables (stdio transport).
  headers (object, via --data) — HTTP headers (sse / streamable-http).

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) (required) — Owning account ID.
  - ai_description (string) — LLM-generated description, preferred over 'description' when present.
  - args (array<string>) — Command arguments (stdio transport).
  - auth_mode (string) — Authentication mode. [shared, per_user_secret, per_user_oauth]
  - call_timeout (integer) (required) — Tool-call timeout in seconds (0 = server default, 60s).
  - can_edit (boolean) (required) — Whether the caller may edit this server.
  - command (string) — Executable command (stdio transport only).
  - connect_timeout (integer) (required) — Connection timeout in seconds (0 = server default, 10s).
  - created_at (integer) (required) — Creation time. Unix timestamp in milliseconds.
  - created_by (integer) (required) — Member ID that created the server.
  - description (string) (required) — Server description.
  - env (object) — Environment variables (stdio transport). Secret values are masked.
  - headers (object) — HTTP headers (sse / streamable-http). Secret values are masked.
  - list_error (string) — Error message when the live tool list failed.
  - oauth_metadata (string) — JSON-encoded OAuth metadata (per_user_oauth mode).
  - proxy_url (string) — Outbound proxy URL used to reach the server.
  - secret_schema (string) — JSON-encoded secret schema (per_user_secret mode).
  - server_id (string) (required) — Unique MCP server ID (prefix 'mcp_').
  - server_name (string) (required) — MCP server name, unique within the account.
  - source_template_name (string) — Marketplace template this connector was installed from; empty for user-authored.
  - status (string) (required) — Server status. [enabled, disabled]
  - team_id (integer) (required) — Team scope: 0 = account-wide; >0 = the owning team.
  - tool_count (integer) — Number of tools in the live list.
  - tools (array<object>) — Live tool list; populated by the get/test endpoints.
    - description (string) (required) — Tool description.
    - input_schema (object) — JSON Schema describing the tool's input parameters.
    - name (string) (required) — Tool name.
  - transport (string) (required) — Transport protocol. [stdio, sse, streamable-http]
  - updated_at (integer) (required) — Last update time. Unix timestamp in milliseconds.
  - url (string) — Server URL (sse / streamable-http transport).
`,
		Args:    requireExactArg("server_id"),
		Example: `  flashduty safari mcp-server-update --data '{"description":"Query Prometheus metrics, alerts, and rules.","server_id":"mcp_4kP9wQ2nLceRtY7uVb3xA1"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "server_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("args") {
						body["args"] = fArgs
					}
					if cmd.Flags().Changed("auth-mode") {
						body["auth_mode"] = fAuthMode
					}
					if cmd.Flags().Changed("call-timeout") {
						body["call_timeout"] = fCallTimeout
					}
					if cmd.Flags().Changed("command") {
						body["command"] = fCommand
					}
					if cmd.Flags().Changed("connect-timeout") {
						body["connect_timeout"] = fConnectTimeout
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("oauth-metadata") {
						body["oauth_metadata"] = fOauthMetadata
					}
					if cmd.Flags().Changed("secret-schema") {
						body["secret_schema"] = fSecretSchema
					}
					if cmd.Flags().Changed("server-id") {
						body["server_id"] = fServerID
					}
					if cmd.Flags().Changed("server-name") {
						body["server_name"] = fServerName
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("transport") {
						body["transport"] = fTransport
					}
					if cmd.Flags().Changed("url") {
						body["url"] = fURL
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.McpServerUpdateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.McpServers.WriteServerUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringSliceVar(&fArgs, "args", nil, "Command arguments (stdio transport).")
	cmd.Flags().StringVar(&fAuthMode, "auth-mode", "", "Authentication mode: shared (default), per_user_secret, or per_user_oauth.")
	cmd.Flags().Int64Var(&fCallTimeout, "call-timeout", 0, "Tool-call timeout in seconds. 0 = default (60s).")
	cmd.Flags().StringVar(&fCommand, "command", "", "Executable command (stdio transport).")
	cmd.Flags().Int64Var(&fConnectTimeout, "connect-timeout", 0, "Connection timeout in seconds. 0 = default (10s).")
	cmd.Flags().StringVar(&fDescription, "description", "", "New description. (1-1024 chars)")
	cmd.Flags().StringVar(&fOauthMetadata, "oauth-metadata", "", "JSON OAuth metadata; reserved for per_user_oauth.")
	cmd.Flags().StringVar(&fSecretSchema, "secret-schema", "", "JSON secret schema; required when auth_mode=per_user_secret.")
	cmd.Flags().StringVar(&fServerID, "server-id", "", "Target MCP server ID. (required)")
	cmd.Flags().StringVar(&fServerName, "server-name", "", "New name. (1-255 chars)")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Reassign team scope: 0 = account-wide; >0 = team. Omit to leave unchanged.")
	cmd.Flags().StringVar(&fTransport, "transport", "", "Transport protocol. [stdio, sse, streamable-http]")
	cmd.Flags().StringVar(&fURL, "url", "", "Server URL (sse / streamable-http transport).")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedMcpServers(root *cobra.Command) {
	gSafari := genGroup(root, "safari", "AI SRE API")
	genAddLeaf(gSafari, genMcpServersReadServerGetCmd())
	genAddLeaf(gSafari, genMcpServersReadServerListCmd())
	genAddLeaf(gSafari, genMcpServersWriteServerCreateCmd())
	genAddLeaf(gSafari, genMcpServersWriteServerDeleteCmd())
	genAddLeaf(gSafari, genMcpServersWriteServerDisableCmd())
	genAddLeaf(gSafari, genMcpServersWriteServerEnableCmd())
	genAddLeaf(gSafari, genMcpServersWriteServerUpdateCmd())
}
