// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genChangesListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fAsc bool
	var fChannelIDs []int
	var fEndTime int64
	var fIncludeEvents bool
	var fIntegrationIDs []int
	var fOrderby string
	var fQuery string
	var fStartTime int64
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List changes",
		Long: `List changes.

Query change records within a time window, with filtering, search, and pagination.

API: POST /change/list (change-read-list)

Request fields:
  --p int — Page number, starting at 1.
  --limit int — Number of items per page.
  --search-after-ctx string
  --asc bool — Sort in ascending order when true.
  --channel-ids []int — Filter by collaboration channel IDs.
  --end-time int — Unix timestamp in seconds for the end of the query window.
  --include-events bool — Include the underlying change events for each change when true.
  --integration-ids []int — Filter by reporting integration IDs.
  --orderby string — Field to sort the result by. [start_time, last_time]
  --query string — Free-text or regular-expression search over change fields.
  --start-time int — Unix timestamp in seconds for the start of the query window.
`,
		Example: `  flashduty change list --data '{"asc":false,"end_time":1717046400,"include_events":false,"integration_ids":[362],"limit":10,"orderby":"start_time","p":1,"start_time":1716960000}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("p") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("asc") {
						body["asc"] = fAsc
					}
					if cmd.Flags().Changed("channel-ids") {
						body["channel_ids"] = fChannelIDs
					}
					if cmd.Flags().Changed("end-time") {
						body["end_time"] = fEndTime
					}
					if cmd.Flags().Changed("include-events") {
						body["include_events"] = fIncludeEvents
					}
					if cmd.Flags().Changed("integration-ids") {
						body["integration_ids"] = fIntegrationIDs
					}
					if cmd.Flags().Changed("orderby") {
						body["orderby"] = fOrderby
					}
					if cmd.Flags().Changed("query") {
						body["query"] = fQuery
					}
					if cmd.Flags().Changed("start-time") {
						body["start_time"] = fStartTime
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ListChangeRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Changes.List(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "p", 0, "Page number, starting at 1.")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Number of items per page.")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().BoolVar(&fAsc, "asc", false, "Sort in ascending order when true.")
	cmd.Flags().IntSliceVar(&fChannelIDs, "channel-ids", nil, "Filter by collaboration channel IDs.")
	cmd.Flags().Int64Var(&fEndTime, "end-time", 0, "Unix timestamp in seconds for the end of the query window.")
	cmd.Flags().BoolVar(&fIncludeEvents, "include-events", false, "Include the underlying change events for each change when true.")
	cmd.Flags().IntSliceVar(&fIntegrationIDs, "integration-ids", nil, "Filter by reporting integration IDs.")
	cmd.Flags().StringVar(&fOrderby, "orderby", "", "Field to sort the result by. [start_time, last_time]")
	cmd.Flags().StringVar(&fQuery, "query", "", "Free-text or regular-expression search over change fields.")
	cmd.Flags().Int64Var(&fStartTime, "start-time", 0, "Unix timestamp in seconds for the start of the query window.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func registerGeneratedChanges(root *cobra.Command) {
	gChange := genGroup(root, "change", "On-call/Changes API")
	genAddLeaf(gChange, genChangesListCmd())
}
