// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import "github.com/spf13/cobra"

// registerGenerated attaches every generated command group to root. Called
// from root.go init() after curated commands so curated leaves win on conflict.
func registerGenerated(root *cobra.Command) {
	registerGeneratedCalendars(root)
}
