// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genAutomationsRuleReadGetCmd() *cobra.Command {
	var dataJSON string
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "automation-rule-get <rule-id>",
		Short: "Get Automation rule",
		Long: `Get Automation rule.

Get one Automation rule by ID.

API: POST /safari/automation/rule/get (automation-rule-read-get)

Request fields:
  --rule-id string (required) — Rule ID, from the list returned by 'POST /safari/automation/rule/list'.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) (required) — Account ID.
  - can_edit (boolean) (required) — True when the caller can manage this rule: the personal rule owner; for team rules, an account admin or a member of the rule's team.
  - created_at (string) (required) — Creation time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - cron_expr (string) (required) — Normalized 5-field cron expression.
  - enabled (boolean) (required) — Whether the rule is enabled.
  - environment_id (string) (required) — BYOC Runner ID.
  - environment_kind (string) (required) — Runtime environment kind. Omit or send an empty value for automatic selection. One of: 'cloud' (platform-hosted cloud sandbox), 'byoc' (self-hosted BYOC runner in the account); an empty value means automatic selection (prefers an online BYOC runner, falls back to the cloud sandbox). [cloud, byoc]
  - http_post_token (string) — HTTP POST trigger token. Returned only on create or token rotation; save it immediately.
  - http_post_trigger_enabled (boolean) (required) — Whether the HTTP POST trigger is enabled.
  - http_post_trigger_id (string) — HTTP POST trigger ID. Omitted when the rule has no HTTP POST trigger.
  - http_post_trigger_url (string) — HTTP POST trigger path. Omitted when the rule has no HTTP POST trigger.
  - name (string) (required) — Rule name.
  - oncall_incident_channel_ids (array<integer>) — On-call integration IDs to watch. Creating or enabling this trigger requires at least one valid ID. Omitted when no On-call incident trigger is configured.
  - oncall_incident_severities (array<string>) — Incident severities to watch. Supported values are Critical, Warning, and Info; creating or enabling this trigger requires at least one value. Omitted when no On-call incident trigger is configured. [Critical, Warning, Info]
  - oncall_incident_trigger_enabled (boolean) (required) — Whether the On-call incident trigger is enabled.
  - oncall_incident_trigger_id (string) — On-call incident trigger ID. Omitted when the rule has no On-call incident trigger.
  - owner_id (integer) (required) — Creator person ID.
  - prompt (string) (required) — Task prompt.
  - rule_id (string) (required) — Rule ID.
  - run_scope (string) (required) — Hidden session run scope. One of: 'person' (personal rule, team_id=0, runs as the creator; disabled when the creator leaves the account), 'team' (team rule, team_id>0, owned by the team and shared with its members; survives the creator leaving). Derived from the rule's team_id. [person, team]
  - schedule_next_fire_at_ms (string) (required) — Next scheduled fire time, Unix milliseconds. 0 means no future scheduled fire is available. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - schedule_trigger_enabled (boolean) (required) — Whether the schedule trigger is enabled.
  - schedule_trigger_id (string) — Schedule trigger ID. Omitted if the rule has no schedule trigger.
  - team_id (integer) (required) — Scope team ID; 0 means personal rule.
  - timezone (string) (required) — IANA timezone 'cron_expr' is evaluated in. Always populated for rules created after this field shipped; empty on legacy rows created before it, which still resolve to UTC when scheduled.
  - updated_at (string) (required) — Last update time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
`,
		Args:    requireBodyFieldOrExactArg("rule_id", "rule-id"),
		Example: `  flashduty safari automation-rule-get --data '{"rule_id":"arule_7NnLzY2Qp8xS4kUaV3mR6b"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "rule_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.AutomationRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Automations.RuleReadGet(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID, from the list returned by 'POST /safari/automation/rule/list'. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genAutomationsRuleReadListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fEnabled bool
	var fIncludePerson bool
	var fKeyword string
	var fScope string
	var fTeamIDs []int
	cmd := &cobra.Command{
		Use:   "automation-rule-list",
		Short: "List Automation rules",
		Long: `List Automation rules.

List Automation rules visible to the caller.

API: POST /safari/automation/rule/list (automation-rule-read-list)

Request fields:
  --page int — Page number, 1-based.
  --limit int — Page size.
  --search-after-ctx string
  --enabled bool — Filter by enabled state: 'true' returns only enabled rules, 'false' only disabled; omit or pass null for no filter.
  --include-person bool — Compatibility field; when scope is empty and this is false, behaves like team scope.
  --keyword string — Filter by name keyword. (≤64 chars)
  --scope string — Scope filter: 'all' (own personal + accessible team rules), 'personal', or 'team'; default 'all'. [all, personal, team]
  --team-ids []int — Filter to these team IDs; this narrows results and does not expand access.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - rules (array<object>) (required) — Array of automation rules for the current page, used with 'total' for pagination.
    - account_id (integer) (required) — Account ID.
    - can_edit (boolean) (required) — True when the caller can manage this rule: the personal rule owner; for team rules, an account admin or a member of the rule's team.
    - created_at (string) (required) — Creation time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
    - cron_expr (string) (required) — Normalized 5-field cron expression.
    - enabled (boolean) (required) — Whether the rule is enabled.
    - environment_id (string) (required) — BYOC Runner ID.
    - environment_kind (string) (required) — Runtime environment kind. Omit or send an empty value for automatic selection. One of: 'cloud' (platform-hosted cloud sandbox), 'byoc' (self-hosted BYOC runner in the account); an empty value means automatic selection (prefers an online BYOC runner, falls back to the cloud sandbox). [cloud, byoc]
    - http_post_token (string) — HTTP POST trigger token. Returned only on create or token rotation; save it immediately.
    - http_post_trigger_enabled (boolean) (required) — Whether the HTTP POST trigger is enabled.
    - http_post_trigger_id (string) — HTTP POST trigger ID. Omitted when the rule has no HTTP POST trigger.
    - http_post_trigger_url (string) — HTTP POST trigger path. Omitted when the rule has no HTTP POST trigger.
    - name (string) (required) — Rule name.
    - oncall_incident_channel_ids (array<integer>) — On-call integration IDs to watch. Creating or enabling this trigger requires at least one valid ID. Omitted when no On-call incident trigger is configured.
    - oncall_incident_severities (array<string>) — Incident severities to watch. Supported values are Critical, Warning, and Info; creating or enabling this trigger requires at least one value. Omitted when no On-call incident trigger is configured. [Critical, Warning, Info]
    - oncall_incident_trigger_enabled (boolean) (required) — Whether the On-call incident trigger is enabled.
    - oncall_incident_trigger_id (string) — On-call incident trigger ID. Omitted when the rule has no On-call incident trigger.
    - owner_id (integer) (required) — Creator person ID.
    - prompt (string) (required) — Task prompt.
    - rule_id (string) (required) — Rule ID.
    - run_scope (string) (required) — Hidden session run scope. One of: 'person' (personal rule, team_id=0, runs as the creator; disabled when the creator leaves the account), 'team' (team rule, team_id>0, owned by the team and shared with its members; survives the creator leaving). Derived from the rule's team_id. [person, team]
    - schedule_next_fire_at_ms (string) (required) — Next scheduled fire time, Unix milliseconds. 0 means no future scheduled fire is available. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
    - schedule_trigger_enabled (boolean) (required) — Whether the schedule trigger is enabled.
    - schedule_trigger_id (string) — Schedule trigger ID. Omitted if the rule has no schedule trigger.
    - team_id (integer) (required) — Scope team ID; 0 means personal rule.
    - timezone (string) (required) — IANA timezone 'cron_expr' is evaluated in. Always populated for rules created after this field shipped; empty on legacy rows created before it, which still resolve to UTC when scheduled.
    - updated_at (string) (required) — Last update time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - total (integer) (required) — Total count.
`,
		Example: `  flashduty safari automation-rule-list --data '{"limit":20,"scope":"all"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("page") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("enabled") {
						body["enabled"] = fEnabled
					}
					if cmd.Flags().Changed("include-person") {
						body["include_person"] = fIncludePerson
					}
					if cmd.Flags().Changed("keyword") {
						body["keyword"] = fKeyword
					}
					if cmd.Flags().Changed("scope") {
						body["scope"] = fScope
					}
					if cmd.Flags().Changed("team-ids") {
						body["team_ids"] = fTeamIDs
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.AutomationRuleListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Automations.RuleReadList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "page", 0, "Page number, 1-based.")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size.")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().BoolVar(&fEnabled, "enabled", false, "Filter by enabled state: 'true' returns only enabled rules, 'false' only disabled; omit or pass null for no filter.")
	cmd.Flags().BoolVar(&fIncludePerson, "include-person", false, "Compatibility field; when scope is empty and this is false, behaves like team scope.")
	cmd.Flags().StringVar(&fKeyword, "keyword", "", "Filter by name keyword. (≤64 chars)")
	cmd.Flags().StringVar(&fScope, "scope", "", "Scope filter: 'all' (own personal + accessible team rules), 'personal', or 'team'; default 'all'. [all, personal, team]")
	cmd.Flags().IntSliceVar(&fTeamIDs, "team-ids", nil, "Filter to these team IDs; this narrows results and does not expand access.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genAutomationsRuleWriteCreateCmd() *cobra.Command {
	var dataJSON string
	var fCronExpr string
	var fEnabled bool
	var fEnvironmentID string
	var fEnvironmentKind string
	var fHTTPPostTriggerEnabled bool
	var fName string
	var fOncallIncidentChannelIDs []int
	var fOncallIncidentSeverities []string
	var fOncallIncidentTriggerEnabled bool
	var fPrompt string
	var fScheduleTriggerEnabled bool
	var fTeamID int64
	var fTimezone string
	cmd := &cobra.Command{
		Use:   "automation-rule-create",
		Short: "Create Automation rule",
		Long: `Create Automation rule.

Create an Automation rule with schedule, HTTP POST, and On-call incident triggers.

API: POST /safari/automation/rule/create (automation-rule-write-create)

Request fields:
  --cron-expr string (required) — Run cadence. Supports 4 fields ('hour day month weekday', minute defaults to 0) and 5 fields ('minute hour day month weekday'). The minute must be one fixed integer; 6-field seconds are not supported. A cron that sets both day-of-month and day-of-week is rejected. The create API currently requires this field even for HTTP-POST-only rules; send a valid cron and set 'schedule_trigger_enabled=false'.
  --enabled bool — Whether the rule is enabled after creation. Omitted API value is false; Chat/CLI create sends true by default unless the user asks for disabled.
  --environment-id string — BYOC Runner ID. Used only when 'environment_kind=byoc'.
  --environment-kind string — Runtime environment kind. Omit or send an empty value for automatic selection. One of: 'cloud' (platform-hosted cloud sandbox), 'byoc' (a self-hosted BYOC runner in the account, used with 'environment_id'); automatic selection prefers an online BYOC runner and falls back to the cloud sandbox. [cloud, byoc]
  --http-post-trigger-enabled bool — Whether to create and enable an HTTP POST trigger. When enabled, the response includes a one-time token.
  --name string (required) — Rule name. (1-255 chars)
  --oncall-incident-channel-ids []int — On-call integration IDs to watch. Creating or enabling this trigger requires at least one valid ID.
  --oncall-incident-severities []string — Incident severities to watch. Supported values are Critical, Warning, and Info; creating or enabling this trigger requires at least one value. [Critical, Warning, Info]
  --oncall-incident-trigger-enabled bool — Whether the On-call incident trigger is enabled.
  --prompt string (required) — Task prompt sent to the AI SRE agent on each run. (≥1 chars)
  --schedule-trigger-enabled bool — Whether the schedule trigger is enabled. Defaults to true when omitted; HTTP-POST-only rules should send false.
  --team-id int — Scope team ID. 0 or omitted means a personal rule; >0 means a team in the account. Can be reassigned later via update (converting a team rule to personal is owner-only; moving into a team requires the caller to belong to it). (min 0)
  --timezone string — IANA timezone 'cron_expr' is evaluated in, e.g. 'Asia/Shanghai'. Must be a timezone name loadable by the server; an invalid value is rejected. Defaults to the caller's member timezone, then the account timezone, then the server default (Asia/Shanghai) when omitted.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) (required) — Account ID.
  - can_edit (boolean) (required) — True when the caller can manage this rule: the personal rule owner; for team rules, an account admin or a member of the rule's team.
  - created_at (string) (required) — Creation time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - cron_expr (string) (required) — Normalized 5-field cron expression.
  - enabled (boolean) (required) — Whether the rule is enabled.
  - environment_id (string) (required) — BYOC Runner ID.
  - environment_kind (string) (required) — Runtime environment kind. Omit or send an empty value for automatic selection. One of: 'cloud' (platform-hosted cloud sandbox), 'byoc' (self-hosted BYOC runner in the account); an empty value means automatic selection (prefers an online BYOC runner, falls back to the cloud sandbox). [cloud, byoc]
  - http_post_token (string) — HTTP POST trigger token. Returned only on create or token rotation; save it immediately.
  - http_post_trigger_enabled (boolean) (required) — Whether the HTTP POST trigger is enabled.
  - http_post_trigger_id (string) — HTTP POST trigger ID. Omitted when the rule has no HTTP POST trigger.
  - http_post_trigger_url (string) — HTTP POST trigger path. Omitted when the rule has no HTTP POST trigger.
  - name (string) (required) — Rule name.
  - oncall_incident_channel_ids (array<integer>) — On-call integration IDs to watch. Creating or enabling this trigger requires at least one valid ID. Omitted when no On-call incident trigger is configured.
  - oncall_incident_severities (array<string>) — Incident severities to watch. Supported values are Critical, Warning, and Info; creating or enabling this trigger requires at least one value. Omitted when no On-call incident trigger is configured. [Critical, Warning, Info]
  - oncall_incident_trigger_enabled (boolean) (required) — Whether the On-call incident trigger is enabled.
  - oncall_incident_trigger_id (string) — On-call incident trigger ID. Omitted when the rule has no On-call incident trigger.
  - owner_id (integer) (required) — Creator person ID.
  - prompt (string) (required) — Task prompt.
  - rule_id (string) (required) — Rule ID.
  - run_scope (string) (required) — Hidden session run scope. One of: 'person' (personal rule, team_id=0, runs as the creator; disabled when the creator leaves the account), 'team' (team rule, team_id>0, owned by the team and shared with its members; survives the creator leaving). Derived from the rule's team_id. [person, team]
  - schedule_next_fire_at_ms (string) (required) — Next scheduled fire time, Unix milliseconds. 0 means no future scheduled fire is available. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - schedule_trigger_enabled (boolean) (required) — Whether the schedule trigger is enabled.
  - schedule_trigger_id (string) — Schedule trigger ID. Omitted if the rule has no schedule trigger.
  - team_id (integer) (required) — Scope team ID; 0 means personal rule.
  - timezone (string) (required) — IANA timezone 'cron_expr' is evaluated in. Always populated for rules created after this field shipped; empty on legacy rows created before it, which still resolve to UTC when scheduled.
  - updated_at (string) (required) — Last update time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
`,
		Example: `  flashduty safari automation-rule-create --data '{"cron_expr":"0 9 * * 1","enabled":true,"http_post_trigger_enabled":true,"name":"Weekly on-call review","oncall_incident_channel_ids":[456],"oncall_incident_severities":["Critical","Warning"],"oncall_incident_trigger_enabled":true,"prompt":"Summarize last week'\''s alert noise and escalation load.","schedule_trigger_enabled":true,"team_id":123,"timezone":"Asia/Shanghai"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("cron-expr") {
						body["cron_expr"] = fCronExpr
					}
					if cmd.Flags().Changed("enabled") {
						body["enabled"] = fEnabled
					}
					if cmd.Flags().Changed("environment-id") {
						body["environment_id"] = fEnvironmentID
					}
					if cmd.Flags().Changed("environment-kind") {
						body["environment_kind"] = fEnvironmentKind
					}
					if cmd.Flags().Changed("http-post-trigger-enabled") {
						body["http_post_trigger_enabled"] = fHTTPPostTriggerEnabled
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("oncall-incident-channel-ids") {
						body["oncall_incident_channel_ids"] = fOncallIncidentChannelIDs
					}
					if cmd.Flags().Changed("oncall-incident-severities") {
						body["oncall_incident_severities"] = fOncallIncidentSeverities
					}
					if cmd.Flags().Changed("oncall-incident-trigger-enabled") {
						body["oncall_incident_trigger_enabled"] = fOncallIncidentTriggerEnabled
					}
					if cmd.Flags().Changed("prompt") {
						body["prompt"] = fPrompt
					}
					if cmd.Flags().Changed("schedule-trigger-enabled") {
						body["schedule_trigger_enabled"] = fScheduleTriggerEnabled
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("timezone") {
						body["timezone"] = fTimezone
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.AutomationRuleCreateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Automations.RuleWriteCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fCronExpr, "cron-expr", "", "Run cadence. Supports 4 fields ('hour day month weekday', minute defaults to 0) and 5 fields ('minute hour day month weekday'). The minute must be one fixed integer; 6-field seconds are not supported. A cron that sets both day-of-month and day-of-week is rejected. The create API currently requires this field even for HTTP-POST-only rules; send a valid cron and set 'schedule_trigger_enabled=false'. (required)")
	cmd.Flags().BoolVar(&fEnabled, "enabled", false, "Whether the rule is enabled after creation. Omitted API value is false; Chat/CLI create sends true by default unless the user asks for disabled.")
	cmd.Flags().StringVar(&fEnvironmentID, "environment-id", "", "BYOC Runner ID. Used only when 'environment_kind=byoc'.")
	cmd.Flags().StringVar(&fEnvironmentKind, "environment-kind", "", "Runtime environment kind. Omit or send an empty value for automatic selection. One of: 'cloud' (platform-hosted cloud sandbox), 'byoc' (a self-hosted BYOC runner in the account, used with 'environment_id'); automatic selection prefers an online BYOC runner and falls back to the cloud sandbox. [cloud, byoc]")
	cmd.Flags().BoolVar(&fHTTPPostTriggerEnabled, "http-post-trigger-enabled", false, "Whether to create and enable an HTTP POST trigger. When enabled, the response includes a one-time token.")
	cmd.Flags().StringVar(&fName, "name", "", "Rule name. (required) (1-255 chars)")
	cmd.Flags().IntSliceVar(&fOncallIncidentChannelIDs, "oncall-incident-channel-ids", nil, "On-call integration IDs to watch. Creating or enabling this trigger requires at least one valid ID.")
	cmd.Flags().StringSliceVar(&fOncallIncidentSeverities, "oncall-incident-severities", nil, "Incident severities to watch. Supported values are Critical, Warning, and Info; creating or enabling this trigger requires at least one value. [Critical, Warning, Info]")
	cmd.Flags().BoolVar(&fOncallIncidentTriggerEnabled, "oncall-incident-trigger-enabled", false, "Whether the On-call incident trigger is enabled.")
	cmd.Flags().StringVar(&fPrompt, "prompt", "", "Task prompt sent to the AI SRE agent on each run. (required) (≥1 chars)")
	cmd.Flags().BoolVar(&fScheduleTriggerEnabled, "schedule-trigger-enabled", false, "Whether the schedule trigger is enabled. Defaults to true when omitted; HTTP-POST-only rules should send false.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Scope team ID. 0 or omitted means a personal rule; >0 means a team in the account. Can be reassigned later via update (converting a team rule to personal is owner-only; moving into a team requires the caller to belong to it). (min 0)")
	cmd.Flags().StringVar(&fTimezone, "timezone", "", "IANA timezone 'cron_expr' is evaluated in, e.g. 'Asia/Shanghai'. Must be a timezone name loadable by the server; an invalid value is rejected. Defaults to the caller's member timezone, then the account timezone, then the server default (Asia/Shanghai) when omitted.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genAutomationsRuleWriteDeleteCmd() *cobra.Command {
	var dataJSON string
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "automation-rule-delete <rule-id>",
		Short: "Delete Automation rule",
		Long: `Delete Automation rule.

Delete an Automation rule.

API: POST /safari/automation/rule/delete (automation-rule-write-delete)

Request fields:
  --rule-id string (required) — Rule ID, from the list returned by 'POST /safari/automation/rule/list'.
`,
		Args:    requireBodyFieldOrExactArg("rule_id", "rule-id"),
		Example: `  flashduty safari automation-rule-delete --data '{"rule_id":"arule_7NnLzY2Qp8xS4kUaV3mR6b"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "rule_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.AutomationRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Automations.RuleWriteDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID, from the list returned by 'POST /safari/automation/rule/list'. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genAutomationsRuleWriteRunCmd() *cobra.Command {
	var dataJSON string
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "automation-rule-run <rule-id>",
		Short: "Run Automation rule",
		Long: `Run Automation rule.

Manually run an Automation rule immediately, outside its schedule.

API: POST /safari/automation/rule/run (automation-rule-write-run)

Request fields:
  --rule-id string (required) — Rule ID, from the list returned by 'POST /safari/automation/rule/list'.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - preflight (object) (required) — Readiness checks computed before a manual run is allowed to start.
    - app_name (string) (required) — App the rule is scoped to. Currently always ai-sre; manual runs are only supported for that app.
    - checks (array<string>) (required) — Names of the readiness checks performed, in order. Current fixed set: rule_loaded, actor_authorized, app_allowed, runtime_scope_resolved, rule_config_valid.
    - ok (boolean) (required) — Whether all readiness checks passed. Always true in a response that reaches the caller — a failed preflight returns a 400/403 error instead of a payload with ok=false.
    - owner_id (integer) (required) — Rule owner person ID.
    - scope (string) (required) — Resolved run scope for this run; mirrors the rule's run_scope. One of: 'person' (personal rule, runs as its creator), 'team' (team rule, runs under the owning team). [person, team]
    - team_id (integer) (required) — Rule's scope team ID; 0 means a personal rule.
    - warnings (array<string>) — Non-fatal warnings surfaced during preflight. Omitted or empty when there are none.
  - rule_id (string) (required) — Rule ID that was run.
  - run (object) — Reference to the run started by a manual trigger.
    - run_id (string) (required) — Run ID, always populated once a run is created.
    - session_id (string) — AI SRE session ID for this run. Always populated in a 200 response, since the call only returns after the session has started.
  - trigger_kind (string) (required) — Always manual for this operation. [manual]
`,
		Args:    requireBodyFieldOrExactArg("rule_id", "rule-id"),
		Example: `  flashduty safari automation-rule-run --data '{"rule_id":"arule_7NnLzY2Qp8xS4kUaV3mR6b"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "rule_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.AutomationRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Automations.RuleWriteRun(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID, from the list returned by 'POST /safari/automation/rule/list'. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genAutomationsRuleWriteUpdateCmd() *cobra.Command {
	var dataJSON string
	var fRuleID string
	var fName string
	var fTeamID int64
	var fEnabled bool
	var fCronExpr string
	var fScheduleTriggerEnabled bool
	var fPrompt string
	var fEnvironmentKind string
	var fEnvironmentID string
	var fHTTPPostTriggerEnabled bool
	var fRotateHTTPPostTriggerToken bool
	var fOncallIncidentTriggerEnabled bool
	var fOncallIncidentChannelIDs []int
	var fOncallIncidentSeverities []string
	cmd := &cobra.Command{
		Use:   "automation-rule-update <rule-id>",
		Short: "Update Automation rule",
		Long: `Update Automation rule.

Update mutable Automation rule fields, including HTTP POST and On-call incident trigger settings.

API: POST /safari/automation/rule/update (automation-rule-write-update)

Request fields:
  --rule-id string (required) — Target rule ID, from the list returned by 'POST /safari/automation/rule/list'.
  --name string — New rule name. (≤255 chars)
  --team-id int — Reassign the rule's scope: 0 converts to a personal rule (only the rule owner may convert a team rule); >0 moves it into a team the caller belongs to. Omit to leave unchanged. (min 0)
  --enabled bool — Whether the rule is enabled.
  --cron-expr string — Run cadence. Supports 4 fields ('hour day month weekday', minute defaults to 0) and 5 fields ('minute hour day month weekday'). The minute must be one fixed integer; 6-field seconds are not supported.
  --schedule-trigger-enabled bool — Whether the schedule trigger is enabled.
  --prompt string — New task prompt.
  --environment-kind string — Runtime environment kind. Omit or send an empty value for automatic selection. [cloud, byoc]
  --environment-id string — BYOC Runner ID.
  --http-post-trigger-enabled bool — Whether the HTTP POST trigger is enabled. Sending true creates one when missing.
  --rotate-http-post-trigger-token bool — Whether to rotate the HTTP POST trigger token. The new token is returned only in this response.
  --oncall-incident-trigger-enabled bool — Whether the On-call incident trigger is enabled.
  --oncall-incident-channel-ids []int — On-call integration IDs to watch. Creating or enabling this trigger requires at least one valid ID.
  --oncall-incident-severities []string — Incident severities to watch. Supported values are Critical, Warning, and Info; creating or enabling this trigger requires at least one value. [Critical, Warning, Info]

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) (required) — Account ID.
  - can_edit (boolean) (required) — True when the caller can manage this rule: the personal rule owner; for team rules, an account admin or a member of the rule's team.
  - created_at (string) (required) — Creation time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - cron_expr (string) (required) — Normalized 5-field cron expression.
  - enabled (boolean) (required) — Whether the rule is enabled.
  - environment_id (string) (required) — BYOC Runner ID.
  - environment_kind (string) (required) — Runtime environment kind. Omit or send an empty value for automatic selection. One of: 'cloud' (platform-hosted cloud sandbox), 'byoc' (self-hosted BYOC runner in the account); an empty value means automatic selection (prefers an online BYOC runner, falls back to the cloud sandbox). [cloud, byoc]
  - http_post_token (string) — HTTP POST trigger token. Returned only on create or token rotation; save it immediately.
  - http_post_trigger_enabled (boolean) (required) — Whether the HTTP POST trigger is enabled.
  - http_post_trigger_id (string) — HTTP POST trigger ID. Omitted when the rule has no HTTP POST trigger.
  - http_post_trigger_url (string) — HTTP POST trigger path. Omitted when the rule has no HTTP POST trigger.
  - name (string) (required) — Rule name.
  - oncall_incident_channel_ids (array<integer>) — On-call integration IDs to watch. Creating or enabling this trigger requires at least one valid ID. Omitted when no On-call incident trigger is configured.
  - oncall_incident_severities (array<string>) — Incident severities to watch. Supported values are Critical, Warning, and Info; creating or enabling this trigger requires at least one value. Omitted when no On-call incident trigger is configured. [Critical, Warning, Info]
  - oncall_incident_trigger_enabled (boolean) (required) — Whether the On-call incident trigger is enabled.
  - oncall_incident_trigger_id (string) — On-call incident trigger ID. Omitted when the rule has no On-call incident trigger.
  - owner_id (integer) (required) — Creator person ID.
  - prompt (string) (required) — Task prompt.
  - rule_id (string) (required) — Rule ID.
  - run_scope (string) (required) — Hidden session run scope. One of: 'person' (personal rule, team_id=0, runs as the creator; disabled when the creator leaves the account), 'team' (team rule, team_id>0, owned by the team and shared with its members; survives the creator leaving). Derived from the rule's team_id. [person, team]
  - schedule_next_fire_at_ms (string) (required) — Next scheduled fire time, Unix milliseconds. 0 means no future scheduled fire is available. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - schedule_trigger_enabled (boolean) (required) — Whether the schedule trigger is enabled.
  - schedule_trigger_id (string) — Schedule trigger ID. Omitted if the rule has no schedule trigger.
  - team_id (integer) (required) — Scope team ID; 0 means personal rule.
  - timezone (string) (required) — IANA timezone 'cron_expr' is evaluated in. Always populated for rules created after this field shipped; empty on legacy rows created before it, which still resolve to UTC when scheduled.
  - updated_at (string) (required) — Last update time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
`,
		Args:    requireBodyFieldOrExactArg("rule_id", "rule-id"),
		Example: `  flashduty safari automation-rule-update --data '{"cron_expr":"15 9 * * 1","enabled":true,"oncall_incident_channel_ids":[456],"oncall_incident_severities":["Critical","Warning"],"oncall_incident_trigger_enabled":true,"rotate_http_post_trigger_token":true,"rule_id":"arule_7NnLzY2Qp8xS4kUaV3mR6b"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "rule_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					if cmd.Flags().Changed("name") {
						body["name"] = fName
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
					if cmd.Flags().Changed("enabled") {
						body["enabled"] = fEnabled
					}
					if cmd.Flags().Changed("cron-expr") {
						body["cron_expr"] = fCronExpr
					}
					if cmd.Flags().Changed("schedule-trigger-enabled") {
						body["schedule_trigger_enabled"] = fScheduleTriggerEnabled
					}
					if cmd.Flags().Changed("prompt") {
						body["prompt"] = fPrompt
					}
					if cmd.Flags().Changed("environment-kind") {
						body["environment_kind"] = fEnvironmentKind
					}
					if cmd.Flags().Changed("environment-id") {
						body["environment_id"] = fEnvironmentID
					}
					if cmd.Flags().Changed("http-post-trigger-enabled") {
						body["http_post_trigger_enabled"] = fHTTPPostTriggerEnabled
					}
					if cmd.Flags().Changed("rotate-http-post-trigger-token") {
						body["rotate_http_post_trigger_token"] = fRotateHTTPPostTriggerToken
					}
					if cmd.Flags().Changed("oncall-incident-trigger-enabled") {
						body["oncall_incident_trigger_enabled"] = fOncallIncidentTriggerEnabled
					}
					if cmd.Flags().Changed("oncall-incident-channel-ids") {
						body["oncall_incident_channel_ids"] = fOncallIncidentChannelIDs
					}
					if cmd.Flags().Changed("oncall-incident-severities") {
						body["oncall_incident_severities"] = fOncallIncidentSeverities
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.AutomationRuleUpdateRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Automations.RuleWriteUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Target rule ID, from the list returned by 'POST /safari/automation/rule/list'. (required)")
	cmd.Flags().StringVar(&fName, "name", "", "New rule name. (≤255 chars)")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Reassign the rule's scope: 0 converts to a personal rule (only the rule owner may convert a team rule); >0 moves it into a team the caller belongs to. Omit to leave unchanged. (min 0)")
	cmd.Flags().BoolVar(&fEnabled, "enabled", false, "Whether the rule is enabled.")
	cmd.Flags().StringVar(&fCronExpr, "cron-expr", "", "Run cadence. Supports 4 fields ('hour day month weekday', minute defaults to 0) and 5 fields ('minute hour day month weekday'). The minute must be one fixed integer; 6-field seconds are not supported.")
	cmd.Flags().BoolVar(&fScheduleTriggerEnabled, "schedule-trigger-enabled", false, "Whether the schedule trigger is enabled.")
	cmd.Flags().StringVar(&fPrompt, "prompt", "", "New task prompt.")
	cmd.Flags().StringVar(&fEnvironmentKind, "environment-kind", "", "Runtime environment kind. Omit or send an empty value for automatic selection. [cloud, byoc]")
	cmd.Flags().StringVar(&fEnvironmentID, "environment-id", "", "BYOC Runner ID.")
	cmd.Flags().BoolVar(&fHTTPPostTriggerEnabled, "http-post-trigger-enabled", false, "Whether the HTTP POST trigger is enabled. Sending true creates one when missing.")
	cmd.Flags().BoolVar(&fRotateHTTPPostTriggerToken, "rotate-http-post-trigger-token", false, "Whether to rotate the HTTP POST trigger token. The new token is returned only in this response.")
	cmd.Flags().BoolVar(&fOncallIncidentTriggerEnabled, "oncall-incident-trigger-enabled", false, "Whether the On-call incident trigger is enabled.")
	cmd.Flags().IntSliceVar(&fOncallIncidentChannelIDs, "oncall-incident-channel-ids", nil, "On-call integration IDs to watch. Creating or enabling this trigger requires at least one valid ID.")
	cmd.Flags().StringSliceVar(&fOncallIncidentSeverities, "oncall-incident-severities", nil, "Incident severities to watch. Supported values are Critical, Warning, and Info; creating or enabling this trigger requires at least one value. [Critical, Warning, Info]")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genAutomationsRunReadListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fRuleID string
	var fStartedAfterMs int64
	var fStartedBeforeMs int64
	var fStatus string
	var fTriggerKind string
	cmd := &cobra.Command{
		Use:   "automation-run-list <rule-id>",
		Short: "List Automation runs",
		Long: `List Automation runs.

List run history for a rule the caller can manage.

API: POST /safari/automation/run/list (automation-run-read-list)

Request fields:
  --page int — Page number, 1-based.
  --limit int — Page size.
  --search-after-ctx string
  --rule-id string (required) — Target rule ID, from the list returned by 'POST /safari/automation/rule/list'.
  --started-after-ms int — Start-time lower bound, Unix milliseconds. Values below the 180-day run-history retention floor are clamped to it (that floor is also the default when omitted). (min 0)
  --started-before-ms int — Start-time upper bound, Unix milliseconds. Must be greater than or equal to the effective 'started_after_ms'; a value below the retention floor yields an empty result. (min 0)
  --status string — Run status filter: 'queued', 'running', 'retrying', 'succeeded', 'partial' (partially succeeded), 'failed', 'skipped' (e.g. rule or trigger no longer valid), 'abandoned' (stale run terminated by the system), 'blocked' (terminal; produced output but a connector is waiting on a human authorization); omit for no filter. [queued, running, retrying, succeeded, partial, failed, skipped, abandoned, blocked]
  --trigger-kind string — Trigger source filter: 'schedule' cron trigger, 'debug' debug run, 'manual' manual run, 'http_post' HTTP POST trigger, 'oncall_incident' on-call incident trigger; omit for no filter. [schedule, debug, manual, http_post, oncall_incident]

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - runs (array<object>) (required) — Array of run records for the given 'rule_id', filtered by the request's status/trigger-kind/time-range and paginated.
    - account_id (integer) (required) — Account ID.
    - attempts (integer) (required) — Attempt count.
    - completed_at (string) (required) — Completion time, Unix milliseconds. 0 means not completed. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
    - created_at (string) (required) — Creation time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
    - duration_ms (integer) (required) — Duration in milliseconds.
    - error_code (string) (required) — Error code; empty when the run did not fail.
    - error_message (string) (required) — Error message; empty when the run did not fail.
    - kind (string) (required) — Run kind; runs listed for a rule are always 'automation_rule'. [automation_rule]
    - occurrence_key (string) (required) — Idempotency key for this occurrence.
    - result_json (object) (required) — Raw run result JSON (carries the run's 'session_id' once started); null when empty.
    - rule_id (string) (required) — Rule ID.
    - run_id (string) (required) — Run ID.
    - session_id (string) — Session created for this run, extracted from 'result_json'. Omitted when the run has not (yet) started a session.
    - session_name (string) — Display name of the run's session, stamped via a batch lookup. Omitted when empty or when the lookup fails.
    - started_at (string) (required) — Start time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
    - stats_json (object) (required) — Raw run statistics JSON; null when empty.
    - status (string) (required) — Run status. One of (the first three are in-flight, the rest terminal): | Value | Meaning | | --- | --- | | 'queued' | Enqueued, waiting for a worker | | 'running' | Executing | | 'retrying' | An attempt failed and a retry is scheduled | | 'succeeded' | Completed successfully | | 'partial' | Partially succeeded (currently only produced by memory-consolidation runs; rule runs never reach it) | | 'failed' | Terminal failure, no further retries | | 'skipped' | Not executed (e.g. grace period expired, trigger or rule invalid); the reason is kept on the run record | | 'abandoned' | Still in-flight past the stale threshold and swept as never-completed (e.g. worker died) | | 'blocked' | Terminal: the run produced output but ended with a connector waiting on a human to complete authorization (distinct from 'failed') | [queued, running, retrying, succeeded, partial, failed, skipped, abandoned, blocked]
    - trigger_kind (string) (required) — Trigger kind. One of: | Value | Meaning | | --- | --- | | 'schedule' | Fired by the rule's schedule trigger | | 'debug' | Debug run (reserved; current rule runs never carry this kind) | | 'manual' | Triggered manually by a user | | 'http_post' | Fired via the rule's HTTP POST webhook | | 'oncall_incident' | Fired by an on-call incident event | [schedule, debug, manual, http_post, oncall_incident]
    - updated_at (string) (required) — Last update time, Unix milliseconds. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value renders as null.
  - total (integer) (required) — Total count.
`,
		Args:    requireBodyFieldOrExactArg("rule_id", "rule-id"),
		Example: `  flashduty safari automation-run-list --data '{"limit":20,"rule_id":"arule_7NnLzY2Qp8xS4kUaV3mR6b","trigger_kind":"schedule"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if err := genFoldPositional(args, body, "rule_id", "string"); err != nil {
						return err
					}
					if cmd.Flags().Changed("page") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					if cmd.Flags().Changed("started-after-ms") {
						body["started_after_ms"] = fStartedAfterMs
					}
					if cmd.Flags().Changed("started-before-ms") {
						body["started_before_ms"] = fStartedBeforeMs
					}
					if cmd.Flags().Changed("status") {
						body["status"] = fStatus
					}
					if cmd.Flags().Changed("trigger-kind") {
						body["trigger_kind"] = fTriggerKind
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.AutomationRunListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Automations.RunReadList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "page", 0, "Page number, 1-based.")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size.")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Target rule ID, from the list returned by 'POST /safari/automation/rule/list'. (required)")
	cmd.Flags().Int64Var(&fStartedAfterMs, "started-after-ms", 0, "Start-time lower bound, Unix milliseconds. Values below the 180-day run-history retention floor are clamped to it (that floor is also the default when omitted). (min 0)")
	cmd.Flags().Int64Var(&fStartedBeforeMs, "started-before-ms", 0, "Start-time upper bound, Unix milliseconds. Must be greater than or equal to the effective 'started_after_ms'; a value below the retention floor yields an empty result. (min 0)")
	cmd.Flags().StringVar(&fStatus, "status", "", "Run status filter: 'queued', 'running', 'retrying', 'succeeded', 'partial' (partially succeeded), 'failed', 'skipped' (e.g. rule or trigger no longer valid), 'abandoned' (stale run terminated by the system), 'blocked' (terminal; produced output but a connector is waiting on a human authorization); omit for no filter. [queued, running, retrying, succeeded, partial, failed, skipped, abandoned, blocked]")
	cmd.Flags().StringVar(&fTriggerKind, "trigger-kind", "", "Trigger source filter: 'schedule' cron trigger, 'debug' debug run, 'manual' manual run, 'http_post' HTTP POST trigger, 'oncall_incident' on-call incident trigger; omit for no filter. [schedule, debug, manual, http_post, oncall_incident]")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func genAutomationsTemplateReadListCmd() *cobra.Command {
	var dataJSON string
	var fLocale string
	cmd := &cobra.Command{
		Use:   "automation-template-list",
		Short: "List Automation templates",
		Long: `List Automation templates.

List preset Automation templates for the requested locale.

API: POST /safari/automation/template/list (automation-template-read-list)

Request fields:
  --locale string — Template locale such as zh-CN or en-US. Omit to detect from the request locale. (≤16 chars)

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - templates (array<object>) (required) — Array of built-in automation templates, with display text localized by the request 'locale' (falling back to request headers).
    - description (string) (required) — Template description.
    - enabled (boolean) (required) — Whether a rule created from this template starts out enabled (prefill value).
    - icon (string) (required) — Icon identifier.
    - name (string) (required) — Template name.
    - prompt (string) (required) — Template prompt.
`,
		Example: `  flashduty safari automation-template-list --data '{"locale":"en-US"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("locale") {
						body["locale"] = fLocale
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.AutomationTemplateListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Automations.TemplateReadList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fLocale, "locale", "", "Template locale such as zh-CN or en-US. Omit to detect from the request locale. (≤16 chars)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedAutomations(root *cobra.Command) {
	gSafari := genGroup(root, "safari", "AI SRE API")
	genAddLeaf(gSafari, genAutomationsRuleReadGetCmd())
	genAddLeaf(gSafari, genAutomationsRuleReadListCmd())
	genAddLeaf(gSafari, genAutomationsRuleWriteCreateCmd())
	genAddLeaf(gSafari, genAutomationsRuleWriteDeleteCmd())
	genAddLeaf(gSafari, genAutomationsRuleWriteRunCmd())
	genAddLeaf(gSafari, genAutomationsRuleWriteUpdateCmd())
	genAddLeaf(gSafari, genAutomationsRunReadListCmd())
	genAddLeaf(gSafari, genAutomationsTemplateReadListCmd())
}
