// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genChannelsChannelCreateCmd() *cobra.Command {
	var dataJSON string
	var fAutoResolveMode string
	var fAutoResolveTimeout int64
	var fChannelName string
	var fDescription string
	var fDisableAutoClose bool
	var fDisableOutlierDetection bool
	var fIsExternalReportEnabled bool
	var fIsPrivate bool
	var fManagingTeamIDs []int
	var fPluginIDs []int
	var fTeamID int64
	cmd := &cobra.Command{
		Use:   "create",
		Short: "Create channel",
		Long: `Create channel.

Create a new channel for incident management.

API: POST /channel/create (channelCreate)

Request fields:
  --auto-resolve-mode string — Auto-resolve timer reset mode. [trigger, update]
  --auto-resolve-timeout int — Auto-resolve timeout in seconds. 0 disables auto-resolve. Max 30 days.
  --channel-name string (required) — Channel name. 1 to 59 characters.
  --description string — Free-form description. Up to 500 characters.
  --disable-auto-close bool — Disable automatic incident closing.
  --disable-outlier-detection bool — Disable outlier incident detection.
  --is-external-report-enabled bool — Allow external reporters to file incidents into this channel.
  --is-private bool — When true, the channel is visible only to its managing teams.
  --managing-team-ids []int — Additional teams that can manage the channel. Up to 3 entries.
  --plugin-ids []int — IDs of plugins (integrations) subscribed to this channel.
  --team-id int (required) — Owning team ID.
  escalate_rule (JSON, via --data) — Default escalation rule applied to the channel. Omit to skip default escalation.
  flapping (JSON, via --data) — Flapping detection configuration.
  group (JSON, via --data) — Alert grouping configuration.
`,
		Example: `  flashduty channel create --data '{"auto_resolve_mode":"trigger","auto_resolve_timeout":86400,"channel_name":"Production Alerts","description":"Handles all production environment alerts","group":{"method":"p","time_window":10,"window_type":"tumbling"},"team_id":3521074710131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("auto-resolve-mode") {
						body["auto_resolve_mode"] = fAutoResolveMode
					}
					if cmd.Flags().Changed("auto-resolve-timeout") {
						body["auto_resolve_timeout"] = fAutoResolveTimeout
					}
					if cmd.Flags().Changed("channel-name") {
						body["channel_name"] = fChannelName
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("disable-auto-close") {
						body["disable_auto_close"] = fDisableAutoClose
					}
					if cmd.Flags().Changed("disable-outlier-detection") {
						body["disable_outlier_detection"] = fDisableOutlierDetection
					}
					if cmd.Flags().Changed("is-external-report-enabled") {
						body["is_external_report_enabled"] = fIsExternalReportEnabled
					}
					if cmd.Flags().Changed("is-private") {
						body["is_private"] = fIsPrivate
					}
					if cmd.Flags().Changed("managing-team-ids") {
						body["managing_team_ids"] = fManagingTeamIDs
					}
					if cmd.Flags().Changed("plugin-ids") {
						body["plugin_ids"] = fPluginIDs
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CreateChannelRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fAutoResolveMode, "auto-resolve-mode", "", "Auto-resolve timer reset mode. [trigger, update]")
	cmd.Flags().Int64Var(&fAutoResolveTimeout, "auto-resolve-timeout", 0, "Auto-resolve timeout in seconds. 0 disables auto-resolve. Max 30 days.")
	cmd.Flags().StringVar(&fChannelName, "channel-name", "", "Channel name. 1 to 59 characters. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Free-form description. Up to 500 characters.")
	cmd.Flags().BoolVar(&fDisableAutoClose, "disable-auto-close", false, "Disable automatic incident closing.")
	cmd.Flags().BoolVar(&fDisableOutlierDetection, "disable-outlier-detection", false, "Disable outlier incident detection.")
	cmd.Flags().BoolVar(&fIsExternalReportEnabled, "is-external-report-enabled", false, "Allow external reporters to file incidents into this channel.")
	cmd.Flags().BoolVar(&fIsPrivate, "is-private", false, "When true, the channel is visible only to its managing teams.")
	cmd.Flags().IntSliceVar(&fManagingTeamIDs, "managing-team-ids", nil, "Additional teams that can manage the channel. Up to 3 entries.")
	cmd.Flags().IntSliceVar(&fPluginIDs, "plugin-ids", nil, "IDs of plugins (integrations) subscribed to this channel.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "Owning team ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelDeleteCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	cmd := &cobra.Command{
		Use:   "delete",
		Short: "Delete channel",
		Long: `Delete channel.

Delete a channel and all associated configuration.

API: POST /channel/delete (channelDelete)

Request fields:
  --channel-id int (required) — Channel ID.
`,
		Example: `  flashduty channel delete --data '{"channel_id":3521074710131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/delete")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelDisableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	cmd := &cobra.Command{
		Use:   "disable",
		Short: "Disable channel",
		Long: `Disable channel.

Disable a channel to stop incident routing without deleting it.

API: POST /channel/disable (channelDisable)

Request fields:
  --channel-id int (required) — Channel ID.
`,
		Example: `  flashduty channel disable --data '{"channel_id":3521074710131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelDisable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/disable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelEnableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	cmd := &cobra.Command{
		Use:   "enable",
		Short: "Enable channel",
		Long: `Enable channel.

Enable a disabled channel to resume incident routing.

API: POST /channel/enable (channelEnable)

Request fields:
  --channel-id int (required) — Channel ID.
`,
		Example: `  flashduty channel enable --data '{"channel_id":3521074710131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelEnable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/enable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel ID. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelEscalateRuleCreateCmd() *cobra.Command {
	var dataJSON string
	var fAggrWindow int64
	var fChannelID int64
	var fDescription string
	var fPriority int64
	var fRuleName string
	var fTemplateID string
	cmd := &cobra.Command{
		Use:   "escalate-rule-create",
		Short: "Create escalation rule",
		Long: `Create escalation rule.

Create an escalation rule defining who gets notified and when during an incident.

API: POST /channel/escalate/rule/create (channelEscalateRuleCreate)

Request fields:
  --aggr-window int — Aggregation window in seconds. 0 disables aggregation.
  --channel-id int (required) — Channel the rule belongs to.
  --description string — Rule description, up to 500 characters.
  --priority int — Evaluation priority. Lower runs first.
  --rule-name string (required) — Rule name, 1 to 39 characters.
  --template-id string (required) — Notification template ID (MongoDB ObjectID).
  filters (JSON, via --data) — Or-of-and filter tree. Each outer element is an AND group; within each group, all conditions must match.
  layers (JSON, via --data) (required) — Escalation levels in order. At least one level is required.
  time_filters (JSON, via --data) — Optional recurring time windows during which the rule applies.
`,
		Example: `  flashduty channel escalate-rule-create --data '{"channel_id":3521074710131,"description":"Notify primary on-call, then escalate to secondary after 30 minutes","layers":[{"escalate_window":30,"force_escalate":false,"max_times":3,"notify_step":10,"target":{"by":{"follow_preference":true},"person_ids":[3790925372131]}}],"rule_name":"On-call escalation","template_id":"6321aad26c12104586a88916"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("aggr-window") {
						body["aggr_window"] = fAggrWindow
					}
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("priority") {
						body["priority"] = fPriority
					}
					if cmd.Flags().Changed("rule-name") {
						body["rule_name"] = fRuleName
					}
					if cmd.Flags().Changed("template-id") {
						body["template_id"] = fTemplateID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CreateEscalationRuleRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelEscalateRuleCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fAggrWindow, "aggr-window", 0, "Aggregation window in seconds. 0 disables aggregation.")
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Rule description, up to 500 characters.")
	cmd.Flags().Int64Var(&fPriority, "priority", 0, "Evaluation priority. Lower runs first.")
	cmd.Flags().StringVar(&fRuleName, "rule-name", "", "Rule name, 1 to 39 characters. (required)")
	cmd.Flags().StringVar(&fTemplateID, "template-id", "", "Notification template ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelEscalateRuleDeleteCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "escalate-rule-delete",
		Short: "Delete escalation rule",
		Long: `Delete escalation rule.

Delete an escalation rule.

API: POST /channel/escalate/rule/delete (channelEscalateRuleDelete)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel escalate-rule-delete --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelEscalateRuleDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/escalate/rule/delete")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelEscalateRuleDisableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "escalate-rule-disable",
		Short: "Disable escalation rule",
		Long: `Disable escalation rule.

Disable an escalation rule without deleting it.

API: POST /channel/escalate/rule/disable (channelEscalateRuleDisable)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel escalate-rule-disable --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelEscalateRuleDisable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/escalate/rule/disable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelEscalateRuleEnableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "escalate-rule-enable",
		Short: "Enable escalation rule",
		Long: `Enable escalation rule.

Enable a disabled escalation rule.

API: POST /channel/escalate/rule/enable (channelEscalateRuleEnable)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel escalate-rule-enable --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelEscalateRuleEnable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/escalate/rule/enable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelEscalateRuleInfoCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "escalate-rule-info",
		Short: "Get escalation rule detail",
		Long: `Get escalation rule detail.

Retrieve detailed information for a specific escalation rule.

API: POST /channel/escalate/rule/info (channelEscalateRuleInfo)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel escalate-rule-info --data '{"channel_id":1001,"rule_id":"6621b23f4a2c5e0012ab34d0"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelEscalateRuleInfo(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelEscalateRuleListCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	cmd := &cobra.Command{
		Use:   "escalate-rule-list",
		Short: "List escalation rules",
		Long: `List escalation rules.

List all escalation rules for a channel.

API: POST /channel/escalate/rule/list (channelEscalateRuleList)

Request fields:
  --channel-id int (required) — Channel to list rules for.
`,
		Example: `  flashduty channel escalate-rule-list --data '{"channel_id":1001}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelScopedListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelEscalateRuleList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel to list rules for. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelEscalateRuleUpdateCmd() *cobra.Command {
	var dataJSON string
	var fAggrWindow int64
	var fChannelID int64
	var fDescription string
	var fPriority int64
	var fRuleID string
	var fRuleName string
	var fTemplateID string
	cmd := &cobra.Command{
		Use:   "escalate-rule-update",
		Short: "Update escalation rule",
		Long: `Update escalation rule.

Update an existing escalation rule configuration.

API: POST /channel/escalate/rule/update (channelEscalateRuleUpdate)

Request fields:
  --aggr-window int — Aggregation window in seconds. 0 disables aggregation.
  --channel-id int (required) — Channel the rule belongs to.
  --description string — Rule description, up to 500 characters.
  --priority int — Evaluation priority. Lower runs first.
  --rule-id string (required) — Escalation rule ID (MongoDB ObjectID).
  --rule-name string (required) — Rule name, 1 to 39 characters.
  --template-id string (required) — Notification template ID (MongoDB ObjectID).
  filters (JSON, via --data)
  layers (JSON, via --data) (required) — Escalation levels in order. At least one level is required.
  time_filters (JSON, via --data) — Optional recurring time windows during which the rule applies.
`,
		Example: `  flashduty channel escalate-rule-update --data '{"channel_id":1001,"layers":[{"target":{"by":{"critical":["voice"],"warning":["sms"]},"person_ids":[42]}}],"rule_id":"6621b23f4a2c5e0012ab34d0","rule_name":"Default escalation","template_id":"6621b23f4a2c5e0012ab34d1"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("aggr-window") {
						body["aggr_window"] = fAggrWindow
					}
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("priority") {
						body["priority"] = fPriority
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					if cmd.Flags().Changed("rule-name") {
						body["rule_name"] = fRuleName
					}
					if cmd.Flags().Changed("template-id") {
						body["template_id"] = fTemplateID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.UpdateEscalationRuleRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelEscalateRuleUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/escalate/rule/update")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fAggrWindow, "aggr-window", 0, "Aggregation window in seconds. 0 disables aggregation.")
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Rule description, up to 500 characters.")
	cmd.Flags().Int64Var(&fPriority, "priority", 0, "Evaluation priority. Lower runs first.")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Escalation rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&fRuleName, "rule-name", "", "Rule name, 1 to 39 characters. (required)")
	cmd.Flags().StringVar(&fTemplateID, "template-id", "", "Notification template ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelInfoCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	cmd := &cobra.Command{
		Use:   "info",
		Short: "Get channel detail",
		Long: `Get channel detail.

Retrieve detailed information for a specific channel.

API: POST /channel/info (channelInfo)

Request fields:
  --channel-id int (required) — Channel ID to fetch.
`,
		Example: `  flashduty channel info --data '{"channel_id":1001}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelInfoRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelInfo(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel ID to fetch. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelInfosCmd() *cobra.Command {
	var dataJSON string
	var fChannelIDs []int
	cmd := &cobra.Command{
		Use:   "infos",
		Short: "Batch get channels",
		Long: `Batch get channels.

Retrieve multiple channels by their IDs.

API: POST /channel/infos (channelInfos)

Request fields:
  --channel-ids []int (required) — Channel IDs to look up. Up to 1000.
`,
		Example: `  flashduty channel infos --data '{"channel_ids":[1001,1002]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-ids") {
						body["channel_ids"] = fChannelIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelInfosRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelInfos(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().IntSliceVar(&fChannelIDs, "channel-ids", nil, "Channel IDs to look up. Up to 1000. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelInhibitRuleCreateCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fDescription string
	var fEquals []string
	var fIsDirectlyDiscard bool
	var fPriority int64
	var fRuleName string
	cmd := &cobra.Command{
		Use:   "inhibit-rule-create",
		Short: "Create inhibit rule",
		Long: `Create inhibit rule.

Create an inhibit rule to suppress lower-priority alerts when higher-priority ones are firing.

API: POST /channel/inhibit/rule/create (channelInhibitRuleCreate)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --description string — Rule description, up to 500 characters.
  --equals []string (required) — Label keys used to pair source and target alerts.
  --is-directly-discard bool — When true, suppressed target alerts are dropped instead of merged.
  --priority int — Evaluation priority. Lower runs first.
  --rule-name string (required) — Rule name, 1 to 39 characters.
  source_filters (JSON, via --data) — Or-of-and filter tree. Each outer element is an AND group; within each group, all conditions must match.
  target_filters (JSON, via --data) — Or-of-and filter tree. Each outer element is an AND group; within each group, all conditions must match.
`,
		Example: `  flashduty channel inhibit-rule-create --data '{"channel_id":3521074710131,"description":"When a Critical alert fires, suppress matching Info alerts","equals":["labels.cluster","labels.service"],"is_directly_discard":false,"rule_name":"Suppress Info when Critical fires","source_filters":[[{"key":"severity","oper":"IN","vals":["Critical"]}]],"target_filters":[[{"key":"severity","oper":"IN","vals":["Info"]}]]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("equals") {
						body["equals"] = fEquals
					}
					if cmd.Flags().Changed("is-directly-discard") {
						body["is_directly_discard"] = fIsDirectlyDiscard
					}
					if cmd.Flags().Changed("priority") {
						body["priority"] = fPriority
					}
					if cmd.Flags().Changed("rule-name") {
						body["rule_name"] = fRuleName
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CreateInhibitRuleRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelInhibitRuleCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Rule description, up to 500 characters.")
	cmd.Flags().StringSliceVar(&fEquals, "equals", nil, "Label keys used to pair source and target alerts. (required)")
	cmd.Flags().BoolVar(&fIsDirectlyDiscard, "is-directly-discard", false, "When true, suppressed target alerts are dropped instead of merged.")
	cmd.Flags().Int64Var(&fPriority, "priority", 0, "Evaluation priority. Lower runs first.")
	cmd.Flags().StringVar(&fRuleName, "rule-name", "", "Rule name, 1 to 39 characters. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelInhibitRuleDeleteCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "inhibit-rule-delete",
		Short: "Delete inhibit rule",
		Long: `Delete inhibit rule.

Delete an inhibit rule.

API: POST /channel/inhibit/rule/delete (channelInhibitRuleDelete)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel inhibit-rule-delete --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelInhibitRuleDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/inhibit/rule/delete")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelInhibitRuleDisableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "inhibit-rule-disable",
		Short: "Disable inhibit rule",
		Long: `Disable inhibit rule.

Disable an inhibit rule without deleting it.

API: POST /channel/inhibit/rule/disable (channelInhibitRuleDisable)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel inhibit-rule-disable --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelInhibitRuleDisable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/inhibit/rule/disable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelInhibitRuleEnableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "inhibit-rule-enable",
		Short: "Enable inhibit rule",
		Long: `Enable inhibit rule.

Enable a disabled inhibit rule.

API: POST /channel/inhibit/rule/enable (channelInhibitRuleEnable)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel inhibit-rule-enable --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelInhibitRuleEnable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/inhibit/rule/enable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelInhibitRuleListCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	cmd := &cobra.Command{
		Use:   "inhibit-rule-list",
		Short: "List inhibit rules",
		Long: `List inhibit rules.

List all inhibit rules configured for a channel.

API: POST /channel/inhibit/rule/list (channelInhibitRuleList)

Request fields:
  --channel-id int (required) — Channel to list rules for.
`,
		Example: `  flashduty channel inhibit-rule-list --data '{"channel_id":1001}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelScopedListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelInhibitRuleList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel to list rules for. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelInhibitRuleUpdateCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fDescription string
	var fEquals []string
	var fIsDirectlyDiscard bool
	var fPriority int64
	var fRuleID string
	var fRuleName string
	cmd := &cobra.Command{
		Use:   "inhibit-rule-update",
		Short: "Update inhibit rule",
		Long: `Update inhibit rule.

Update an existing inhibit rule configuration.

API: POST /channel/inhibit/rule/update (channelInhibitRuleUpdate)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --description string — Rule description, up to 500 characters.
  --equals []string (required) — Label keys used to pair source and target alerts.
  --is-directly-discard bool — When true, suppressed target alerts are dropped instead of merged.
  --priority int — Evaluation priority. Lower runs first.
  --rule-id string (required) — Inhibit rule ID (MongoDB ObjectID).
  --rule-name string (required) — Rule name, 1 to 39 characters.
  source_filters (JSON, via --data)
  target_filters (JSON, via --data)
`,
		Example: `  flashduty channel inhibit-rule-update --data '{"channel_id":1001,"equals":["labels.cluster"],"rule_id":"6621b23f4a2c5e0012ab34ce","rule_name":"Suppress downstream"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("equals") {
						body["equals"] = fEquals
					}
					if cmd.Flags().Changed("is-directly-discard") {
						body["is_directly_discard"] = fIsDirectlyDiscard
					}
					if cmd.Flags().Changed("priority") {
						body["priority"] = fPriority
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					if cmd.Flags().Changed("rule-name") {
						body["rule_name"] = fRuleName
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.UpdateInhibitRuleRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelInhibitRuleUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/inhibit/rule/update")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Rule description, up to 500 characters.")
	cmd.Flags().StringSliceVar(&fEquals, "equals", nil, "Label keys used to pair source and target alerts. (required)")
	cmd.Flags().BoolVar(&fIsDirectlyDiscard, "is-directly-discard", false, "When true, suppressed target alerts are dropped instead of merged.")
	cmd.Flags().Int64Var(&fPriority, "priority", 0, "Evaluation priority. Lower runs first.")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Inhibit rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&fRuleName, "rule-name", "", "Rule name, 1 to 39 characters. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelListCmd() *cobra.Command {
	var dataJSON string
	var fP int64
	var fLimit int64
	var fSearchAfterCtx string
	var fAsc bool
	var fChannelIDs []int
	var fChannelName string
	var fIsBrief bool
	var fIsMyManaged bool
	var fIsMyStarred bool
	var fIsMyTeam bool
	var fOrderby string
	var fQuery string
	var fTeamIDs []int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List channels",
		Long: `List channels.

List channels accessible to the current user with optional filters.

API: POST /channel/list (channelList)

Request fields:
  --p int — Page number (1-based).
  --limit int — Page size. Defaults to 100 when omitted.
  --search-after-ctx string
  --asc bool — When true, sort ascending.
  --channel-ids []int — Filter by explicit channel IDs.
  --channel-name string — Exact-match filter on channel name. Takes priority over 'query' for name filtering.
  --is-brief bool — When true, return only brief fields ('channel_id', 'channel_name', 'description', 'status').
  --is-my-managed bool — When true, return only channels the caller manages.
  --is-my-starred bool — When true, return only channels the caller has starred. Mutually exclusive with 'is_my_team'.
  --is-my-team bool — When true, return channels owned by the caller's teams. Mutually exclusive with 'is_my_starred'.
  --orderby string — Field used to order results. [ranking, created_at, updated_at, channel_name, last_incident_at]
  --query string — Free-text query against channel name/description.
  --team-ids []int — Filter by team IDs.
`,
		Example: `  flashduty channel list --data '{"asc":false,"limit":20,"orderby":"created_at","p":1}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("p") {
						body["p"] = fP
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
					if cmd.Flags().Changed("search-after-ctx") {
						body["search_after_ctx"] = fSearchAfterCtx
					}
					if cmd.Flags().Changed("asc") {
						body["asc"] = fAsc
					}
					if cmd.Flags().Changed("channel-ids") {
						body["channel_ids"] = fChannelIDs
					}
					if cmd.Flags().Changed("channel-name") {
						body["channel_name"] = fChannelName
					}
					if cmd.Flags().Changed("is-brief") {
						body["is_brief"] = fIsBrief
					}
					if cmd.Flags().Changed("is-my-managed") {
						body["is_my_managed"] = fIsMyManaged
					}
					if cmd.Flags().Changed("is-my-starred") {
						body["is_my_starred"] = fIsMyStarred
					}
					if cmd.Flags().Changed("is-my-team") {
						body["is_my_team"] = fIsMyTeam
					}
					if cmd.Flags().Changed("orderby") {
						body["orderby"] = fOrderby
					}
					if cmd.Flags().Changed("query") {
						body["query"] = fQuery
					}
					if cmd.Flags().Changed("team-ids") {
						body["team_ids"] = fTeamIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ListChannelsRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fP, "p", 0, "Page number (1-based).")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size. Defaults to 100 when omitted.")
	cmd.Flags().StringVar(&fSearchAfterCtx, "search-after-ctx", "", "Request field ")
	cmd.Flags().BoolVar(&fAsc, "asc", false, "When true, sort ascending.")
	cmd.Flags().IntSliceVar(&fChannelIDs, "channel-ids", nil, "Filter by explicit channel IDs.")
	cmd.Flags().StringVar(&fChannelName, "channel-name", "", "Exact-match filter on channel name. Takes priority over `query` for name filtering.")
	cmd.Flags().BoolVar(&fIsBrief, "is-brief", false, "When true, return only brief fields (`channel_id`, `channel_name`, `description`, `status`).")
	cmd.Flags().BoolVar(&fIsMyManaged, "is-my-managed", false, "When true, return only channels the caller manages.")
	cmd.Flags().BoolVar(&fIsMyStarred, "is-my-starred", false, "When true, return only channels the caller has starred. Mutually exclusive with `is_my_team`.")
	cmd.Flags().BoolVar(&fIsMyTeam, "is-my-team", false, "When true, return channels owned by the caller's teams. Mutually exclusive with `is_my_starred`.")
	cmd.Flags().StringVar(&fOrderby, "orderby", "", "Field used to order results. [ranking, created_at, updated_at, channel_name, last_incident_at]")
	cmd.Flags().StringVar(&fQuery, "query", "", "Free-text query against channel name/description.")
	cmd.Flags().IntSliceVar(&fTeamIDs, "team-ids", nil, "Filter by team IDs.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelNotifyRuleCreateCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "notify-rule-create",
		Short: "Create channel notification rule",
		Long: `Create channel notification rule.

Create a notification rule for a channel.

API: POST /channel/notify/rule/create (channelNotifyRuleCreate)
`,
		Example: `  flashduty channel notify-rule-create --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				_, err = ctx.Client.Channels.ChannelNotifyRuleCreate(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/notify/rule/create")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelNotifyRuleDeleteCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "notify-rule-delete",
		Short: "Delete channel notification rule",
		Long: `Delete channel notification rule.

Delete a channel notification rule.

API: POST /channel/notify/rule/delete (channelNotifyRuleDelete)
`,
		Example: `  flashduty channel notify-rule-delete --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				_, err = ctx.Client.Channels.ChannelNotifyRuleDelete(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/notify/rule/delete")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelNotifyRuleDisableCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "notify-rule-disable",
		Short: "Disable channel notification rule",
		Long: `Disable channel notification rule.

Disable a channel notification rule without deleting it.

API: POST /channel/notify/rule/disable (channelNotifyRuleDisable)
`,
		Example: `  flashduty channel notify-rule-disable --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				_, err = ctx.Client.Channels.ChannelNotifyRuleDisable(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/notify/rule/disable")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelNotifyRuleEnableCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "notify-rule-enable",
		Short: "Enable channel notification rule",
		Long: `Enable channel notification rule.

Enable a disabled channel notification rule.

API: POST /channel/notify/rule/enable (channelNotifyRuleEnable)
`,
		Example: `  flashduty channel notify-rule-enable --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				_, err = ctx.Client.Channels.ChannelNotifyRuleEnable(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/notify/rule/enable")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelNotifyRuleListCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "notify-rule-list",
		Short: "List channel notification rules",
		Long: `List channel notification rules.

List all notification rules configured for a channel.

API: POST /channel/notify/rule/list (channelNotifyRuleList)
`,
		Example: `  flashduty channel notify-rule-list --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				_, err = ctx.Client.Channels.ChannelNotifyRuleList(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/notify/rule/list")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelNotifyRuleUpdateCmd() *cobra.Command {
	var dataJSON string
	cmd := &cobra.Command{
		Use:   "notify-rule-update",
		Short: "Update channel notification rule",
		Long: `Update channel notification rule.

Update an existing channel notification rule.

API: POST /channel/notify/rule/update (channelNotifyRuleUpdate)
`,
		Example: `  flashduty channel notify-rule-update --data '{}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
				})
				if err != nil {
					return err
				}
				_ = body
				_, err = ctx.Client.Channels.ChannelNotifyRuleUpdate(cmdContext(ctx.Cmd))
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/notify/rule/update")
				return nil
			})
		},
	}
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelSilenceRuleCreateCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fDescription string
	var fFromIncidentID string
	var fIsAutoDelete bool
	var fIsDirectlyDiscard bool
	var fPriority int64
	var fRuleName string
	cmd := &cobra.Command{
		Use:   "silence-rule-create",
		Short: "Create silence rule",
		Long: `Create silence rule.

Create a silence rule to suppress notifications matching specified conditions.

API: POST /channel/silence/rule/create (channelSilenceRuleCreate)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --description string — Rule description, up to 500 characters.
  --from-incident-id string — Source incident ID when the silence was created from an incident.
  --is-auto-delete bool — When true, the silence rule is automatically deleted after its time window expires. Defaults to false.
  --is-directly-discard bool — When true, silenced alerts are dropped instead of suppressed into incidents.
  --priority int — Evaluation priority. Lower runs first.
  --rule-name string (required) — Rule name, 1 to 39 characters.
  filters (JSON, via --data) — Or-of-and filter tree. Each outer element is an AND group; within each group, all conditions must match.
  time_filter (JSON, via --data) — One-off time window defined by unix seconds.
  time_filters (JSON, via --data) — Recurring time windows during which silencing applies. Mutually exclusive with 'time_filter'.
`,
		Example: `  flashduty channel silence-rule-create --data '{"channel_id":3521074710131,"description":"Silence all Info alerts during planned maintenance","filters":[[{"key":"severity","oper":"IN","vals":["Info"]}]],"is_directly_discard":false,"rule_name":"Maintenance window silence","time_filter":{"end_time":1773414000,"start_time":1773388800}}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("from-incident-id") {
						body["from_incident_id"] = fFromIncidentID
					}
					if cmd.Flags().Changed("is-auto-delete") {
						body["is_auto_delete"] = fIsAutoDelete
					}
					if cmd.Flags().Changed("is-directly-discard") {
						body["is_directly_discard"] = fIsDirectlyDiscard
					}
					if cmd.Flags().Changed("priority") {
						body["priority"] = fPriority
					}
					if cmd.Flags().Changed("rule-name") {
						body["rule_name"] = fRuleName
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CreateSilenceRuleRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelSilenceRuleCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Rule description, up to 500 characters.")
	cmd.Flags().StringVar(&fFromIncidentID, "from-incident-id", "", "Source incident ID when the silence was created from an incident.")
	cmd.Flags().BoolVar(&fIsAutoDelete, "is-auto-delete", false, "When true, the silence rule is automatically deleted after its time window expires. Defaults to false.")
	cmd.Flags().BoolVar(&fIsDirectlyDiscard, "is-directly-discard", false, "When true, silenced alerts are dropped instead of suppressed into incidents.")
	cmd.Flags().Int64Var(&fPriority, "priority", 0, "Evaluation priority. Lower runs first.")
	cmd.Flags().StringVar(&fRuleName, "rule-name", "", "Rule name, 1 to 39 characters. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelSilenceRuleDeleteCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "silence-rule-delete",
		Short: "Delete silence rule",
		Long: `Delete silence rule.

Delete a silence rule.

API: POST /channel/silence/rule/delete (channelSilenceRuleDelete)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel silence-rule-delete --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelSilenceRuleDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/silence/rule/delete")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelSilenceRuleDisableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "silence-rule-disable",
		Short: "Disable silence rule",
		Long: `Disable silence rule.

Disable a silence rule without deleting it.

API: POST /channel/silence/rule/disable (channelSilenceRuleDisable)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel silence-rule-disable --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelSilenceRuleDisable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/silence/rule/disable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelSilenceRuleEnableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "silence-rule-enable",
		Short: "Enable silence rule",
		Long: `Enable silence rule.

Enable a disabled silence rule.

API: POST /channel/silence/rule/enable (channelSilenceRuleEnable)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel silence-rule-enable --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelSilenceRuleEnable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/silence/rule/enable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelSilenceRuleListCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	cmd := &cobra.Command{
		Use:   "silence-rule-list",
		Short: "List silence rules",
		Long: `List silence rules.

List all silence rules configured for a channel.

API: POST /channel/silence/rule/list (channelSilenceRuleList)

Request fields:
  --channel-id int (required) — Channel to list rules for.
`,
		Example: `  flashduty channel silence-rule-list --data '{"channel_id":1001}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelScopedListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelSilenceRuleList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel to list rules for. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelSilenceRuleUpdateCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fDescription string
	var fIsAutoDelete bool
	var fIsDirectlyDiscard bool
	var fPriority int64
	var fRuleID string
	var fRuleName string
	cmd := &cobra.Command{
		Use:   "silence-rule-update",
		Short: "Update silence rule",
		Long: `Update silence rule.

Update an existing silence rule configuration.

API: POST /channel/silence/rule/update (channelSilenceRuleUpdate)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --description string — Rule description, up to 500 characters.
  --is-auto-delete bool — When true, the silence rule is automatically deleted after its time window expires. Defaults to false.
  --is-directly-discard bool — When true, silenced alerts are dropped instead of suppressed into incidents.
  --priority int — Evaluation priority. Lower runs first.
  --rule-id string (required) — Silence rule ID (MongoDB ObjectID).
  --rule-name string (required) — Rule name, 1 to 39 characters.
  filters (JSON, via --data)
  time_filter (JSON, via --data) — One-off time window defined by unix seconds.
  time_filters (JSON, via --data) — Recurring time windows. Mutually exclusive with 'time_filter'.
`,
		Example: `  flashduty channel silence-rule-update --data '{"channel_id":1001,"filters":[[{"key":"labels.service","oper":"IN","vals":["billing"]}]],"rule_id":"6621b23f4a2c5e0012ab34cd","rule_name":"Mute during maintenance","time_filter":{"end_time":1710086400,"start_time":1710000000}}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("is-auto-delete") {
						body["is_auto_delete"] = fIsAutoDelete
					}
					if cmd.Flags().Changed("is-directly-discard") {
						body["is_directly_discard"] = fIsDirectlyDiscard
					}
					if cmd.Flags().Changed("priority") {
						body["priority"] = fPriority
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					if cmd.Flags().Changed("rule-name") {
						body["rule_name"] = fRuleName
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.UpdateSilenceRuleRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelSilenceRuleUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/silence/rule/update")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Rule description, up to 500 characters.")
	cmd.Flags().BoolVar(&fIsAutoDelete, "is-auto-delete", false, "When true, the silence rule is automatically deleted after its time window expires. Defaults to false.")
	cmd.Flags().BoolVar(&fIsDirectlyDiscard, "is-directly-discard", false, "When true, silenced alerts are dropped instead of suppressed into incidents.")
	cmd.Flags().Int64Var(&fPriority, "priority", 0, "Evaluation priority. Lower runs first.")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Silence rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&fRuleName, "rule-name", "", "Rule name, 1 to 39 characters. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelUnsubscribeRuleCreateCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fDescription string
	var fPriority int64
	var fRuleName string
	cmd := &cobra.Command{
		Use:   "unsubscribe-rule-create",
		Short: "Create drop rule",
		Long: `Create drop rule.

Create a drop rule to filter out unwanted alerts before they become incidents.

API: POST /channel/unsubscribe/rule/create (channelUnsubscribeRuleCreate)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --description string — Rule description, up to 500 characters.
  --priority int — Evaluation priority. Lower runs first.
  --rule-name string (required) — Rule name, 1 to 39 characters.
  filters (JSON, via --data) — Or-of-and filter tree. Each outer element is an AND group; within each group, all conditions must match.
`,
		Example: `  flashduty channel unsubscribe-rule-create --data '{"channel_id":3521074710131,"description":"Discard all alerts from the test environment before they create incidents","filters":[[{"key":"labels.env","oper":"IN","vals":["test","dev"]}]],"rule_name":"Drop test environment alerts"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("priority") {
						body["priority"] = fPriority
					}
					if cmd.Flags().Changed("rule-name") {
						body["rule_name"] = fRuleName
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.CreateDropRuleRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelUnsubscribeRuleCreate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Rule description, up to 500 characters.")
	cmd.Flags().Int64Var(&fPriority, "priority", 0, "Evaluation priority. Lower runs first.")
	cmd.Flags().StringVar(&fRuleName, "rule-name", "", "Rule name, 1 to 39 characters. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelUnsubscribeRuleDeleteCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "unsubscribe-rule-delete",
		Short: "Delete drop rule",
		Long: `Delete drop rule.

Delete a drop rule.

API: POST /channel/unsubscribe/rule/delete (channelUnsubscribeRuleDelete)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel unsubscribe-rule-delete --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelUnsubscribeRuleDelete(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/unsubscribe/rule/delete")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelUnsubscribeRuleDisableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "unsubscribe-rule-disable",
		Short: "Disable drop rule",
		Long: `Disable drop rule.

Disable a drop rule without deleting it.

API: POST /channel/unsubscribe/rule/disable (channelUnsubscribeRuleDisable)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel unsubscribe-rule-disable --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelUnsubscribeRuleDisable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/unsubscribe/rule/disable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelUnsubscribeRuleEnableCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fRuleID string
	cmd := &cobra.Command{
		Use:   "unsubscribe-rule-enable",
		Short: "Enable drop rule",
		Long: `Enable drop rule.

Enable a disabled drop rule.

API: POST /channel/unsubscribe/rule/enable (channelUnsubscribeRuleEnable)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --rule-id string (required) — Rule ID (MongoDB ObjectID).
`,
		Example: `  flashduty channel unsubscribe-rule-enable --data '{"channel_id":3521074710131,"rule_id":"6621b23f4a2c5e0012ab34cd"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelRuleIDRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelUnsubscribeRuleEnable(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/unsubscribe/rule/enable")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelUnsubscribeRuleListCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	cmd := &cobra.Command{
		Use:   "unsubscribe-rule-list",
		Short: "List drop rules",
		Long: `List drop rules.

List drop rules for a channel.

API: POST /channel/unsubscribe/rule/list (channelUnsubscribeRuleList)

Request fields:
  --channel-id int (required) — Channel to list rules for.
`,
		Example: `  flashduty channel unsubscribe-rule-list --data '{"channel_id":1001}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ChannelScopedListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelUnsubscribeRuleList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel to list rules for. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelUnsubscribeRuleUpdateCmd() *cobra.Command {
	var dataJSON string
	var fChannelID int64
	var fDescription string
	var fPriority int64
	var fRuleID string
	var fRuleName string
	cmd := &cobra.Command{
		Use:   "unsubscribe-rule-update",
		Short: "Update drop rule",
		Long: `Update drop rule.

Update an existing drop rule configuration.

API: POST /channel/unsubscribe/rule/update (channelUnsubscribeRuleUpdate)

Request fields:
  --channel-id int (required) — Channel the rule belongs to.
  --description string — Rule description, up to 500 characters.
  --priority int — Evaluation priority. Lower runs first.
  --rule-id string (required) — Drop rule ID (MongoDB ObjectID).
  --rule-name string (required) — Rule name, 1 to 39 characters.
  filters (JSON, via --data)
`,
		Example: `  flashduty channel unsubscribe-rule-update --data '{"channel_id":1001,"filters":[[{"key":"labels.env","oper":"IN","vals":["test"]}]],"rule_id":"6621b23f4a2c5e0012ab34cf","rule_name":"Drop test alerts"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("priority") {
						body["priority"] = fPriority
					}
					if cmd.Flags().Changed("rule-id") {
						body["rule_id"] = fRuleID
					}
					if cmd.Flags().Changed("rule-name") {
						body["rule_name"] = fRuleName
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.UpdateDropRuleRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.ChannelUnsubscribeRuleUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /channel/unsubscribe/rule/update")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel the rule belongs to. (required)")
	cmd.Flags().StringVar(&fDescription, "description", "", "Rule description, up to 500 characters.")
	cmd.Flags().Int64Var(&fPriority, "priority", 0, "Evaluation priority. Lower runs first.")
	cmd.Flags().StringVar(&fRuleID, "rule-id", "", "Drop rule ID (MongoDB ObjectID). (required)")
	cmd.Flags().StringVar(&fRuleName, "rule-name", "", "Rule name, 1 to 39 characters. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsChannelUpdateCmd() *cobra.Command {
	var dataJSON string
	var fAutoResolveMode string
	var fAutoResolveTimeout int64
	var fChannelID int64
	var fChannelName string
	var fDescription string
	var fDisableAutoClose bool
	var fDisableOutlierDetection bool
	var fIsExternalReportEnabled bool
	var fIsPrivate bool
	var fManagingTeamIDs []int
	var fTeamID int64
	cmd := &cobra.Command{
		Use:   "update",
		Short: "Update channel",
		Long: `Update channel.

Update an existing channel's configuration and settings.

API: POST /channel/update (channelUpdate)

Request fields:
  --auto-resolve-mode string — Auto-resolve timer reset mode. [trigger, update]
  --auto-resolve-timeout int — Auto-resolve timeout in seconds. 0 disables auto-resolve. Max 30 days.
  --channel-id int (required) — Channel ID to update.
  --channel-name string — New channel name. 1 to 59 characters.
  --description string — New description. Up to 500 characters.
  --disable-auto-close bool — Disable automatic incident closing.
  --disable-outlier-detection bool — Disable outlier incident detection.
  --is-external-report-enabled bool — Allow external reporters to file incidents into this channel.
  --is-private bool — When true, the channel is visible only to its managing teams.
  --managing-team-ids []int — Additional teams that can manage the channel. Up to 3 entries.
  --team-id int — New owning team ID.
  flapping (JSON, via --data) — Flapping detection configuration.
  group (JSON, via --data) — Alert grouping configuration.
`,
		Example: `  flashduty channel update --data '{"channel_id":1001,"channel_name":"Production Alerts (v2)","description":"Updated description"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("auto-resolve-mode") {
						body["auto_resolve_mode"] = fAutoResolveMode
					}
					if cmd.Flags().Changed("auto-resolve-timeout") {
						body["auto_resolve_timeout"] = fAutoResolveTimeout
					}
					if cmd.Flags().Changed("channel-id") {
						body["channel_id"] = fChannelID
					}
					if cmd.Flags().Changed("channel-name") {
						body["channel_name"] = fChannelName
					}
					if cmd.Flags().Changed("description") {
						body["description"] = fDescription
					}
					if cmd.Flags().Changed("disable-auto-close") {
						body["disable_auto_close"] = fDisableAutoClose
					}
					if cmd.Flags().Changed("disable-outlier-detection") {
						body["disable_outlier_detection"] = fDisableOutlierDetection
					}
					if cmd.Flags().Changed("is-external-report-enabled") {
						body["is_external_report_enabled"] = fIsExternalReportEnabled
					}
					if cmd.Flags().Changed("is-private") {
						body["is_private"] = fIsPrivate
					}
					if cmd.Flags().Changed("managing-team-ids") {
						body["managing_team_ids"] = fManagingTeamIDs
					}
					if cmd.Flags().Changed("team-id") {
						body["team_id"] = fTeamID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.UpdateChannelRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.ChannelUpdate(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().StringVar(&fAutoResolveMode, "auto-resolve-mode", "", "Auto-resolve timer reset mode. [trigger, update]")
	cmd.Flags().Int64Var(&fAutoResolveTimeout, "auto-resolve-timeout", 0, "Auto-resolve timeout in seconds. 0 disables auto-resolve. Max 30 days.")
	cmd.Flags().Int64Var(&fChannelID, "channel-id", 0, "Channel ID to update. (required)")
	cmd.Flags().StringVar(&fChannelName, "channel-name", "", "New channel name. 1 to 59 characters.")
	cmd.Flags().StringVar(&fDescription, "description", "", "New description. Up to 500 characters.")
	cmd.Flags().BoolVar(&fDisableAutoClose, "disable-auto-close", false, "Disable automatic incident closing.")
	cmd.Flags().BoolVar(&fDisableOutlierDetection, "disable-outlier-detection", false, "Disable outlier incident detection.")
	cmd.Flags().BoolVar(&fIsExternalReportEnabled, "is-external-report-enabled", false, "Allow external reporters to file incidents into this channel.")
	cmd.Flags().BoolVar(&fIsPrivate, "is-private", false, "When true, the channel is visible only to its managing teams.")
	cmd.Flags().IntSliceVar(&fManagingTeamIDs, "managing-team-ids", nil, "Additional teams that can manage the channel. Up to 3 entries.")
	cmd.Flags().Int64Var(&fTeamID, "team-id", 0, "New owning team ID.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsRouteInfoCmd() *cobra.Command {
	var dataJSON string
	var fIntegrationID int64
	cmd := &cobra.Command{
		Use:   "info",
		Short: "Get routing rule detail",
		Long: `Get routing rule detail.

Retrieve the routing rule configuration for a specific integration. Returns null when the integration has no routing rule configured.

API: POST /route/info (routeInfo)

Request fields:
  --integration-id int (required) — Integration ID. Must be greater than 0.
`,
		Example: `  flashduty route info --data '{"integration_id":6113996590131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("integration-id") {
						body["integration_id"] = fIntegrationID
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.RouteInfoRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.RouteInfo(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fIntegrationID, "integration-id", 0, "Integration ID. Must be greater than 0. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsRouteListCmd() *cobra.Command {
	var dataJSON string
	var fIntegrationIDs []int
	cmd := &cobra.Command{
		Use:   "list",
		Short: "List routing rules",
		Long: `List routing rules.

Return routing rules for the specified integrations. Integrations without a configured rule are omitted from the response.

API: POST /route/list (routeList)

Request fields:
  --integration-ids []int (required) — Integration IDs to fetch routing rules for.
`,
		Example: `  flashduty route list --data '{"integration_ids":[6113996590131,6113996590132]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("integration-ids") {
						body["integration_ids"] = fIntegrationIDs
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ListRoutesRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Channels.RouteList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().IntSliceVar(&fIntegrationIDs, "integration-ids", nil, "Integration IDs to fetch routing rules for. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genChannelsRouteUpsertCmd() *cobra.Command {
	var dataJSON string
	var fIntegrationID int64
	var fVersion int64
	cmd := &cobra.Command{
		Use:   "upsert",
		Short: "Upsert routing rule",
		Long: `Upsert routing rule.

Create or update routing rules for an integration to direct alerts to specific channels. At least one of 'cases' or 'default' must be provided.

API: POST /route/upsert (routeUpsert)

Request fields:
  --integration-id int (required) — Integration the rule belongs to.
  --version int — Expected current version for optimistic concurrency control. Pass the value returned by the latest read.
  cases (JSON, via --data) — Ordered list of case branches. Cases are evaluated top to bottom.
  default (JSON, via --data) — Default branch used when no case matches (or all matched cases yield no valid channels).
  sections (JSON, via --data) — Optional sections that group consecutive cases for display.
`,
		Example: `  flashduty route upsert --data '{"cases":[{"channel_ids":[3521074710131],"fallthrough":false,"if":[{"key":"severity","oper":"IN","vals":["Critical"]}],"routing_mode":"standard"}],"default":{"channel_ids":[3521074710131]},"integration_id":6113996590131}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("integration-id") {
						body["integration_id"] = fIntegrationID
					}
					if cmd.Flags().Changed("version") {
						body["version"] = fVersion
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.UpsertRouteRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				_, err = ctx.Client.Channels.RouteUpsert(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				ctx.WriteResult("OK: POST /route/upsert")
				return nil
			})
		},
	}
	cmd.Flags().Int64Var(&fIntegrationID, "integration-id", 0, "Integration the rule belongs to. (required)")
	cmd.Flags().Int64Var(&fVersion, "version", 0, "Expected current version for optimistic concurrency control. Pass the value returned by the latest read.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func registerGeneratedChannels(root *cobra.Command) {
	gChannel := genGroup(root, "channel", "On-call/Channels API")
	genAddLeaf(gChannel, genChannelsChannelCreateCmd())
	genAddLeaf(gChannel, genChannelsChannelDeleteCmd())
	genAddLeaf(gChannel, genChannelsChannelDisableCmd())
	genAddLeaf(gChannel, genChannelsChannelEnableCmd())
	genAddLeaf(gChannel, genChannelsChannelEscalateRuleCreateCmd())
	genAddLeaf(gChannel, genChannelsChannelEscalateRuleDeleteCmd())
	genAddLeaf(gChannel, genChannelsChannelEscalateRuleDisableCmd())
	genAddLeaf(gChannel, genChannelsChannelEscalateRuleEnableCmd())
	genAddLeaf(gChannel, genChannelsChannelEscalateRuleInfoCmd())
	genAddLeaf(gChannel, genChannelsChannelEscalateRuleListCmd())
	genAddLeaf(gChannel, genChannelsChannelEscalateRuleUpdateCmd())
	genAddLeaf(gChannel, genChannelsChannelInfoCmd())
	genAddLeaf(gChannel, genChannelsChannelInfosCmd())
	genAddLeaf(gChannel, genChannelsChannelInhibitRuleCreateCmd())
	genAddLeaf(gChannel, genChannelsChannelInhibitRuleDeleteCmd())
	genAddLeaf(gChannel, genChannelsChannelInhibitRuleDisableCmd())
	genAddLeaf(gChannel, genChannelsChannelInhibitRuleEnableCmd())
	genAddLeaf(gChannel, genChannelsChannelInhibitRuleListCmd())
	genAddLeaf(gChannel, genChannelsChannelInhibitRuleUpdateCmd())
	genAddLeaf(gChannel, genChannelsChannelListCmd())
	genAddLeaf(gChannel, genChannelsChannelNotifyRuleCreateCmd())
	genAddLeaf(gChannel, genChannelsChannelNotifyRuleDeleteCmd())
	genAddLeaf(gChannel, genChannelsChannelNotifyRuleDisableCmd())
	genAddLeaf(gChannel, genChannelsChannelNotifyRuleEnableCmd())
	genAddLeaf(gChannel, genChannelsChannelNotifyRuleListCmd())
	genAddLeaf(gChannel, genChannelsChannelNotifyRuleUpdateCmd())
	genAddLeaf(gChannel, genChannelsChannelSilenceRuleCreateCmd())
	genAddLeaf(gChannel, genChannelsChannelSilenceRuleDeleteCmd())
	genAddLeaf(gChannel, genChannelsChannelSilenceRuleDisableCmd())
	genAddLeaf(gChannel, genChannelsChannelSilenceRuleEnableCmd())
	genAddLeaf(gChannel, genChannelsChannelSilenceRuleListCmd())
	genAddLeaf(gChannel, genChannelsChannelSilenceRuleUpdateCmd())
	genAddLeaf(gChannel, genChannelsChannelUnsubscribeRuleCreateCmd())
	genAddLeaf(gChannel, genChannelsChannelUnsubscribeRuleDeleteCmd())
	genAddLeaf(gChannel, genChannelsChannelUnsubscribeRuleDisableCmd())
	genAddLeaf(gChannel, genChannelsChannelUnsubscribeRuleEnableCmd())
	genAddLeaf(gChannel, genChannelsChannelUnsubscribeRuleListCmd())
	genAddLeaf(gChannel, genChannelsChannelUnsubscribeRuleUpdateCmd())
	genAddLeaf(gChannel, genChannelsChannelUpdateCmd())
	gRoute := genGroup(root, "route", "On-call/Channels API")
	genAddLeaf(gRoute, genChannelsRouteInfoCmd())
	genAddLeaf(gRoute, genChannelsRouteListCmd())
	genAddLeaf(gRoute, genChannelsRouteUpsertCmd())
}
