// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genDiagnosticsQueryDiagnoseCmd() *cobra.Command {
	var dataJSON string
	var fAccountID int64
	var fDsName string
	var fDsType string
	var fOperation string
	cmd := &cobra.Command{
		Use:   "query-diagnose",
		Short: "Diagnose data source",
		Long: `Diagnose data source.

Run a synchronous diagnostic query ('log_patterns' for Loki/VictoriaLogs, 'metric_trends' for Prometheus). Used by Flashduty AI SRE for log-pattern clustering and time-series trend analysis. Long-running — up to 35 s.

API: POST /monit/query/diagnose (monit-read-query-diagnose)

Request fields:
  --account-id int — Optional consistency check. Must equal the authenticated account when supplied.
  --ds-name string (required) — Data source name configured under the tenant.
  --ds-type string (required) — Data source type. 'log_patterns' supports 'loki' and 'victorialogs'; 'metric_trends' supports 'prometheus'.
  --operation string — Diagnostic operation. When omitted, inferred from 'ds_type' (loki / victorialogs → 'log_patterns', prometheus → 'metric_trends'). Other sources must specify explicitly. [log_patterns, metric_trends]
  input (JSON, via --data) (required)
  methods (JSON, via --data) — Diagnostic methods to run. When omitted, 'log_patterns' defaults to 'pattern_snapshot + pattern_compare(previous_window)' and 'metric_trends' defaults to 'single_window_shape + window_compare(previous_window)'.
  options (JSON, via --data) — Execution options, all upper-bounded by monit-edge.
  time_range (JSON, via --data) — Diagnostic window in Unix seconds. Defaults to the last 15 minutes when missing or invalid; windows wider than 6 hours are rejected.
`,
		Example: `  flashduty monit query-diagnose --data '{"account_id":10001,"ds_name":"vmlogs-read","ds_type":"victorialogs","input":{"query":"_stream:{status='500'}"},"methods":[{"name":"pattern_snapshot"},{"baseline":"same_window_yesterday","name":"pattern_compare"}],"operation":"log_patterns","options":{"examples_per_pattern":2,"max_logs_scanned":10000,"max_patterns":20,"timeout_seconds":25},"time_range":{"end":1776849344,"start":1776847544}}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("account-id") {
						body["account_id"] = fAccountID
					}
					if cmd.Flags().Changed("ds-name") {
						body["ds_name"] = fDsName
					}
					if cmd.Flags().Changed("ds-type") {
						body["ds_type"] = fDsType
					}
					if cmd.Flags().Changed("operation") {
						body["operation"] = fOperation
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.DiagnoseRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Diagnostics.QueryDiagnose(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fAccountID, "account-id", 0, "Optional consistency check. Must equal the authenticated account when supplied.")
	cmd.Flags().StringVar(&fDsName, "ds-name", "", "Data source name configured under the tenant. (required)")
	cmd.Flags().StringVar(&fDsType, "ds-type", "", "Data source type. `log_patterns` supports `loki` and `victorialogs`; `metric_trends` supports `prometheus`. (required)")
	cmd.Flags().StringVar(&fOperation, "operation", "", "Diagnostic operation. When omitted, inferred from `ds_type` (loki / victorialogs → `log_patterns`, prometheus → `metric_trends`). Other sources must specify explicitly. [log_patterns, metric_trends]")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genDiagnosticsQueryRowsCmd() *cobra.Command {
	var dataJSON string
	var fAccountID int64
	var fDelaySeconds int64
	var fDsName string
	var fDsType string
	var fExpr string
	cmd := &cobra.Command{
		Use:   "query-rows",
		Short: "Query data source rows",
		Long: `Query data source rows.

Run a synchronous ad-hoc query against a configured data source and get back its raw rows. Used by Flashduty AI SRE and by UI preview. The request is forwarded over WebSocket to monit-edge, which executes the query against the underlying source (Prometheus / Loki / VictoriaLogs / SLS / MySQL / Postgres / Oracle / ClickHouse / Elasticsearch).

API: POST /monit/query/rows (monit-read-query-rows)

Request fields:
  --account-id int — Optional consistency check. Must equal the authenticated account when supplied; mismatched values are rejected. Business execution always uses the authenticated account.
  --delay-seconds int — Look-back offset in seconds applied to point-in-time queries (Prometheus, Loki stats, VictoriaLogs stats). Ignored for raw / detail queries.
  --ds-name string (required) — Data source name; must match a configured data source under the tenant.
  --ds-type string (required) — Data source type; must match a configured data source under the tenant. Examples: 'prometheus', 'loki', 'victorialogs', 'sls', 'elasticsearch', 'mysql', 'postgres', 'oracle', 'clickhouse'.
  --expr string (required) — Query expression. Syntax depends on 'ds_type' and is interpreted by the corresponding monit-edge client (PromQL for Prometheus, LogQL for Loki, SQL for SQL sources, etc.).
  args (JSON, via --data) — Polymorphic key/value extension parameters forwarded verbatim to monit-edge. All values must be strings. Semantics depend on 'ds_type': SLS requires 'sls.project' + 'sls.logstore'; Loki / VictoriaLogs raw mode requires a time range via '<source>.start'/'<source>.end' or '<source>.timespan.value' + '<source>.timespan.unit'; Prometheus and SQL sources ignore it. Always namespace keys by source (e.g. 'sls.project', 'loki.type').
`,
		Example: `  flashduty monit query-rows --data '{"account_id":10001,"delay_seconds":30,"ds_name":"prod-prom","ds_type":"prometheus","expr":"up"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("account-id") {
						body["account_id"] = fAccountID
					}
					if cmd.Flags().Changed("delay-seconds") {
						body["delay_seconds"] = fDelaySeconds
					}
					if cmd.Flags().Changed("ds-name") {
						body["ds_name"] = fDsName
					}
					if cmd.Flags().Changed("ds-type") {
						body["ds_type"] = fDsType
					}
					if cmd.Flags().Changed("expr") {
						body["expr"] = fExpr
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.QueryRowsRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Diagnostics.QueryRows(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fAccountID, "account-id", 0, "Optional consistency check. Must equal the authenticated account when supplied; mismatched values are rejected. Business execution always uses the authenticated account.")
	cmd.Flags().Int64Var(&fDelaySeconds, "delay-seconds", 0, "Look-back offset in seconds applied to point-in-time queries (Prometheus, Loki stats, VictoriaLogs stats). Ignored for raw / detail queries.")
	cmd.Flags().StringVar(&fDsName, "ds-name", "", "Data source name; must match a configured data source under the tenant. (required)")
	cmd.Flags().StringVar(&fDsType, "ds-type", "", "Data source type; must match a configured data source under the tenant. Examples: `prometheus`, `loki`, `victorialogs`, `sls`, `elasticsearch`, `mysql`, `postgres`, `oracle`, `clickhouse`. (required)")
	cmd.Flags().StringVar(&fExpr, "expr", "", "Query expression. Syntax depends on `ds_type` and is interpreted by the corresponding monit-edge client (PromQL for Prometheus, LogQL for Loki, SQL for SQL sources, etc.). (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genDiagnosticsTargetsListCmd() *cobra.Command {
	var dataJSON string
	var fAccountID int64
	var fCursor string
	var fKeyword string
	var fLimit int64
	cmd := &cobra.Command{
		Use:   "targets",
		Short: "List monitored targets",
		Long: `List monitored targets.

List the targets observed under the current tenant by the monit-agent route projection. Supports 'target_locator' prefix search and cursor pagination. Use this to drive 'target_locator' selection for '/monit/tools/catalog' and '/monit/tools/invoke'.

API: POST /monit/targets (monit-read-targets-list)

Request fields:
  --account-id int — Optional consistency check. Must equal the authenticated account when supplied.
  --cursor string — Opaque pagination cursor from the previous response's 'next_cursor'. Omit / pass empty string for the first page. Reset whenever 'keyword', 'limit', or tenant changes.
  --keyword string — Prefix match against 'target_locator'. ASCII only, no whitespace, no '|', max 256 bytes. Substring search is not supported.
  --limit int — Page size. Default 50, max 200.
`,
		Example: `  flashduty monit targets --data '{"keyword":"db-prod","limit":50}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("account-id") {
						body["account_id"] = fAccountID
					}
					if cmd.Flags().Changed("cursor") {
						body["cursor"] = fCursor
					}
					if cmd.Flags().Changed("keyword") {
						body["keyword"] = fKeyword
					}
					if cmd.Flags().Changed("limit") {
						body["limit"] = fLimit
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.TargetsListRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Diagnostics.TargetsList(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fAccountID, "account-id", 0, "Optional consistency check. Must equal the authenticated account when supplied.")
	cmd.Flags().StringVar(&fCursor, "cursor", "", "Opaque pagination cursor from the previous response's `next_cursor`. Omit / pass empty string for the first page. Reset whenever `keyword`, `limit`, or tenant changes.")
	cmd.Flags().StringVar(&fKeyword, "keyword", "", "Prefix match against `target_locator`. ASCII only, no whitespace, no `|`, max 256 bytes. Substring search is not supported.")
	cmd.Flags().Int64Var(&fLimit, "limit", 0, "Page size. Default 50, max 200.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genDiagnosticsToolsCatalogCmd() *cobra.Command {
	var dataJSON string
	var fAccountID int64
	var fIncludeOutputShape bool
	var fTargetKind string
	var fTargetLocator string
	cmd := &cobra.Command{
		Use:   "tools-catalog",
		Short: "List target tool catalog",
		Long: `List target tool catalog.

Look up the tools that the per-target monit-agent currently exposes for a given 'target_locator' (host, mysql, …). Returns each tool's name, description, and JSON-Schema 'input_schema'. Pair with '/monit/tools/invoke' to drive AI-SRE tool calls.

API: POST /monit/tools/catalog (monit-read-tools-catalog)

Request fields:
  --account-id int — Optional consistency check. Must equal the authenticated account when supplied.
  --include-output-shape bool — When true, each tool entry includes its 'output_shape' JSON Schema. Defaults to false to keep responses small for LLM consumption.
  --target-kind string — Optional target kind. When omitted webapi auto-infers across currently known kinds. Built-in kinds: 'host', 'mysql'. Required on retry when the previous call returned 'ambiguous_target_kind'.
  --target-locator string (required) — Target identifier (host name, MySQL address, …). Max 256 bytes; no whitespace, control characters, or '|'.
`,
		Example: `  flashduty monit tools-catalog --data '{"account_id":10001,"include_output_shape":true,"target_locator":"web-01"}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("account-id") {
						body["account_id"] = fAccountID
					}
					if cmd.Flags().Changed("include-output-shape") {
						body["include_output_shape"] = fIncludeOutputShape
					}
					if cmd.Flags().Changed("target-kind") {
						body["target_kind"] = fTargetKind
					}
					if cmd.Flags().Changed("target-locator") {
						body["target_locator"] = fTargetLocator
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ToolCatalogRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Diagnostics.ToolsCatalog(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fAccountID, "account-id", 0, "Optional consistency check. Must equal the authenticated account when supplied.")
	cmd.Flags().BoolVar(&fIncludeOutputShape, "include-output-shape", false, "When true, each tool entry includes its `output_shape` JSON Schema. Defaults to false to keep responses small for LLM consumption.")
	cmd.Flags().StringVar(&fTargetKind, "target-kind", "", "Optional target kind. When omitted webapi auto-infers across currently known kinds. Built-in kinds: `host`, `mysql`. Required on retry when the previous call returned `ambiguous_target_kind`.")
	cmd.Flags().StringVar(&fTargetLocator, "target-locator", "", "Target identifier (host name, MySQL address, …). Max 256 bytes; no whitespace, control characters, or `|`. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func genDiagnosticsToolsInvokeCmd() *cobra.Command {
	var dataJSON string
	var fAccountID int64
	var fTargetKind string
	var fTargetLocator string
	cmd := &cobra.Command{
		Use:   "tools-invoke",
		Short: "Invoke target tools",
		Long: `Invoke target tools.

Invoke up to 8 monit-agent tools concurrently on a single target. Results come back in the order of the input 'tools' array. Long-running — individual tools have per-tool timeouts on the agent and the whole request may take tens of seconds.

API: POST /monit/tools/invoke (monit-read-tools-invoke)

Request fields:
  --account-id int — Optional consistency check. Must equal the authenticated account when supplied.
  --target-kind string — Optional target kind; auto-inferred when omitted.
  --target-locator string (required) — Target identifier. Same validation rules as '/monit/tools/catalog'.
  tools (JSON, via --data) (required) — Up to 8 tool calls; webapi executes them concurrently and returns results in input order.
`,
		Example: `  flashduty monit tools-invoke --data '{"account_id":10001,"target_locator":"web-01","tools":[{"params":{},"tool":"os.overview"},{"params":{"host":"10.0.0.10","port":3306},"tool":"net.tcp_ping"}]}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) {
					if cmd.Flags().Changed("account-id") {
						body["account_id"] = fAccountID
					}
					if cmd.Flags().Changed("target-kind") {
						body["target_kind"] = fTargetKind
					}
					if cmd.Flags().Changed("target-locator") {
						body["target_locator"] = fTargetLocator
					}
				})
				if err != nil {
					return err
				}
				req := new(flashduty.ToolInvokeRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Diagnostics.ToolsInvoke(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().Int64Var(&fAccountID, "account-id", 0, "Optional consistency check. Must equal the authenticated account when supplied.")
	cmd.Flags().StringVar(&fTargetKind, "target-kind", "", "Optional target kind; auto-inferred when omitted.")
	cmd.Flags().StringVar(&fTargetLocator, "target-locator", "", "Target identifier. Same validation rules as `/monit/tools/catalog`. (required)")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; typed flags override its fields")
	return cmd
}

func registerGeneratedDiagnostics(root *cobra.Command) {
	gMonit := genGroup(root, "monit", "Monitors API")
	genAddLeaf(gMonit, genDiagnosticsQueryDiagnoseCmd())
	genAddLeaf(gMonit, genDiagnosticsQueryRowsCmd())
	genAddLeaf(gMonit, genDiagnosticsTargetsListCmd())
	genAddLeaf(gMonit, genDiagnosticsToolsCatalogCmd())
	genAddLeaf(gMonit, genDiagnosticsToolsInvokeCmd())
}
