// Code generated by internal/cmd/cligen; DO NOT EDIT.

package cli

import (
	"github.com/spf13/cobra"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

func genResourcesInfoCmd() *cobra.Command {
	var dataJSON string
	var fNoCache bool
	cmd := &cobra.Command{
		Use:   "resource-info",
		Short: "Get RUM resource info",
		Long: `Get RUM resource info.

Return the account's RUM resource record and its current session usage.

API: POST /rum/resource/info (rum-resource-read-info)

Request fields:
  --no-cache bool — Bypass the short-lived cache of the resource record (plan version, quotas, status) and read it from source. Does not refresh the usage counts. Default 'false'.

Response fields ('data' envelope is unwrapped — these fields are at the top level):
  - account_id (integer) (required) — Account ID that owns this resource.
  - action.days (integer) (required) — Retention period in days for action (user interaction) data.
  - created_at (string) (required) — Unix timestamp in seconds when the resource was created. Also anchors the start of the first billing window. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value stays the bare integer 0.
  - error.days (integer) (required) — Retention period in days for error data.
  - expired_at (string) — Unix timestamp in seconds when the on-premises license expires. Only present on on-premises deployments; omitted entirely for SaaS accounts. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value stays the bare integer 0.
  - long_task.days (integer) (required) — Retention period in days for long-task data.
  - offering_id (integer) (required) — ID of the offering (SKU) this resource was provisioned from.
  - order_id (string) (required) — ID of the order that provisioned this resource. Empty for resources provisioned outside the order flow (e.g. on-premises).
  - product (string) (required) — Product code for this resource. Always 'rum' for this endpoint. [rum]
  - resource.days (integer) (required) — Retention period in days for resource (network request) data.
  - resource_id (string) (required) — Unique resource identifier for the account's RUM resource.
  - resource_name (string) (required) — Display name of the resource.
  - session.days (integer) (required) — Retention period in days for session data.
  - session_investigate.free_cnt (integer) (required) — Free quota for investigate sessions per application, per billing window.
  - session_investigate.used_cnt (integer) (required) — Number of investigate (error tracking) sessions used in the current billing window.
  - session_limit_reached (boolean) (required) — 'true' when a 'version=free' account has exceeded its combined free session quota across all applications. Always 'false' for non-free plans.
  - session_measure.free_cnt (integer) (required) — Free quota for measure sessions per application, per billing window.
  - session_measure.used_cnt (integer) (required) — Number of measure (performance) sessions used in the current billing window.
  - session_replay.free_cnt (integer) (required) — Free quota for session-replay sessions per application, per billing window.
  - session_replay.used_cnt (integer) (required) — Number of session-replay sessions used in the current billing window.
  - status (string) (required) — Status of the resource. A resource with status 'deleted' or 'destroyed' never reaches this field — the operation returns 'ResourceNotFound' for those instead. [enabled, disabled]
  - updated_at (string) (required) — Unix timestamp in seconds when the resource was last updated. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value stays the bare integer 0.
  - version (string) (required) — Plan version of this resource. [free, professional]
  - view.days (integer) (required) — Retention period in days for view (page/screen) data.
  - window_end_time (string) (required) — Unix timestamp in seconds for the end of the current 30-day billing window. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value stays the bare integer 0.
  - window_start_time (string) (required) — Unix timestamp in seconds for the start of the current 30-day billing window. CLI '--json' renders this as an RFC3339 string in the process's local timezone (NOT UTC, and NOT the wire integer); an unset value stays the bare integer 0.
`,
		Example: `  flashduty rum resource-info --data '{"no_cache":false}'`,
		RunE: func(cmd *cobra.Command, args []string) error {
			return runCommand(cmd, args, func(ctx *RunContext) error {
				body, err := genAssembleBody(dataJSON, func(body map[string]any) error {
					if cmd.Flags().Changed("no-cache") {
						body["no_cache"] = fNoCache
					}
					return nil
				})
				if err != nil {
					return err
				}
				req := new(flashduty.RUMResourceInfoRequest)
				if err := genBindBody(body, req); err != nil {
					return err
				}
				out, _, err := ctx.Client.Resources.Info(cmdContext(ctx.Cmd), req)
				if err != nil {
					return err
				}
				return printGenericResult(ctx, out)
			})
		},
	}
	cmd.Flags().BoolVar(&fNoCache, "no-cache", false, "Bypass the short-lived cache of the resource record (plan version, quotas, status) and read it from source. Does not refresh the usage counts. Default 'false'.")
	cmd.Flags().StringVar(&dataJSON, "data", "", "Full request body as JSON; positional arguments and typed flags override its fields. Accepts inline JSON, or - to read stdin.")
	return cmd
}

func registerGeneratedResources(root *cobra.Command) {
	gRUM := genGroup(root, "rum", "RUM API")
	genAddLeaf(gRUM, genResourcesInfoCmd())
}
