// Command cligen generates cobra commands for every Flashduty OpenAPI operation
// not already owned by a hand-curated command, so the CLI covers the full API
// surface and every command's --help is sourced from the API description.
//
// It mirrors go-flashduty's own generator: it reads the SAME vendored spec (from
// the linked go-flashduty module) and reuses naming.go so each generated command
// targets the exact typed SDK method. Structure (method name, request type, data
// return) is read by REFLECTING the compiled SDK — authoritative and always in
// sync; help text (summaries, field descriptions, examples) is read from the
// spec. Run: `go run ./internal/cmd/cligen` from the repo root.
package main

import (
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"reflect"
	"sort"
	"strings"

	flashduty "github.com/flashcatcloud/go-flashduty"
)

const genHeader = "// Code generated by internal/cmd/cligen; DO NOT EDIT.\n\n"

func main() {
	only := ""
	for i, a := range os.Args[1:] {
		if a == "--only" && i+1 < len(os.Args[1:]) {
			only = os.Args[1:][i+1]
		}
	}
	if err := run(only); err != nil {
		fmt.Fprintln(os.Stderr, "cligen:", err)
		os.Exit(1)
	}
}

func run(only string) error {
	specPath, err := specPath()
	if err != nil {
		return err
	}
	spec, err := loadSpec(specPath)
	if err != nil {
		return err
	}
	sdk := reflectSDK()

	root, err := repoRoot()
	if err != nil {
		return err
	}
	genDir := filepath.Join(root, "internal", "cli")

	// On a full run, clear stale generated files first so a service that lost
	// operations leaves no orphan zz_generated_*.go behind.
	if only == "" {
		if err := cleanGenerated(genDir); err != nil {
			return err
		}
	}

	// Generate a path-derived command for EVERY operation. Curated commands win
	// on an exact name match at registration (genAddLeaf), so a generated twin of
	// a curated command is harmlessly dropped while the curated one keeps the
	// path-name; curated commands at a different (ergonomic) name coexist as
	// extras. This guarantees every API path has a command at its path-name.
	services := collectServices(asMap(spec["paths"]), asMap(asMap(spec["components"])["schemas"]))
	groupShorts := computeGroupShorts(services)

	var registered []string
	var generatedOpIDs []string
	emitted := 0
	for _, s := range services {
		if only != "" && !strings.Contains(s.Tag, only) {
			continue
		}
		src, n, opIDs := emitService(s, sdk, groupShorts)
		if n == 0 {
			continue
		}
		if err := writeGo(filepath.Join(genDir, "zz_generated_"+fileName(s.Name)+".go"), src); err != nil {
			return err
		}
		registered = append(registered, s.Name)
		generatedOpIDs = append(generatedOpIDs, opIDs...)
		emitted += n
	}

	if err := writeGo(filepath.Join(genDir, "zz_generated_register.go"), emitRegister(registered)); err != nil {
		return err
	}
	// The coverage manifest is only authoritative on a full run.
	if only == "" {
		if err := writeGo(filepath.Join(genDir, "zz_generated_manifest.go"), emitManifest(generatedOpIDs)); err != nil {
			return err
		}
		// Response-help table covers ALL services so curated commands can look up
		// any method; only complete on a full run.
		if err := writeGo(filepath.Join(genDir, "zz_generated_response_help.go"), emitResponseHelp(services)); err != nil {
			return err
		}
	}
	fmt.Printf("cligen: %d services, %d generated commands\n", len(registered), emitted)
	return nil
}

// cleanGenerated removes all zz_generated_*.go files so a full run starts from
// a clean slate (orphan files from removed services don't linger).
func cleanGenerated(genDir string) error {
	entries, err := os.ReadDir(genDir)
	if err != nil {
		return err
	}
	for _, e := range entries {
		if !e.IsDir() && strings.HasPrefix(e.Name(), "zz_generated_") && strings.HasSuffix(e.Name(), ".go") {
			if err := os.Remove(filepath.Join(genDir, e.Name())); err != nil {
				return err
			}
		}
	}
	return nil
}

// ---- spec model ------------------------------------------------------------

type service struct {
	Name string // Go service field on Client, e.g. "Calendars"
	Tag  string
	Ops  []specOp
}

type specOp struct {
	OpID     string
	Method   string // Go SDK method name
	HTTP     string
	Path     string
	Summary  string
	Desc     string
	Example  string        // compact request-body example JSON, "" if none
	Fields   []specField   // flat top-level request fields (drives flag help)
	ReqTree  []schemaField // full nested request body tree (for --data expansion)
	RespTree []schemaField // 200 response `data` field tree (output shape)
	// RespArray is true when the 200 `data` payload is itself a bare top-level
	// array (`type:array, items:$ref`) rather than an object or {items,total}
	// envelope. RespTree then holds the ROW (array-element) fields, and help must
	// document the output as a TOP-LEVEL array (`jq '.[]'`), not `under data`.
	RespArray bool
}

// schemaField is one node in a (possibly nested) request/response schema tree.
type schemaField struct {
	Wire       string
	Type       string // string,int,bool,number,object,array<object>,...
	Required   bool
	Desc       string
	Enum       []string
	Constraint string // compact bound, e.g. "max 100", "1-39 chars"
	Children   []schemaField
}

type specField struct {
	Wire       string
	Required   bool
	Desc       string
	Enum       []string
	Constraint string // compact bound, e.g. "max 100", "1-39 chars"
}

func collectServices(paths, schemas map[string]any) []service {
	walker := &specWalker{schemas: schemas}
	byTag := map[string][]struct {
		path, http string
		op         map[string]any
	}{}
	for p, item := range paths {
		for method, raw := range asMap(item) {
			m := strings.ToUpper(method)
			if m != "POST" && m != "GET" {
				continue
			}
			o := asMap(raw)
			tags := asSlice(o["tags"])
			if len(tags) == 0 {
				continue
			}
			// Streaming endpoints (200 body is not application/json, e.g.
			// session/export's application/x-ndjson) cannot be modeled by the
			// generated typed-response command: the SDK exposes them as a
			// hand-written streaming method with a non-standard signature
			// (io.ReadCloser, *Response, error), not the (out, *Response, error)
			// the template expects. Skip them here — they are covered by a
			// curated command at their path-name — mirroring go-flashduty's own
			// generator, which skips the same ops.
			if isStreamingOp(o) {
				continue
			}
			tag, _ := tags[0].(string)
			byTag[tag] = append(byTag[tag], struct {
				path, http string
				op         map[string]any
			}{p, m, o})
		}
	}

	var tagNames []string
	for t := range byTag {
		tagNames = append(tagNames, t)
	}
	sort.Strings(tagNames)

	var out []service
	for _, tag := range tagNames {
		entries := byTag[tag]
		sort.Slice(entries, func(i, j int) bool {
			return str(entries[i].op, "operationId") < str(entries[j].op, "operationId")
		})
		var opIDs []string
		for _, e := range entries {
			opIDs = append(opIDs, str(e.op, "operationId"))
		}
		names := methodNames(opIDs)
		svc := service{Name: serviceName(tag), Tag: tag}
		for _, e := range entries {
			opID := str(e.op, "operationId")
			respTree, respArray := walker.responseTree(e.op)
			svc.Ops = append(svc.Ops, specOp{
				OpID:      opID,
				Method:    names[opID],
				HTTP:      e.http,
				Path:      e.path,
				Summary:   str(e.op, "summary"),
				Desc:      str(e.op, "description"),
				Example:   walker.example(e.op),
				Fields:    walker.fields(e.op),
				ReqTree:   walker.requestTree(e.op),
				RespTree:  respTree,
				RespArray: respArray,
			})
		}
		if len(svc.Ops) > 0 {
			out = append(out, svc)
		}
	}
	return out
}

// isStreamingOp reports whether an operation's 200 response is a non-JSON
// streaming body (its 200 content has no "application/json" key, e.g.
// session/export's application/x-ndjson). Such ops cannot be modeled by a
// generated typed-response command and are served by a curated command instead.
// This mirrors go-flashduty's generator, which excludes the same ops from the
// SDK's typed do() path in favor of a hand-written streaming method.
func isStreamingOp(o map[string]any) bool {
	content := asMap(asMap(asMap(o["responses"])["200"])["content"])
	if len(content) == 0 {
		return false // no body at all is not a streaming response
	}
	_, hasJSON := content["application/json"]
	return !hasJSON
}

type specWalker struct{ schemas map[string]any }

func (w *specWalker) deref(s map[string]any) map[string]any {
	if ref := refName(s); ref != "" {
		return asMap(w.schemas[ref])
	}
	return s
}

// merged returns the flattened properties + required set of a schema, resolving
// $ref and allOf.
func (w *specWalker) merged(s map[string]any) (map[string]any, map[string]bool) {
	props := map[string]any{}
	req := map[string]bool{}
	s = w.deref(s)
	for _, part := range asSlice(s["allOf"]) {
		p, r := w.merged(asMap(part))
		for k, v := range p {
			props[k] = v
		}
		for k := range r {
			req[k] = true
		}
	}
	for k, v := range asMap(s["properties"]) {
		props[k] = v
	}
	for _, r := range asSlice(s["required"]) {
		if name, ok := r.(string); ok {
			req[name] = true
		}
	}
	return props, req
}

func (w *specWalker) fields(op map[string]any) []specField {
	var fields []specField
	if rb := asMap(op["requestBody"]); rb != nil {
		sch := asMap(asMap(asMap(rb["content"])["application/json"])["schema"])
		props, req := w.merged(sch)
		for wire, v := range props {
			pv := w.deref(asMap(v))
			fields = append(fields, specField{
				Wire:       wire,
				Required:   req[wire],
				Desc:       str(pv, "description"),
				Enum:       w.enumOf(pv),
				Constraint: constraintOf(pv),
			})
		}
	}
	for _, raw := range asSlice(op["parameters"]) {
		pm := asMap(raw)
		if str(pm, "in") != "query" {
			continue
		}
		psch := w.deref(asMap(pm["schema"]))
		fields = append(fields, specField{
			Wire:       str(pm, "name"),
			Required:   boolOf(pm["required"]),
			Desc:       str(pm, "description"),
			Enum:       w.enumOf(psch),
			Constraint: constraintOf(psch),
		})
	}
	sort.Slice(fields, func(i, j int) bool { return fields[i].Wire < fields[j].Wire })
	return fields
}

func (w *specWalker) example(op map[string]any) string {
	rb := asMap(op["requestBody"])
	if rb == nil {
		return ""
	}
	ex, ok := asMap(asMap(rb["content"])["application/json"])["example"]
	if !ok {
		return ""
	}
	b, err := json.Marshal(ex)
	if err != nil {
		return ""
	}
	return string(b)
}

// enumOf returns a schema's enum values, falling back to its array items' enum
// (so a `[]string` flag whose elements are constrained still advertises them).
func (w *specWalker) enumOf(s map[string]any) []string {
	if e := enumStrings(s); len(e) > 0 {
		return e
	}
	if str(s, "type") == "array" {
		return enumStrings(w.deref(asMap(s["items"])))
	}
	return nil
}

// schemaType renders a compact type label for a (deref'd) property schema.
func schemaType(s map[string]any) string {
	switch t := str(s, "type"); t {
	case "array":
		it := asMap(s["items"])
		et := str(it, "type")
		if et == "" && (it["properties"] != nil || it["allOf"] != nil || it["$ref"] != nil) {
			et = "object"
		}
		if et == "" {
			et = "any"
		}
		return "array<" + et + ">"
	case "":
		if s["properties"] != nil || s["allOf"] != nil || s["$ref"] != nil {
			return "object"
		}
		return "any"
	default:
		return t
	}
}

// constraintOf renders a compact bound string ("max 100", "1-39 chars", "1-100")
// from a property schema's numeric/length keywords. Agents exceeding a documented
// limit (e.g. --limit 200 when max is 100) is the single largest source of
// InvalidParameter 400s, so these bounds belong in --help alongside the type.
func constraintOf(s map[string]any) string {
	var parts []string
	mn, okMn := numStr(s["minimum"])
	mx, okMx := numStr(s["maximum"])
	switch {
	case okMn && okMx:
		parts = append(parts, mn+"-"+mx)
	case okMx:
		parts = append(parts, "max "+mx)
	case okMn:
		parts = append(parts, "min "+mn)
	}
	lmn, okLmn := numStr(s["minLength"])
	lmx, okLmx := numStr(s["maxLength"])
	switch {
	case okLmn && okLmx:
		parts = append(parts, lmn+"-"+lmx+" chars")
	case okLmx:
		parts = append(parts, "≤"+lmx+" chars")
	case okLmn:
		parts = append(parts, "≥"+lmn+" chars")
	}
	return strings.Join(parts, ", ")
}

// numStr formats a JSON number (float64 / json.Number) without a trailing ".0",
// returning ok=false for nil/non-numeric so callers can omit absent bounds.
func numStr(v any) (string, bool) {
	switch n := v.(type) {
	case float64:
		if n == float64(int64(n)) {
			return fmt.Sprintf("%d", int64(n)), true
		}
		return fmt.Sprintf("%g", n), true
	case json.Number:
		return n.String(), true
	default:
		return "", false
	}
}

// maxSchemaDepth bounds how deep request/response trees are expanded in --help.
const maxSchemaDepth = 3

// tree walks an object schema (resolving $ref/allOf) into a sorted field tree,
// recursing into nested objects and array-element objects up to maxSchemaDepth.
func (w *specWalker) tree(schema map[string]any, depth int) []schemaField {
	if depth > maxSchemaDepth {
		return nil
	}
	props, req := w.merged(schema)
	var out []schemaField
	for wire, v := range props {
		pv := w.deref(asMap(v))
		f := schemaField{
			Wire:       wire,
			Required:   req[wire],
			Desc:       str(pv, "description"),
			Enum:       enumStrings(pv),
			Type:       schemaType(pv),
			Constraint: constraintOf(pv),
		}
		switch {
		case pv["properties"] != nil || pv["allOf"] != nil:
			f.Children = w.tree(pv, depth+1)
		case str(pv, "type") == "array":
			it := w.deref(asMap(pv["items"]))
			if it["properties"] != nil || it["allOf"] != nil {
				f.Children = w.tree(it, depth+1)
			} else if len(f.Enum) == 0 {
				f.Enum = enumStrings(it) // array of constrained scalars
			}
		}
		out = append(out, f)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].Wire < out[j].Wire })
	return out
}

// requestTree returns the full nested field tree of an operation's JSON body.
func (w *specWalker) requestTree(op map[string]any) []schemaField {
	rb := asMap(op["requestBody"])
	if rb == nil {
		return nil
	}
	sch := asMap(asMap(asMap(rb["content"])["application/json"])["schema"])
	if sch == nil {
		return nil
	}
	return w.tree(sch, 0)
}

// responseTree returns the field tree of an operation's 200 response `data`
// member (unwrapping the {request_id,error,data} envelope), so --help can show
// the output shape — including the {items[],total} pagination wrapper for lists.
// The bool is true when `data` is itself a bare top-level array
// (`type:array, items:$ref`): the returned tree then holds the array-element
// (row) fields, since an array schema has no `properties` of its own and tree()
// would otherwise yield nothing — leaving every such list endpoint (e.g.
// rule-list-basic) with an empty Response-fields block that forced agents to
// guess jq keys. Callers document this shape as a TOP-LEVEL array (`jq '.[]'`).
func (w *specWalker) responseTree(op map[string]any) ([]schemaField, bool) {
	r200 := asMap(asMap(op["responses"])["200"])
	sch := asMap(asMap(asMap(r200["content"])["application/json"])["schema"])
	if sch == nil {
		return nil, false
	}
	props, _ := w.merged(sch)
	data := w.deref(asMap(props["data"]))
	if data == nil {
		return nil, false
	}
	if str(data, "type") == "array" {
		it := w.deref(asMap(data["items"]))
		if it["properties"] != nil || it["allOf"] != nil {
			return w.tree(it, 0), true
		}
		return nil, false // array of bare scalars — no row field tree to document
	}
	return w.tree(data, 0), false
}

// ---- reflection over the compiled SDK -------------------------------------

type methodInfo struct {
	ReqType string // request struct name ("" => no body param)
	HasData bool   // method returns (*Data, *Response, error)
}

// eachServiceField walks a Client value, descending into its embedded
// genServices struct, and invokes fn for every *XxxService handle with its
// field name (the service name, e.g. "Calendars").
func eachServiceField(cv reflect.Value, fn func(name string, svcType reflect.Type)) {
	ct := cv.Type()
	for i := 0; i < ct.NumField(); i++ {
		f := ct.Field(i)
		if f.Anonymous && deref(f.Type).Kind() == reflect.Struct {
			fv := cv.Field(i)
			if fv.Kind() == reflect.Pointer {
				fv = fv.Elem()
			}
			if fv.IsValid() {
				eachServiceField(fv, fn)
			}
			continue
		}
		if f.Type.Kind() == reflect.Pointer && strings.HasSuffix(f.Type.Elem().Name(), "Service") {
			fn(f.Name, f.Type)
		}
	}
}

// reflectSDK introspects a real Client so the generator targets the exact
// method/request-type names the SDK exposes, regardless of how the spec maps to
// Go identifiers.
func reflectSDK() map[string]map[string]methodInfo {
	client, err := flashduty.NewClient("cligen-dummy-key")
	if err != nil {
		panic("cligen: NewClient: " + err.Error())
	}
	out := map[string]map[string]methodInfo{}
	eachServiceField(reflect.ValueOf(client).Elem(), func(name string, svcType reflect.Type) {
		methods := map[string]methodInfo{}
		for m := 0; m < svcType.NumMethod(); m++ {
			meth := svcType.Method(m)
			mt := meth.Func.Type() // In(0)=receiver, In(1)=ctx, In(2)=*Req?
			info := methodInfo{HasData: mt.NumOut() == 3}
			if mt.NumIn() >= 3 {
				rt := mt.In(2)
				if rt.Kind() == reflect.Pointer {
					rt = rt.Elem()
				}
				info.ReqType = rt.Name()
			}
			methods[meth.Name] = info
		}
		out[name] = methods
	})
	return out
}

// reqFields reflects a request struct's flag-able scalar fields (flattening
// embedded structs) and the names of complex fields (reachable only via --data).
func reqFields(reqType string) (scalars []scalarField, complex []string) {
	if reqType == "" {
		return nil, nil
	}
	t := typeByName(reqType)
	if t == nil {
		return nil, nil
	}
	// A request type whose body is a JSON array or scalar (not an object) has no
	// flag-able fields; it is reachable only via --data.
	if deref(t).Kind() != reflect.Struct {
		return nil, nil
	}
	var walk func(t reflect.Type)
	seen := map[string]bool{}
	walk = func(t reflect.Type) {
		for i := 0; i < t.NumField(); i++ {
			f := t.Field(i)
			if f.Anonymous && deref(f.Type).Kind() == reflect.Struct {
				walk(deref(f.Type))
				continue
			}
			// POST bodies tag fields with `json`; GET query structs tag them with
			// `url` and carry NO json tag. Fall back to the url wire-name so GET
			// commands emit typed flags instead of a bare --data nobody can fill.
			wire := strings.Split(f.Tag.Get("json"), ",")[0]
			if wire == "" {
				wire = strings.Split(f.Tag.Get("url"), ",")[0]
			}
			if wire == "" || wire == "-" || seen[wire] {
				continue
			}
			seen[wire] = true
			kind, ok := scalarKind(f.Type)
			if !ok {
				complex = append(complex, wire)
				continue
			}
			scalars = append(scalars, scalarField{Wire: wire, Kind: kind})
		}
	}
	walk(deref(t))
	return scalars, complex
}

type scalarField struct {
	Wire string
	Kind string // "string","bool","int","float","[]string","[]int"
}

var typeRegistry = buildTypeRegistry()

func buildTypeRegistry() map[string]reflect.Type {
	reg := map[string]reflect.Type{}
	client, err := flashduty.NewClient("cligen-dummy-key")
	if err != nil {
		panic("cligen: NewClient: " + err.Error())
	}
	eachServiceField(reflect.ValueOf(client).Elem(), func(_ string, svcType reflect.Type) {
		for m := 0; m < svcType.NumMethod(); m++ {
			mt := svcType.Method(m).Func.Type()
			if mt.NumIn() >= 3 {
				rt := mt.In(2)
				if rt.Kind() == reflect.Pointer {
					rt = rt.Elem()
				}
				reg[rt.Name()] = rt
			}
		}
	})
	return reg
}

func typeByName(name string) reflect.Type { return typeRegistry[name] }

func deref(t reflect.Type) reflect.Type {
	for t.Kind() == reflect.Pointer {
		t = t.Elem()
	}
	return t
}

func scalarKind(t reflect.Type) (string, bool) {
	t = deref(t)
	switch t.Kind() {
	case reflect.String:
		return "string", true
	case reflect.Bool:
		return "bool", true
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
		return "int", true
	case reflect.Float32, reflect.Float64:
		return "float", true
	case reflect.Slice:
		switch deref(t.Elem()).Kind() {
		case reflect.String:
			return "[]string", true
		case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
			reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64:
			return "[]int", true
		}
	}
	return "", false
}

// ---- emission --------------------------------------------------------------

func emitService(s service, sdk map[string]map[string]methodInfo, groupShorts map[string]string) (string, int, []string) {
	var cmds strings.Builder
	methods := sdk[s.Name]
	var register strings.Builder
	fmt.Fprintf(&register, "func registerGenerated%s(root *cobra.Command) {\n", s.Name)

	n := 0
	usesFlashduty := false
	var opIDs []string
	groups := map[string]string{} // group name -> Go var expr
	for _, o := range s.Ops {
		mi, ok := methods[o.Method]
		if !ok {
			// Method not found by reflection (naming drift); skip rather than emit broken code.
			fmt.Fprintf(os.Stderr, "cligen: WARN %s.%s (%s) not found on SDK; skipped\n", s.Name, o.Method, o.OpID)
			continue
		}
		if mi.ReqType != "" {
			usesFlashduty = true
		}
		fn := "gen" + s.Name + o.Method + "Cmd"
		cmds.WriteString(emitCmd(fn, s, o, mi))
		// Registration is a flat two-level tree: the first path segment is the
		// top-level group (find-or-create — generated ops merge into the curated
		// group of the same name), and the remaining segments hyphen-join into
		// the leaf verb. Flattening guarantees no operation is both a runnable
		// leaf and a parent group, so prefix-nested paths (e.g. /monit/rule/update
		// and /monit/rule/update/fields) never collide.
		group := cliGroup(o.Path)
		parentVar, done := groups[group]
		if !done {
			parentVar = "g" + sanitize(group)
			fmt.Fprintf(&register, "\t%s := genGroup(root, %q, %q)\n", parentVar, group, groupShorts[group])
			groups[group] = parentVar
		}
		fmt.Fprintf(&register, "\tgenAddLeaf(%s, %s())\n", parentVar, fn)
		n++
		opIDs = append(opIDs, o.OpID)
	}
	register.WriteString("}\n")

	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("package cli\n\n")
	if usesFlashduty {
		b.WriteString("import (\n\t\"github.com/spf13/cobra\"\n\n\tflashduty \"github.com/flashcatcloud/go-flashduty\"\n)\n\n")
	} else {
		b.WriteString("import \"github.com/spf13/cobra\"\n\n")
	}
	b.WriteString(cmds.String())
	b.WriteString(register.String())
	return b.String(), n, opIDs
}

func emitCmd(fn string, s service, o specOp, mi methodInfo) string {
	scalars, complexFields := reqFields(mi.ReqType)
	// Spec metadata by wire for help + required annotation.
	specByWire := map[string]specField{}
	for _, f := range o.Fields {
		specByWire[f.Wire] = f
	}
	// Pre-compute which scalar fields are unix-seconds timestamps so the three
	// emit loops below can check a map lookup instead of re-evaluating the
	// string-scanning predicate on every iteration.
	isTime := map[string]bool{}
	for _, sf := range scalars {
		if isUnixSecondsField(sf.Wire, sf.Kind, specByWire[sf.Wire].Desc) {
			isTime[sf.Wire] = true
		}
	}

	var b strings.Builder
	fmt.Fprintf(&b, "func %s() *cobra.Command {\n", fn)
	b.WriteString("\tvar dataJSON string\n")
	for _, sf := range scalars {
		typ := goFlagType(sf.Kind)
		if isTime[sf.Wire] {
			// Relative-time flag: a string at the CLI surface ("7d"/"now"/date/
			// unix), parsed to unix seconds at runtime (see genParseTimeFlag).
			typ = "string"
		}
		fmt.Fprintf(&b, "\tvar %s %s\n", flagVar(sf.Wire), typ)
	}

	// Command literal. The leaf verb must match the name registered in
	// emitService (cliVerb), so they share the same derivation.
	verb := cliVerb(o.Path)
	fmt.Fprintf(&b, "\tcmd := &cobra.Command{\n")
	fmt.Fprintf(&b, "\t\tUse:   %q,\n", verb)
	fmt.Fprintf(&b, "\t\tShort: %q,\n", oneLine(o.Summary))
	fmt.Fprintf(&b, "\t\tLong:  %s,\n", quoteMultiline(longHelp(o, scalars, complexFields, specByWire)))
	if ex := exampleHelp(o); ex != "" {
		fmt.Fprintf(&b, "\t\tExample: %s,\n", quoteMultiline(ex))
	}
	b.WriteString("\t\tRunE: func(cmd *cobra.Command, args []string) error {\n")
	b.WriteString("\t\t\treturn runCommand(cmd, args, func(ctx *RunContext) error {\n")
	// Relative-time flags are parsed to unix seconds before body assembly,
	// mirroring the curated incident-list --since/--until handling.
	for _, sf := range scalars {
		if !isTime[sf.Wire] {
			continue
		}
		fmt.Fprintf(&b, "\t\t\t\t%s, %s, err := genParseTimeFlag(cmd, %q, %s)\n",
			parsedTimeVar(sf.Wire), okTimeVar(sf.Wire), flagName(sf.Wire), flagVar(sf.Wire))
		b.WriteString("\t\t\t\tif err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
	}
	// body assembly
	b.WriteString("\t\t\t\tbody, err := genAssembleBody(dataJSON, func(body map[string]any) {\n")
	for _, sf := range scalars {
		if isTime[sf.Wire] {
			fmt.Fprintf(&b, "\t\t\t\t\tif %s {\n\t\t\t\t\t\tbody[%q] = %s\n\t\t\t\t\t}\n",
				okTimeVar(sf.Wire), sf.Wire, parsedTimeVar(sf.Wire))
			continue
		}
		fmt.Fprintf(&b, "\t\t\t\t\tif cmd.Flags().Changed(%q) {\n\t\t\t\t\t\tbody[%q] = %s\n\t\t\t\t\t}\n",
			flagName(sf.Wire), sf.Wire, flagVar(sf.Wire))
	}
	b.WriteString("\t\t\t\t})\n")
	b.WriteString("\t\t\t\tif err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")

	call := fmt.Sprintf("ctx.Client.%s.%s(cmdContext(ctx.Cmd)", s.Name, o.Method)
	if mi.ReqType != "" {
		fmt.Fprintf(&b, "\t\t\t\treq := new(flashduty.%s)\n", mi.ReqType)
		b.WriteString("\t\t\t\tif err := genBindBody(body, req); err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
		call += ", req)"
	} else {
		b.WriteString("\t\t\t\t_ = body\n")
		call += ")"
	}

	switch {
	case mi.HasData:
		fmt.Fprintf(&b, "\t\t\t\tout, _, err := %s\n", call)
		b.WriteString("\t\t\t\tif err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
		b.WriteString("\t\t\t\treturn printGenericResult(ctx, out)\n")
	default:
		// (*Response, error): a mutation, OR an export/attachment endpoint
		// whose CSV/file body the SDK surfaces on Response.Raw. Capture the
		// response and stream Raw verbatim when present (so `> file.csv`
		// works); otherwise fall back to the canned OK acknowledgment.
		fmt.Fprintf(&b, "\t\t\t\tresp, err := %s\n", call)
		b.WriteString("\t\t\t\tif err != nil {\n\t\t\t\t\treturn err\n\t\t\t\t}\n")
		b.WriteString("\t\t\t\tif resp != nil && len(resp.Raw) > 0 {\n\t\t\t\t\treturn ctx.WriteRaw(resp.Raw)\n\t\t\t\t}\n")
		fmt.Fprintf(&b, "\t\t\t\tctx.WriteResult(%q)\n", "OK: "+o.HTTP+" "+o.Path)
		b.WriteString("\t\t\t\treturn nil\n")
	}
	b.WriteString("\t\t\t})\n\t\t},\n\t}\n")

	// flags
	for _, sf := range scalars {
		usage := flagUsage(specByWire[sf.Wire])
		if isTime[sf.Wire] {
			fmt.Fprintf(&b, "\tcmd.Flags().StringVar(&%s, %q, \"\", %q)\n",
				flagVar(sf.Wire), flagName(sf.Wire), usage+relativeTimeHint)
			continue
		}
		fmt.Fprintf(&b, "\tcmd.Flags().%s(&%s, %q, %s, %q)\n",
			flagSetter(sf.Kind), flagVar(sf.Wire), flagName(sf.Wire), flagZero(sf.Kind), usage)
	}
	b.WriteString("\tcmd.Flags().StringVar(&dataJSON, \"data\", \"\", \"Full request body as JSON; typed flags override its fields. Accepts inline JSON, or - to read stdin.\")\n")
	b.WriteString("\treturn cmd\n}\n\n")
	return b.String()
}

func emitRegister(services []string) string {
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("package cli\n\n")
	b.WriteString("import \"github.com/spf13/cobra\"\n\n")
	b.WriteString("// registerGenerated attaches every generated command group to root. Called\n// from root.go init() after curated commands so curated leaves win on conflict.\n")
	b.WriteString("func registerGenerated(root *cobra.Command) {\n")
	for _, s := range services {
		fmt.Fprintf(&b, "\tregisterGenerated%s(root)\n", s)
	}
	b.WriteString("}\n")
	return b.String()
}

// emitManifest records every operationId that has a generated command, for the
// coverage test to assert the generator targets the full spec (one path-derived
// command per operation).
func emitManifest(generated []string) string {
	sort.Strings(generated)
	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("package cli\n\n")
	b.WriteString("// generatedOpIDs are the OpenAPI operationIds the generator emitted a\n// path-derived command for (every operation in the spec).\n")
	b.WriteString("var generatedOpIDs = []string{\n")
	for _, id := range generated {
		fmt.Fprintf(&b, "\t%q,\n", id)
	}
	b.WriteString("}\n")
	return b.String()
}

// emitResponseHelp generates a map from SDK "Service.Method" to its rendered
// Response-fields block, so curated commands (which call the same SDK methods
// under ergonomic flags) can show the same output schema as generated commands.
func emitResponseHelp(services []service) string {
	type kv struct{ k, v string }
	var rows []kv
	for _, s := range services {
		for _, o := range s.Ops {
			// Curated commands read this map. Every curated list command
			// flattens its {items,total} envelope to a top-level array, so they
			// need the flattened ("jq '.[]'") shape, not the wire envelope. An
			// endpoint whose `data` is already a bare top-level array documents
			// the same `.[]` shape directly from its row fields.
			sec := responseSectionList(o.RespTree)
			if o.RespArray {
				sec = responseSectionTopArray(o.RespTree)
			}
			if sec == "" {
				continue
			}
			rows = append(rows, kv{s.Name + "." + o.Method, sec})
		}
	}
	sort.Slice(rows, func(i, j int) bool { return rows[i].k < rows[j].k })

	var b strings.Builder
	b.WriteString(genHeader)
	b.WriteString("package cli\n\n")
	b.WriteString("// responseHelpBySDKMethod maps an SDK \"Service.Method\" to its rendered\n// Response-fields help block. Curated commands look this up via responseHelp()\n// so they document the same output shape as the generated commands.\n")
	b.WriteString("var responseHelpBySDKMethod = map[string]string{\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "\t%q: %q,\n", r.k, r.v)
	}
	b.WriteString("}\n")
	return b.String()
}

// ---- help text -------------------------------------------------------------

func longHelp(o specOp, scalars []scalarField, complexFields []string, byWire map[string]specField) string {
	var b strings.Builder
	if o.Summary != "" {
		b.WriteString(strings.TrimSuffix(o.Summary, ".") + ".\n")
	}
	if o.Desc != "" && o.Desc != o.Summary {
		b.WriteString("\n" + o.Desc + "\n")
	}
	fmt.Fprintf(&b, "\nAPI: %s %s (%s)\n", o.HTTP, o.Path, o.OpID)
	if len(scalars) > 0 || len(complexFields) > 0 {
		b.WriteString("\nRequest fields:\n")
		for _, sf := range scalars {
			f := byWire[sf.Wire]
			req := ""
			if f.Required {
				req = " (required)"
			}
			// A unix-seconds field is a relative-time string flag at the CLI
			// surface (see emitCmd / isUnixSecondsField); document it as the type
			// the user actually passes, not the underlying int.
			isTime := isUnixSecondsField(sf.Wire, sf.Kind, f.Desc)
			kind := sf.Kind
			if isTime {
				kind = "string"
			}
			line := fmt.Sprintf("  --%s %s%s", flagName(sf.Wire), kind, req)
			if f.Desc != "" {
				line += " — " + oneLine(f.Desc)
			}
			if len(f.Enum) > 0 {
				line += " [" + strings.Join(f.Enum, ", ") + "]"
			}
			if f.Constraint != "" {
				line += " (" + f.Constraint + ")"
			}
			if isTime {
				line += relativeTimeHint
			}
			b.WriteString(line + "\n")
		}
		reqByWire := map[string]schemaField{}
		for _, n := range o.ReqTree {
			reqByWire[n.Wire] = n
		}
		for _, wire := range complexFields {
			f := byWire[wire]
			node := reqByWire[wire]
			typ := "JSON"
			if node.Type != "" {
				typ = node.Type
			}
			req := ""
			if f.Required || node.Required {
				req = " (required)"
			}
			line := fmt.Sprintf("  %s (%s, via --data)%s", wire, typ, req)
			if f.Desc != "" {
				line += " — " + oneLine(f.Desc)
			}
			b.WriteString(line + "\n")
			// Expand the nested sub-fields so the agent doesn't guess the body shape.
			renderTree(&b, node.Children, 2)
		}
	}
	// Response shape — so the agent reads/extracts output fields without guessing.
	s := responseSection(o.RespTree)
	if o.RespArray {
		s = responseSectionTopArray(o.RespTree)
	}
	if s != "" {
		b.WriteString("\n" + s)
	}
	return b.String()
}

// responseSection renders the "Response fields" help block for a response tree,
// or "" when the response has no documented schema. Shared by longHelp (embedded
// in generated commands) and emitResponseHelp (looked up by curated commands).
// listEnvelope returns the row (array-element) fields and true when resp is a
// paginated list envelope: exactly one object-array field named items/docs/list
// with only SCALAR siblings (total, p, limit, has_next_page, search_after_ctx …
// — all pagination metadata). This is the shape the backend returns under
// `data`; the CLI's curated list commands flatten it to a top-level array. The
// scalar-sibling test avoids enumerating every pagination field name.
func listEnvelope(resp []schemaField) ([]schemaField, bool) {
	var rows []schemaField
	found := false
	for _, f := range resp {
		if (f.Wire == "items" || f.Wire == "docs" || f.Wire == "list") && strings.HasPrefix(f.Type, "array") && len(f.Children) > 0 {
			if found {
				return nil, false
			}
			rows, found = f.Children, true
			continue
		}
		// Any non-row sibling must be a scalar (pagination metadata). An array
		// or object sibling means this is a richer response, not a flat list.
		if strings.HasPrefix(f.Type, "array") || f.Type == "object" || len(f.Children) > 0 {
			return nil, false
		}
	}
	return rows, found
}

// responseSection renders the Response-fields block. printGenericResult UNWRAPS
// the {request_id,error,data} envelope and prints `data`'s content at the top
// level (verified: `fduty schedule list --json | jq 'keys'` → [items,total], and
// `jq '.data'` → null). So the printed shape is `data`'s content directly — never
// nested under a `.data` key. A list envelope keeps its rows under items[]; the
// correct jq is `.items[]`, NOT `.data.items[]`.
func responseSection(resp []schemaField) string {
	if len(resp) == 0 {
		return ""
	}
	var b strings.Builder
	if _, ok := listEnvelope(resp); ok {
		b.WriteString("Response fields (`data` envelope is unwrapped — rows are nested under items[]; pipe `jq '.items[]'`, NOT `.data.items[]`):\n")
	} else {
		b.WriteString("Response fields (`data` envelope is unwrapped — these fields are at the top level):\n")
	}
	renderTree(&b, resp, 1)
	return b.String()
}

// responseSectionTopArray renders the Response-fields block for an endpoint whose
// `data` payload is itself a bare top-level array of row objects (no items[]
// wrapper) — both the generated command's raw print and a curated command emit a
// top-level array, so the documented jq path is `.[]`. rows are the
// array-element fields produced by responseTree's array descent.
func responseSectionTopArray(rows []schemaField) string {
	if len(rows) == 0 {
		return ""
	}
	var b strings.Builder
	b.WriteString("Response fields (`data` is a TOP-LEVEL array of these row objects — pipe `jq '.[]'`, NOT `.items[]`):\n")
	renderTree(&b, rows, 1)
	return b.String()
}

// responseSectionList renders the Response-fields block for a command whose
// `--json` FLATTENS a list envelope to a top-level array of row objects (every
// curated list command does this via PrintList). It documents the flattened
// shape — `jq '.[]'`, not `.items[]` — so an agent that trusts the help writes a
// jq path that actually matches the output. Non-list responses fall through to
// responseSection unchanged.
func responseSectionList(resp []schemaField) string {
	if rows, ok := listEnvelope(resp); ok {
		var b strings.Builder
		b.WriteString("Response fields (this command's `--json` is a TOP-LEVEL array of these row objects — pipe `jq '.[]'`, NOT `.items[]`):\n")
		renderTree(&b, rows, 1)
		return b.String()
	}
	return responseSection(resp)
}

// renderTree writes a schema field tree as an indented "- name (type) — desc"
// list, recursing into nested object/array-element fields. indent is in 2-space
// units (so it nests under the parent line in longHelp).
func renderTree(b *strings.Builder, fields []schemaField, indent int) {
	pad := strings.Repeat("  ", indent)
	for _, f := range fields {
		line := pad + "- " + f.Wire + " (" + f.Type + ")"
		if f.Required {
			line += " (required)"
		}
		if f.Desc != "" {
			line += " — " + oneLine(f.Desc)
		}
		if len(f.Enum) > 0 {
			line += " [" + strings.Join(f.Enum, ", ") + "]"
		}
		if f.Constraint != "" {
			line += " (" + f.Constraint + ")"
		}
		b.WriteString(line + "\n")
		renderTree(b, f.Children, indent+1)
	}
}

func exampleHelp(o specOp) string {
	if o.Example == "" {
		return ""
	}
	return "  flashduty " + cliGroup(o.Path) + " " + cliVerb(o.Path) + " --data '" + o.Example + "'"
}

func flagUsage(f specField) string {
	// Spec descriptions use Markdown code-spans (`field`). pflag's UnquoteUsage
	// treats the first backtick-quoted word as the flag's value-type placeholder,
	// rendering nonsense like "--dql sql" / "--country-code phones". Convert
	// backticks to single quotes so pflag falls back to the real type name.
	u := strings.ReplaceAll(oneLine(f.Desc), "`", "'")
	if u == "" {
		u = "Request field " + f.Wire
	}
	if f.Required {
		u += " (required)"
	}
	if len(f.Enum) > 0 {
		u += " [" + strings.Join(f.Enum, ", ") + "]"
	}
	if f.Constraint != "" {
		u += " (" + f.Constraint + ")"
	}
	return u
}

// ---- small helpers ---------------------------------------------------------

// flagDisplayName overrides the CLI surface name for a few unintuitive wire
// keys. The JSON wire key (what we put in the request body) is unchanged; only
// the flag an agent types differs. "p" → "page" because a bare "--p" is the
// single most-guessed-wrong list flag (audit), and no request field uses the
// wire "page", so the rename is collision-free.
var flagDisplayName = map[string]string{"p": "page"}

func flagName(wire string) string {
	if n, ok := flagDisplayName[wire]; ok {
		return n
	}
	return kebab(wire)
}
func flagVar(wire string) string { return "f" + pascal(tokens(wire)) }

// parsedTimeVar / okTimeVar name the runtime locals a relative-time flag parses
// into (the unix-seconds value and whether the flag was set).
func parsedTimeVar(wire string) string { return "v" + pascal(tokens(wire)) }
func okTimeVar(wire string) string     { return "ok" + pascal(tokens(wire)) }

// isUnixSecondsField reports whether an integer request field is a unix-SECONDS
// timestamp — the only kind for which a relative-time flag ("7d"/"now"/date)
// makes sense. It deliberately excludes:
//   - millisecond timestamps (RUM/sourcemap/webhook windows): timeutil.Parse
//     yields seconds, which would be 1000x wrong;
//   - durations ("timeout in seconds", "seconds_to_ack", "delay_seconds"): a
//     count of seconds, not a point in time.
//
// Detection in priority order:
//  1. millisecond exclusion always wins (so a misleading name can't override it);
//  2. the description names it a unix/epoch-seconds timestamp (the common case);
//  3. name conventions for fields the description under-documents:
//     - a bare window boundary `start`/`end` (schedule windows describe these in
//     prose only, e.g. scheduleList.start), and
//     - the `<point>_at_…_seconds` timestamp convention (close_at_seconds,
//     created_at_start_seconds). The `_at_` point-in-time marker is what
//     distinguishes these from a `delay_seconds`-style duration, which has none.
func isUnixSecondsField(name, kind, desc string) bool {
	if kind != "int" {
		return false
	}
	d := strings.ToLower(desc)
	if strings.Contains(d, "millisecond") {
		return false
	}
	if (strings.Contains(d, "unix") || strings.Contains(d, "epoch")) && strings.Contains(d, "second") {
		return true
	}
	n := strings.ToLower(name)
	if n == "start" || n == "end" {
		return true
	}
	return strings.HasSuffix(n, "_seconds") && strings.Contains(n, "_at_")
}

// relativeTimeHint documents the forms a relative-time flag accepts. Appended to
// BOTH the cobra flag usage and the Long "Request fields" doc line so the two
// renderings of the same flag agree (and the agent skill-doc corpus, which reads
// the Long block, sees the relative-time capability).
const relativeTimeHint = " Accepts a duration (7d, 24h), '+7d' for the future, 'now', a date, or Unix seconds."

func goFlagType(kind string) string {
	switch kind {
	case "string":
		return "string"
	case "bool":
		return "bool"
	case "int":
		return "int64"
	case "float":
		return "float64"
	case "[]string":
		return "[]string"
	case "[]int":
		return "[]int"
	}
	return "string"
}

func flagSetter(kind string) string {
	switch kind {
	case "string":
		return "StringVar"
	case "bool":
		return "BoolVar"
	case "int":
		return "Int64Var"
	case "float":
		return "Float64Var"
	case "[]string":
		return "StringSliceVar"
	case "[]int":
		return "IntSliceVar"
	}
	return "StringVar"
}

func flagZero(kind string) string {
	switch kind {
	case "string":
		return `""`
	case "bool":
		return "false"
	case "int":
		return "0"
	case "float":
		return "0"
	case "[]string":
		return "nil"
	case "[]int":
		return "nil"
	}
	return `""`
}

func pathSegs(p string) []string {
	var out []string
	for _, s := range strings.Split(p, "/") {
		if s != "" {
			out = append(out, s)
		}
	}
	return out
}

// cliGroup is the top-level command group for an operation: the kebab of its
// first path segment. Generated ops merge into the curated group of the same
// name (e.g. /incident/* joins the curated `incident` command).
func cliGroup(path string) string { return kebab(pathSegs(path)[0]) }

// cliVerb is the leaf verb: the remaining path segments after the group,
// hyphen-joined. A single-segment path uses that segment as the verb. Because
// every operation becomes exactly one leaf (never a parent of another op), this
// flat shape is collision-free even for prefix-nested paths.
func cliVerb(path string) string {
	segs := pathSegs(path)
	if len(segs) == 1 {
		return kebab(segs[0])
	}
	return strings.Join(mapSlice(segs[1:], kebab), "-")
}

// computeGroupShorts assigns each top-level group a one-line description. A group
// that holds a single tag's ops uses that tag; a group spanning several tags
// (e.g. `monit` = Alert rules + Data sources + Rule sets) uses their common
// tag-prefix ("Monitors"). Groups that merge into a curated command keep the
// curated short (genGroup reuses the existing command), so this only sets the
// short for generated-only groups.
func computeGroupShorts(services []service) map[string]string {
	tagsByGroup := map[string]map[string]bool{}
	for _, s := range services {
		for _, o := range s.Ops {
			g := cliGroup(o.Path)
			if tagsByGroup[g] == nil {
				tagsByGroup[g] = map[string]bool{}
			}
			tagsByGroup[g][s.Tag] = true
		}
	}
	out := map[string]string{}
	for g, set := range tagsByGroup {
		var tags []string
		for t := range set {
			tags = append(tags, t)
		}
		sort.Strings(tags)
		out[g] = groupShort(tags)
	}
	return out
}

func groupShort(tags []string) string {
	if len(tags) == 0 {
		return "Flashduty API"
	}
	if len(tags) == 1 {
		return tags[0] + " API"
	}
	common := strings.Split(tags[0], "/")
	for _, t := range tags[1:] {
		segs := strings.Split(t, "/")
		i := 0
		for i < len(common) && i < len(segs) && common[i] == segs[i] {
			i++
		}
		common = common[:i]
	}
	if len(common) > 0 {
		return strings.Join(common, "/") + " API"
	}
	return "Flashduty API"
}

func sanitize(s string) string {
	var b strings.Builder
	for _, t := range tokens(s) {
		b.WriteString(pascalToken(t))
	}
	return b.String()
}

func mapSlice(in []string, f func(string) string) []string {
	out := make([]string, len(in))
	for i, s := range in {
		out[i] = f(s)
	}
	return out
}

func oneLine(s string) string {
	s = strings.ReplaceAll(s, "\n", " ")
	s = strings.ReplaceAll(s, "\r", " ")
	return strings.Join(strings.Fields(s), " ")
}

func quoteMultiline(s string) string { return "`" + strings.ReplaceAll(s, "`", "'") + "`" }

func enumStrings(s map[string]any) []string {
	var out []string
	for _, v := range asSlice(s["enum"]) {
		if str, ok := v.(string); ok && str != "" {
			out = append(out, str)
		}
	}
	return out
}

func boolOf(v any) bool { b, _ := v.(bool); return b }

func refName(s map[string]any) string {
	ref, _ := s["$ref"].(string)
	if ref == "" {
		return ""
	}
	return ref[strings.LastIndex(ref, "/")+1:]
}

func asMap(v any) map[string]any { m, _ := v.(map[string]any); return m }
func asSlice(v any) []any        { s, _ := v.([]any); return s }
func str(m map[string]any, k string) string {
	s, _ := m[k].(string)
	return s
}

func fileName(svc string) string {
	var b strings.Builder
	for i, r := range svc {
		if r >= 'A' && r <= 'Z' {
			if i > 0 {
				b.WriteByte('_')
			}
			b.WriteRune(r - 'A' + 'a')
		} else {
			b.WriteRune(r)
		}
	}
	return b.String()
}

func writeGo(path, src string) error {
	formatted, err := format.Source([]byte(src))
	if err != nil {
		_ = os.WriteFile(path, []byte(src), 0o644)
		return fmt.Errorf("format %s: %w", filepath.Base(path), err)
	}
	return os.WriteFile(path, formatted, 0o644)
}

func loadSpec(path string) (map[string]any, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	var spec map[string]any
	if err := json.Unmarshal(data, &spec); err != nil {
		return nil, fmt.Errorf("parse spec: %w", err)
	}
	return spec, nil
}

// specPath resolves the openapi.en.json shipped in the linked go-flashduty
// module, so the CLI always generates against the spec its SDK was built from.
func specPath() (string, error) {
	out, err := exec.Command("go", "list", "-m", "-f", "{{.Dir}}", "github.com/flashcatcloud/go-flashduty").Output()
	if err != nil {
		return "", fmt.Errorf("locate go-flashduty module: %w", err)
	}
	dir := strings.TrimSpace(string(out))
	return filepath.Join(dir, "openapi", "openapi.en.json"), nil
}

func repoRoot() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for dir := wd; ; {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", wd)
		}
		dir = parent
	}
}
